### ISSUE TITLE
Overpass turbo: getting the centroid of polygons

### ISSUE THREAD

**Issue by severinmenard** [tyrasd/overpass-turbo#114]
if I use a normal script or the wizard eg to get all the schools over an area, I will get both nodes and closed ways. For the latter, it happens when people put the amenity=school on a polygon (typically a landuse). 
This heterogeneous data is not easy to reuse afterwards, eg in uMap where only the odes will be displayed as (clusterable) markers. Yohan Boniface provided me a tip to get I guess centroids of the polygon through overpass:
````
(
  node({{bbox}})[amenity=school];
  way({{bbox}})[amenity=school];
);
(._;>;);
out center;
````

It works fine but (._;>;); is not really user friendly (actually not at all) and a blocker for non techy people
Would it be possible to add checkboxes in the wizard window to get the same results?

**Comment by tyrasd** [comment]
@pyrog: good idea. I've created a separate ticket for that: #136.
