### ISSUE TITLE
user-history using attic data

### ISSUE THREAD

**Issue by mvigerske** [tyrasd/overpass-turbo#115]
Hi,

we are teaching our cartography-students to work with OSM. Each student has his own task to do and his own OSM-username. I try to find a way to download/see the history of each student. Under http://www.openstreetmap.org/user/.../history I can see every node touched by a student. But I can't download it or can't see all lines and polys in one map. If I want to check the work of each student, I have to click through all these nodes... thats a never ending story...

This is why I need to find a way to download the data of each student. The OSM Board (http://forum.openstreetmap.org/viewtopic.php?pid=464487) gave me the clue to use the overpass API and its newly implemented attic-data. 
Right now, I would ask http://overpass-turbo.eu to show me all "user:..." but that only gives me the data which was touched finally(!) by this user.
Maybe there is a way to ask for the user-data at a specific time?

Thanks a lot,
Drongo

**Comment by tyrasd** [comment]
I'm closing this ticket as it is not really a bug with overpass turbo.
I would recommend using places like http://help.openstreetmap.org for such questions in the future.
