### ISSUE TITLE
Adjust MapCSS without re-running query

### ISSUE THREAD

**Issue by mmd-osm** [tyrasd/overpass-turbo#123]
I'd like to apply changes to a MapCSS style without the need to rerun my query.

Rationale: As most people are not able to write perfect MapCSS right from the start, several iterations are usually needed. A long running query interferes quite a bit with this iterative prototyping approach.

**Comment by tyrasd** [comment]
I do still like the idea, is there a particular reason for closing this ticket (and a few other issues)?

**Comment by mmd-osm** [comment]
Well, I have revisited a number of issues I created in the past and re-evaluated how important they are to me today. If the issue described in the ticket didn't bother me in the last 6-12 months, it's probably not worthwhile implementing that feature anymore :)
Please feel free to re-open tickets, you may still find useful, though.

**Comment by bjohas** [comment]
I think this is quite useful. Running queries can take time, and running a query multiple times certainly takes time. It would be very handy if new CSS could be applied without re-running the query, effectively caching the data. I'm trying to use OverpassTurbo for issue detection, and being able to adjust MapCSS without re-running the query would be very helpful.

**Comment by martinum4** [comment]
Hello, is there an update on this? It would really come in handy in regard of quickly editing styles, especially with bigger datasets.

**Comment by OneKN1** [comment]
I came accross this issue while I'm trying with MapCSS. A tiny change on the style puts load on the overpass-api server as the complete query has to be run again.

**Comment by simon04** [comment]
This feature is live at https://tyrasd.github.io/overpass-turbo/

@tyrasd, shall re push a new release to https://overpass-turbo.eu/?

**Comment by cloudrac3r** [comment]
I am finding this helpful on https://tyrasd.github.io/overpass-turbo/ ! Can it be added to https://overpass-turbo.eu/ ?

**Comment by tyrasd** [comment]
@cloudrac3r the feature should be available on overpass-turbo.eu since a few months ago (and works for me just fine). Could you perhaps share a query where it is not working to detect the mapcss properly?

**Comment by cloudrac3r** [comment]
My apologies, I misunderstood how the feature works. After some more experiments, I found out that I have to enter a query that uses MapCSS and click Run. After that, the circle-arrows button to apply MapCSS changes appears in the top bar. Now that I understand it, it is working as intended. Sorry, my bad!
