### ISSUE TITLE
Does Intelligent Wizard works for all languages?

### ISSUE THREAD

**Issue by pyrog** [tyrasd/overpass-turbo#127]
Intelligent Wizard works for some language, but don't for others:
* ["Bus Station" in "San Francisco"](http://overpass-turbo.eu/s/6Fb) or
* French: ["arrêt de bus" in Annecy](http://overpass-turbo.eu/s/6F9) work fine
* Italian: **"Stazione degli autobus" in Parma** or
* German: ** Busbahnhof in Munchen** or
* Spanish: **"Estación de autobuses" in Madrid** don't

**Comment by tyrasd** [comment]
Yes, turbo first tries to look up terms in your UI language (either auto detected or as set in the settings) and falls back to English if nothing is found. In principle, this is the expected behavior…
