### ISSUE TITLE
button for disableing piwik analyzer

### ISSUE THREAD

**Issue by jotpe** [tyrasd/overpass-turbo#132]
Would be great if I could disable your piwik web analyzer, while working on overpass-turbo.eu . 

Its great that you can change the url for the overpass instance. But if I changed it to a local private one, please don't log it by default.

Regards Johannes

**Comment by tyrasd** [comment]
There will be a piwik out-out button to the settings dialog with the next release (which will be soon). (See also this older discussion on the [osm wiki](http://wiki.openstreetmap.org/wiki/Talk:Overpass_turbo#Piwik_Tracking).)
But, can you elaborate why you think that tracking should be disabled once one uses a localhost API server? I don't really get what difference that makes (note that no queries, settings or even result data is sent to piwik)…

**Comment by jotpe** [comment]
Great.

> (note that no queries, settings or even result data is sent to piwik)…
I didn't know that, maybe others too.
Because people don't expects tracking on private instances. Load data or meta data have same importance. (Wir wollen nur eure Zweitstimme...) 
Maybe give an advice about tracking on startup...

Regards Johannes

**Comment by tyrasd** [comment]
piwik out-out is now live on overpass-turbo.eu

**Comment by jotpe** [comment]
Removed totally?
