### ISSUE TITLE
How can i send the request and receive the response ?

### ISSUE THREAD

**Issue by m4xell** [tyrasd/overpass-turbo#135]
How can i send the request and receive the response via java language (JSON format). Where i must send the request ? (what is the ip ).

**Comment by Abbe98** [comment]
Overpass Turbo is just for developing queries. You should look at the [Overpass API](https://wiki.openstreetmap.org/wiki/Overpass_API).

**Comment by tyrasd** [comment]
In addition to what Abbe said, there is a link you can get via the *export* menu called *raw data from Overpass API* which is probably what you are looking for.
