### ISSUE TITLE
Case insensitive query with key regex doesn't work in Overpass QL

### ISSUE THREAD

**Issue by SpocWeb** [tyrasd/overpass-turbo#141]
But it works in Overpass XML. Example: 
This works: `rel['name',i~".*Uelzen.*",i];`
This does NOT work: `rel[~'name.*',i~".*uelzen.*",i];`
Neither does this: `rel[~'name.*'~".*uelzen.*",i];`
But in Overpass XML it works: 
````
<osm-script timeout="25">
	<query into="_" type="relation">
	  <has-kv case="ignore" regk="name.*" modv="" regv=".*uelzen.*"/>
	</query>
  <print e="" from="_" geometry="skeleton" limit="" mode="body" n="" order="quadtile" s="" w=""/>
</osm-script>
````

It seems I have to fall back to specific Languages. This seems to be faster anyway:
````
(
rel['name'~'.*uelzen.*',i];
rel['name:de'~'.*uelzen.*',i];
rel['name:en'~'.*uelzen.*',i];
);
out  qt;
````

**Comment by tyrasd** [comment]
As far as I know case-insensitive regexes on keys are not yet supported by the Overpass API, so the second example is expected to fail. But your third example looks weird.
 
As this is an upstream problem with the Overpass API, I have moved the [ticket](https://github.com/drolbr/Overpass-API/issues/182) there.
