### ISSUE TITLE
too much optimizing when converting Overpass QL to compact 

### ISSUE THREAD

**Issue by malenki** [tyrasd/overpass-turbo#142]
[This query](http://overpass-turbo.eu/s/76P) returns 46 weirs. When exporting it to compact, a ".rivers" gets dropped and the result are only 9 weirs.

(sanderd17 helped creating this query and debugging it)

**Comment by mmd-osm** [comment]
I think you should report this upstream at Overpass API: https://github.com/drolbr/Overpass-API

**Comment by tyrasd** [comment]
Also: I cannot reproduce the actual issue. Yes, the `.rivers` is optimized away in the compact version (whether or not this should be done, idk). But both queries give the same results to me…

**Comment by mmd-osm** [comment]
@tyrasd : I can confirm the issue: also, in my case the converted query returns just 8 nodes (might be due to different screen resolution) http://overpass-turbo.eu/s/777   - while http://overpass-turbo.eu/s/76P produces 44 nodes.

**Comment by tyrasd** [comment]
Oh, now I see it, too. (Don't know what I was looking at earlier… :confused: ) Thanks for the clarification!
