### ISSUE TITLE
Wizard: add a greater/less than operator

### ISSUE THREAD

**Issue by sabas** [tyrasd/overpass-turbo#143]
While overpass api doesn't support comparison operators for numerical operators (https://github.com/drolbr/Overpass-API/issues/78) it could be useful to add a shortcut in the wizard which compiles to a regex
Example, for width<5 it translates (a thread in italian mailing list resulted in this example)
```
width~=/^[0-4]{1}([.][0-9]{0,2})/
```

Also, does escaping with backslash works? because I originally wrote "\." but the correct way was using "[.]".

**Comment by tyrasd** [comment]
Even though this is a funny idea, I'll *probably* not implement it, because it would potentially encourage using such hacky workaround. It would be best to have this implemented in the Overpass API.

Yes, escaping with a backslash should work: `\.` (in the final ql-query this then looks like `node["width"~"\\."]`).

**Comment by sabas** [comment]
Thanks :-)

**Comment by sigfrido** [comment]
We should also take into account that tags which are expected to hold numeric values ("width" in our case) may also contain mixed numeric / string values ("5 m" or "15 ft") or deprecated string values ("narrow"). If the latter case can be dealt with by means of validation, a numeric comparison should also take into account units of measure (or at least work smooth even if a unit is specified).

**Comment by mmd-osm** [comment]
@sigfrido: I would encourage you to also add all of your requirements (different unit of measures, different formatting, etc.) to the Overpass API ticket mentioned by @sabas : https://github.com/drolbr/Overpass-API/issues/78.

**Comment by mmd-osm** [comment]
See http://gis.19327.n8.nabble.com/Date-ranges-with-Overpass-API-td5886864.html
