### ISSUE TITLE
Nodes missing tags

### ISSUE THREAD

**Issue by drolbr** [tyrasd/overpass-turbo#146]
In the following query
http://overpass-turbo.eu/s/7lu
the explicitly found nodes have tags, as can be seen in the data view. But when clicking on a node in the map view, no tags are shown.

An example are the nodes in this query
http://overpass-turbo.eu/s/7lv
But the other nodes from the query above show the same problem.

**Comment by tyrasd** [comment]
Confirming the issue. Apparently the looks like the full geometry output overrides the nodes' tag information, which should not happen. I'll take a look at it (also, this is somewhat related to https://github.com/tyrasd/osmtogeojson/issues/23).

**Comment by tyrasd** [comment]
fixed in https://github.com/tyrasd/osmtogeojson/commit/6538a3b505b460318e555b103bcb1952260a0f46

**Comment by drolbr** [comment]
Danke!
