### ISSUE TITLE
Inconsistent output between the API and GUI

### ISSUE THREAD

**Issue by jonaspovilas** [tyrasd/overpass-turbo#147]
When I use the following: 

http://overpass-api.de/api/interpreter?data=[out:json];node[%22building%22](44.567499,-123.281392,44.57,-123.277819);way[%22building%22](44.567499,-123.281392,44.57,-123.277819);relation[%22building%22](44.567499,-123.281392,44.569693,-123.277819);out%20body%20geom;out%20skel%20qt;%20

versus pasting this into http://overpass-turbo.eu/ and exporting the results as geoJSON

````
 /*  ---------All buildings in a tight bounding box centered on Monroe & 25th ---------- */
[out:json][timeout:25];
// gather results
(
  // query part for: “building=*”
  node["building"](44.567499,-123.281392,44.569693,-123.277819);
  way["building"](44.567499,-123.281392,44.569693,-123.277819);
  relation["building"](44.567499,-123.281392,44.569693,-123.277819);
);
// print results
out body;
>;
out skel qt;
````
I get the correct # of buildings (21) in the latter but only (2) buildings in the former. 

Any ideas as to why?

![311](https://cloud.githubusercontent.com/assets/8727186/6172275/89a392a4-b294-11e4-892c-e264ff31680c.JPG)

**Comment by jonaspovilas** [comment]
I see a pattern.. it seems that the api/interpreter only finds buildings which are defined in a node tag: 

109   "tags": {
110     "addr:housenumber": "101",
111     "addr:street": "Southwest 26th Street",
112     "alt_name": "OAB",
113     "building": "yes",
114     "name": "Ocean Administration Building",
115     "type": "multipolygon" 
116   }

but fails to provide a way to get the buildings defined as Features..

218       "type": "Feature",
219       "id": "way/41376290",
220       "properties": {
221         "@id": "way/41376290",
222         "alt_name": "BalE",
223         "building": "yes" 
224       },

19 of the buildings are "Type:Feature" and not found. 

How is the GUI able to get and export this data from the above query? 

thanks, 

Jonas

**Comment by tyrasd** [comment]
The query you are using with the overpass interpreter is slightly different than the query you use in turbo. For example, look at the output part: `out%20body%20geom;out%20skel%20qt;`. Decoded this reads `out body geom;out skel qt;`. In overpass turbo you have `out body; >; out skel qt;`. Also, in the API query the parentheses around the node/way/relation parts are missing. This explains why you don't get whole result.

I would suggest to use the *raw data directly from Overpass API* export mode from within overpass turbo to conveniently convert a query into a ready-to-use API-interpreter link.
