### ISSUE TITLE
SSL certificate for https:overpass-turbo.eu/ is expired 

### ISSUE THREAD

**Issue by Stephen-m** [tyrasd/overpass-turbo#151]
SSL certificate for https://overpass-turbo.eu/ is expired yesterday (2015-03-25)

**Comment by tyrasd** [comment]
actually, there was never a matching ssl certificate for overpass-turbo in place. The site is reachable via https, but the respective certificate is issued only for the shared webhosting provider/server (lupus.uberspace.de).

**Comment by tyrasd** [comment]
fixed in #167
