### ISSUE TITLE
"zoom to data" throws Syntax error in JS console

### ISSUE THREAD

**Issue by tilmanb** [tyrasd/overpass-turbo#153]
When clicking "auf die Daten zoomen" the JS console displays "SyntaxError: return not in function".

Tested using Firefox 37.0

This is probably due to js/ide.js#L344 setting href="javascript:return false;".

Probably it may be better to set href = '#' and then appending "return false;" to the onclick handlers.

I am hesitant to create a pull request for that, because i am not an expert on browser compatibility issues that may arise...

**Comment by tyrasd** [comment]
thanks for noticing!
