### ISSUE TITLE
Any idea how do I get the boundary coordinates of a region from Google maps ?

### ISSUE THREAD

**Issue by bismoy2013** [tyrasd/overpass-turbo#164]
Google Map has started highlighting search areas in Pink color. How do I get all the boundary coordinates of that place? Google doesn't provide any apis for that, Hope this question is clear enough :)

Reference : http://stackoverflow.com/questions/12194046/google-maps-api-v3-how-to-get-region-border-coordinates-polyline-data

**Comment by tyrasd** [comment]
closing for the same reason explained in https://github.com/Leaflet/Leaflet/issues/3468

**Comment by tyrasd** [comment]
btw: if you'd like to use openstreetmap data instead, here is an example how to get the area of a region by name:
http://overpass-turbo.eu/s/9kF, or just the bounds: http://overpass-turbo.eu/s/9kH

**Comment by bismoy2013** [comment]
Well thanks very much for taking your time and providing these links, but how will I get the boundary coordiantes , for example I found a nice link based on Oepnstreet map , the kml format datas are really coming out to be cool and useful , http://global.mapit.mysociety.org/area/29746.html , needed something like this for India regions atleast :)

**Comment by stephan75** [comment]
Have a look at the web service from OSM user Wambacher at
https://osm.wno-edv-service.de/boundaries/

try the text search box, or the tree structure on the left.

If you found your needed region, use the export feature to get boundaries in different formats.

**Comment by bismoy2013** [comment]
Thanks @stephan75 for the comment, but this looks like it's available only for countries not for different citities within different countries . Or may be I am missing something ?

By the way I'm trying to get Openstreetmap relation id for different cities, and don't know how to get the list . Have a look at the link : http://global.mapit.mysociety.org/area/29746.html

http://polygons.openstreetmap.fr/index.py?id=71525

**Comment by tyrasd** [comment]
as explained above, this is getting much too much off-topic here. @bismoy2013: please use a more appropriate discussion platform. If you'd like to use OpenStreetMap, you could ask your questions on https://help.openstreetmap.org/ for example (a tip: try to phrase your question as concrete as possible and have someone look over your English – no offence, but there appears to be a bit of a language barrier involved). Or maybe there is even a local [forum](http://forum.openstreetmap.org/) or [mailing list](http://lists.openstreetmap.org/) for your country.
