### ISSUE TITLE
wizard/Nominatim: searching in places broken

### ISSUE THREAD

**Issue by malenki** [tyrasd/overpass-turbo#165]
When entering e.g. 

    sport=skateboarding in Berlin

and exectuing the query, overpass turbo immediately returns 

    Nominatim Error
    Could not find anything with the following name: Berlin

**Comment by tyrasd** [comment]
see http://wiki.openstreetmap.org/wiki/Talk:Overpass_turbo#in_doesn.27t_seem_to_work_in_wizard

Does it still fail in the [master](http://overpass-turbo.eu/master/) branch?

**Comment by mmd-osm** [comment]
Message on Javascript console:

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://nominatim.openstreetmap.org/search?X-Requested-With=overpass-turbo&format=json&q=Berlin. (Reason: CORS header 'Access-Control-Allow-Origin' missing).
An error occured while contacting the osm search server nominatim.openstreetmap.org :(
turbo.m...5-04-23 (line 25)
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://nominatim.openstreetmap.org/search?X-Requested-With=overpass-turbo&format=json&q=Berlin. (Reason: CORS request failed).
```

**Comment by tyrasd** [comment]
Thanks for linking the ticket. To me it looks like to be a firefox bug, actually.

The only issue with adding overpass turbo to HTTPSeverywhere is that I don't have a signed certificate for https://overpass-turbo.eu/.

An alternative workaround would be to hardcode all nominatim queries to `https`…

**Comment by tyrasd** [comment]
> An alternative workaround would be to hardcode all nominatim queries to https…

this is now live on the main instance

**Comment by malenki** [comment]
Martin Raifer schrieb
am Mon, 18 May 2015 13:16:41 -0700:

> > An alternative workaround would be to hardcode all nominatim
> > queries to https…
> 
> this is now live on the main instance

Thanks for the quick fix, although I filed a quite incomplete issue.
(Yes, I experienced it with FF and didn't test other browsers.)

**Comment by HolgerJeromin** [comment]
You can get a certificate for free from Startssl.
