### ISSUE TITLE
Error during export interactive map

### ISSUE THREAD

**Issue by GaMsh** [tyrasd/overpass-turbo#169]
Hi!
I try export in interactive this query: http://overpass-turbo.eu/s/6Qg

But exported map includes ONLY node, not show way, relation =(

Please fix it.

**Comment by tyrasd** [comment]
The features are there, but only very small (not displayed as circle markers as on overpass turbo itself).

fixing that is already covered in #23, so I'm closing this one as a duplicate

**Comment by tyrasd** [comment]
PS: as a temporal workaround you could consider using the `geometry="center"` output mode: http://overpass-turbo.eu/s/9ub

**Comment by GaMsh** [comment]
Thank you!
