### ISSUE TITLE
RTL problem for arabic name

### ISSUE THREAD

**Issue by Stalfur** [tyrasd/overpass-turbo#170]
I was going to do a query on settlements in Qatar but I get no data from my query, neither from overpass-api or using webform in overpass-turbo.

    area[name="قطر"];(node[place="city"](area););out;

Same logic gives me cities in places with LTR names (Ísland, South Africa etc) but this fails in returning any data.

**Comment by drolbr** [comment]
The server has received the sequence of hex bytes:
d9 82 d8 b7 d8 b1
but the name tag contains the value as hex bytes:
e2 80 8f d9 82 d8 b7 d8 b1 e2 80 8e

This happens from overpass-turbo as well as from the simpler form. Hence I suppose that it is some browser encoding problem or an evil character in the tag. @Stalfur: could you please do some research what the purpose of "e2 80 8e" and "e2 80 8f" is and whether these should be in the tag name?

**Comment by drolbr** [comment]
BTW: I suggest to investigate the simpler request

rel[name="قطر"];
out;

which exhibits the same problem.

**Comment by Stalfur** [comment]
e2 80 8e seems to be end of line character
e2 80 8f is a marker that means it is RTL https://en.wikipedia.org/wiki/Right-to-left_mark

**Comment by sanderd17** [comment]
Note that RTL and LTR marks are only needed in specific cases. And concatenating the some RTL strings with other strings (f.e. by including them in an XML) sometimes requires the marks to be added between those two strings. 

The Unicode bidi algorithm is rather complicated, and makes it being dependent on the definition of a "paragraph". Followed by interpretion if the overall paragraph is LTR or RTL, and then inserting some marks to flip certain signs correctly.

@Stalfur As an intermediate solution, you could work with regex search, and make those LTR and RTL marks an optional part of the string (not sure how to write these special marks in the browser though).

**Comment by drolbr** [comment]
Thank you for the explanation for the markers.

Precisely,

    rel[name~"قطر"];
    out;

which searches for the substring قطر, works or it also works

    rel[name~"^.قطر.$"];
    out;

which masks the special characters.

One last question. Are theses markers in this case necessary in the tag value? Given that there is no text before or behind the real name, they don't separate anything.

**Comment by tyrasd** [comment]
> Are theses markers in this case necessary in the tag value?

As far as [I can see](http://overpass-turbo.eu/s/9xy), most other RTL text doesn't seem to have these markers in them.

**Comment by tyrasd** [comment]
btw: @Stalfur:

For a generally  more robust (e.g. whitespace tolerant) search for objects by name, I strongly suggest using a proper geocoder instead of a hardcoded `name=…` selector directly in Overpass. In overpass turbo you can use the following "shortcut":http://wiki.openstreetmap.org/wiki/Overpass_turbo/Extended_Overpass_Queries#Available_Shortcuts:

    {{geocodeArea:قطر}};(node[place="city"](area););out;

**Comment by tyrasd** [comment]
(marking this as invalid because it's not actually a bug in overpass turbo or the Overpass API)

**Comment by Stalfur** [comment]
So problem was dirty data and poor querying from me?
