### ISSUE TITLE
runtime error: Query run out of memory is not returning http error code

### ISSUE THREAD

**Issue by matkoniecz** [tyrasd/overpass-turbo#176]
I would expect 412, 413 or 500 rather than 200 and note instead of expected data.

In my case it resulted in confusing bug where data seemed to be downloaded successfully (as no http error code was encountered) but it was unexpectedly empty.

My use case: https://github.com/matkoniecz/CartoCSSHelper/blob/master/lib/cartocss_helper/downloader.rb#L248

Overpass query in that case: http://overpass-api.de/api/interpreter?data=[timeout:600];(node(45.07091,5.845229999999999,47.27091,8.04523);%3C;);out%20meta;

**Comment by tyrasd** [comment]
yes, some run-time errors return a HTTP 200 status code. But actually, this is so "by design" as explained by Roland in this comment: https://github.com/tyrasd/overpass-turbo/issues/171#issuecomment-114361095

**Comment by matkoniecz** [comment]
I now wonder about proper way to detect failures like that as one may not rely on error code. 

Search for "<remark> runtime error:" in returned data - but is there possibility of other errors not giving proper http code? Is also possible that such string may appear in a valid response...

Parse xml and look for remark inside osm?

```
<?xml version="1.0" encoding="UTF-8"?>
<osm version="0.6" generator="Overpass API">
<note>The data included in this document is from www.openstreetmap.org. The data is made available under ODbL.</note>
<meta osm_base="2015-07-03T17:03:02Z"/>

<remark> runtime error: Query run out of memory in "recurse" at line 1 using about 541 MB of RAM. </remark>

</osm>
```

**Comment by mmd-osm** [comment]
@matkoniecz: I wonder why you discuss this topic on overpass turbo. The proper repository to discuss this is of course Overpass API: https://github.com/drolbr/Overpass-API
