### ISSUE TITLE
Set the map extent with a parameter in the URL

### ISSUE THREAD

**Issue by Gustry** [tyrasd/overpass-turbo#180]
In QuickOSM, we can open Overpass Turbo. I would like to pass, in the URL, an extent. Overpass Turbo will set the extent of the map canvas according to this parameter.

Even if there is no query in Overpass Turbo, it's only to show the same extent as in QGIS.
Because some people copy/paste queries from QuickOSM to Overpass Turbo and may think that they are using the same extent using the button.

One day, when I will have time, I will add a feature which allow users to open query from QuickOSM to Overpass Turbo. (and reverse thanks to a short link) https://github.com/3liz/QgisQuickOSMPlugin/issues/3

**Comment by mmd-osm** [comment]
There's a parameter for Map location & Zoom: http://wiki.openstreetmap.org/wiki/Overpass_turbo/Development#Map_Location_.26_Zoom

Doesn't this already support your requirement assuming a bit of additional calculation to convert an extent to a lat/lon/zoom format?

**Comment by Gustry** [comment]
Ok thanks. I forgot this page. I tried to do some reverse engineering with `lat`, `lon` ...
I will do that.
