### ISSUE TITLE
Different rendering results with out geom;

### ISSUE THREAD

**Issue by mmd-osm** [tyrasd/overpass-turbo#182]
I try to visualize highway ways which are also part of a landuse relation. 
When using `out geom;` I get some unexpected results:

![rend](https://cloud.githubusercontent.com/assets/5842757/8639011/bbe684d4-28cc-11e5-9e28-65a7aeda0992.png) ![rend2](https://cloud.githubusercontent.com/assets/5842757/8639012/bbea8066-28cc-11e5-8fa7-ac89aa8a4080.png)

Query 1:
```C
[bbox:{{bbox}}];
rel[landuse];
way(r)[highway];
out geom;
rel(bw)[landuse];
out geom;
```

http://overpass-turbo.eu/s/anH or as union http://overpass-turbo.eu/s/anJ

Query 2:

```C
[bbox:{{bbox}}];
rel[landuse];
( way(r)[highway];
  rel(bw)[landuse];
);
(._;>;);
out;
```

http://overpass-turbo.eu/s/anI or http://overpass-turbo.eu/s/anN

**Comment by tyrasd** [comment]
Solving this is going to be quite tricky (see https://github.com/tyrasd/osmtogeojson/issues/38#issuecomment-121146471).

Something like http://overpass-turbo.eu/s/apU could also be used as a workaround in the meantime…

**Comment by mmd-osm** [comment]
Cool! Thanks for fixing this tricky issue. :+1:
