### ISSUE TITLE
MapCSS escaping issue

### ISSUE THREAD

**Issue by mmd-osm** [tyrasd/overpass-turbo#186]
This issue is related to this forum post: http://forum.openstreetmap.org/viewtopic.php?id=32228

Overpass turbo's MapCSS implementation unfortunately doesn't escape the input as needed: http://overpass-turbo.eu/s/aPz

**Comment by tyrasd** [comment]
damn, that's embarrassing. I thought I paid attention about such stuff, apparently not well enough. :goat:

**Comment by mmd-osm** [comment]
Cool, thanks for the quick fix!

**Comment by mmd-osm** [comment]
Hmm, there seems to be a side effect of the most recent deployment, maybe some previous logic got somehow overwritten? http://osmlab.github.io/learnoverpass/en/docs/actions/print/ throws some error popups now.

**Comment by tyrasd** [comment]
it should now work again (no code fixes required, as it was some kind of strange auto-deploy issue, I guess: I just re-deployed the beta instance and everything seems to be in order now.)
