### ISSUE TITLE
Overpass-API runtime error 

### ISSUE THREAD

**Issue by leodobrasil** [tyrasd/overpass-turbo#194]
Dear maintainers...
Since today evening (08-22-2015) all request trials are aborted by a timeout error. What follows is the output line: 

  *<strong style="color:#FF0000">Error</strong>: runtime error: open64: 0 Success /osm3s_v0.7.51_osm_base Dispatcher_Client::request_read_and_idx::timeout. Probably the server is overcrowded.*

Trying from a different IP address resultet in the same error.
Hope that my ticket might be helpful to fix the bug.

Sincerely,
Leonhard

**Comment by marczoutendijk** [comment]
I'm experiencing the same error as of 08-24-2015.

**Comment by tyrasd** [comment]
confirming, but it's a problem with the main Overpass API server. //cc @drolbr

in the meantime you can switch to one of the alternative Overpass servers in the settings.

**Comment by tyrasd** [comment]
documented the downtime here: http://wiki.openstreetmap.org/wiki/Overpass_API/status#Reported_2015-08-25

**Comment by tyrasd** [comment]
> in the meantime you can switch to one of the alternative Overpass servers in the settings.

actually, I've deployed a quick hotfix in the meantime where all requests to *overpass-api.de/api* are automatically redirected to *http://overpass.osm.rambler.ru/cgi/*.

**Comment by tyrasd** [comment]
The overpass server seems to be fine again.

**Comment by leodobrasil** [comment]
Hello Martin,
well done. Thank you for keeping all running.
Leonhard

Am 25.08.2015 um 11:26 schrieb Martin Raifer:
