### ISSUE TITLE
change title of the page as query is running/completed

### ISSUE THREAD

**Issue by matkoniecz** [tyrasd/overpass-turbo#196]
Currently page title (visible in tabs) is always "overpass turbo". It would be useful to see state of query (running or completed).

This way it would be easy to check whatever query completed and it is possible to see results without switching to the overpass tab.

It is especially true for queries that are running for a long time.

**Comment by tyrasd** [comment]
nice idea!

**Comment by matkoniecz** [comment]
Thanks!
