### ISSUE TITLE
500 error/http://overpass-api.de/api/interpreter missing CORS?

### ISSUE THREAD

**Issue by Abbe98** [tyrasd/overpass-turbo#198]
![image](https://cloud.githubusercontent.com/assets/2631719/9701373/bdae68b6-5425-11e5-88e2-64a28ea17d1a.png)

Running the following(invalid) [Overpass query](http://overpass-turbo.eu/s/biP).

**Comment by tyrasd** [comment]
It's a bug of the Overpass-API. Let's discuss it there: https://github.com/drolbr/Overpass-API/issues/227
