### ISSUE TITLE
"Another request from your IP is still running", but there is no other request

### ISSUE THREAD

**Issue by HostedDinner** [tyrasd/overpass-turbo#199]
I get this error:
> runtime error: […] Another request from your IP is still running.

but I'm not running any other request at the moment. Maybe it's an IPv6 issue? I know some programs will split IPv6 after the first `:` and treat everything with the same prefix as one IP.
Or is it a issue with the overpass api? (Because some times I get a "Too many requests" error on osm main page, when I query things.

**Comment by tyrasd** [comment]
The error message `"Another request from your IP is still running"` comes directly from the Overpass API, so it has nothing to do with overpass turbo itself. Maybe the Overpass API server has difficulty parsing the ipv6 address or something (or are you on a shared internet connection behind a NAT where another user could have requests running?). Do you mind opening a ticket there (https://github.com/drolbr/Overpass-API/issues)?

**Comment by HostedDinner** [comment]
Ok, I will open an issue there. (And no, its not a shared connection)

**Comment by HolgerJeromin** [comment]
Perhaps you have the same problem as already reported?
https://github.com/drolbr/Overpass-API/issues/223
