### ISSUE TITLE
unable to query "created_by" tag with value "~OsmAnd.*"

### ISSUE THREAD

**Issue by gitGOwin** [tyrasd/overpass-turbo#202]
I'm trying to find out how often OsmAnd is used for collecting POIs in a certain region [0]. I ran a query [1] using regex but it returns an empty result, although I know for a fact that POIs in the area exists as tag created_by=OsmAnd~ 2.1.1

Trying out a more generic query [1], using "created_by=*" produces results, but do not include those POIs with the value "OsmAnd~ 2.1.1". 

Would this have to do with the tilde within the tag value?

[0] http://www.openstreetmap.org/changeset/33974559
[1] http://overpass-turbo.eu/s/bp8
[2]  http://overpass-turbo.eu/s/bp7

**Comment by mmd-osm** [comment]
The tag "created_by" you're referring to is part of a *changeset*. At this time, you can only query for nodes, ways and relations. So, unfortunately, what you're trying to do here is currently impossible with Overpass API / overpass turbo.
