### ISSUE TITLE
geojson.io

### ISSUE THREAD

**Issue by d1g** [tyrasd/overpass-turbo#204]
Since we have export to github, http://geojson.io/ would be more useful than raw gist export?

overpass-turbo may delegate some functions to this service if developers are willing to collaborate.

**Comment by tyrasd** [comment]
actually, after exporting to github/gist, a direct link to geojson.io should appear in the result dialog along with the raw gist-link. So, you have both the direct access link to your data (for download, etc.) as well as the link to geojson.io for editing.

**Comment by d1g** [comment]
Aha, then I just missed it. Probably we want to give a clear hint "you may edit it with geojson.io later" before user leaves "export" tab or slightly restructure menu, export -> github -> geojson.io was unexpected:

* export -> github (gist)
* export -> geojson.io

**Comment by d1g** [comment]
Right now it states "export" -> "gist"; less confusing than github.
