### ISSUE TITLE
Show attribution on main map as well

### ISSUE THREAD

**Issue by matkoniecz** [tyrasd/overpass-turbo#205]
Also - why in https://github.com/tyrasd/overpass-turbo/blob/de58254c5645c4af06db4b73a501502be2821e79/js/configs.js attribution contains "Map:cc-by-sa"?

Is it about map style used by {s}.tile.openstreetmap.org/{z}/{x}/{y}.png ? In that case it is CC0 - see https://github.com/gravitystorm/openstreetmap-carto/blob/master/LICENSE.txt

**Comment by tyrasd** [comment]
This attribution string is displayed only on exported images (export->map->as image) and the *cc-by-sa* refers to the copyright of the actual OSM map tiles (not the map style source code), which is cc-by-sa according to the osm [copyright page](http://www.openstreetmap.org/copyright/en).

For general attribution, there is a whole section in the help dialog (help->attribution), which clearly states all used data sources, licences and libraries used by overpass turbo.

**Comment by matkoniecz** [comment]
I think that attribution should be also on the map itself - see 

> For a browsable electronic map, the credit should appear in the corner of the map.

on http://www.openstreetmap.org/copyright

**Comment by tyrasd** [comment]
Well, strictly speaking overpass turbo is quite a bit more than a browsable electronic map, the [community Legal FAQ](http://wiki.openstreetmap.org/wiki/Legal_FAQ#3a._I_would_like_to_use_OpenStreetMap_maps._How_should_I_credit_you.3F) suggests to put the attribution *in a place reasonable to the medium* (and other *applications* such as Mapbox Studio, Kosmtik, etc. don't have it on their main map displays, not even JOSM).

I'm not trying to hide OSM or anything and I do see that putting the attribution on the map as well wouldn't hurt. The only issue I have is that overpass turbo may not always display an OSM-based map in the background (it can be configured to display any tile provider in the settings) and is able to show any data provided by an Overpass API instance (which may or may not be OSM data). So, a static string wouldn't work too well.

I'll put it on my todo-list once I get around it.

**Comment by matkoniecz** [comment]
One of main reasons is that I sometimes share Overpass query and it would be nice to have it described as OSM data - without making it necessary to add explanation what is the source of data.

**Comment by tyrasd** [comment]
True. I'll see what I can do quickly.

**Comment by mackerski** [comment]
Could you give some attention to this failure to attribute on the map itself? The current approach is not in accordance with the Attribution Guidelines: https://wiki.osmfoundation.org/wiki/Licence/Attribution_Guidelines#:~:text=Attribution%20must%20be%20legible%20and,or%20next%20to%2C%20other%20attributions.

See in particular the first item in the bulleted list.
