### ISSUE TITLE
Keyborard shortcuts collide with national characters

### ISSUE THREAD

**Issue by RicoElectrico** [tyrasd/overpass-turbo#207]
I can't write Ó [AltGr+O] or Ś [AltGr+S] because they bring up open/save dialogs. Ctrl+Alt shortcuts should be avoided in general, due to national keyboars using them (Ctrl+Alt is equivalent to AltGr)

**Comment by tyrasd** [comment]
yes, that's  a bug, will fix asap

**Comment by tyrasd** [comment]
can you please check if the error is fixed on http://overpass-turbo.eu/master/?

**Comment by RicoElectrico** [comment]
Seems fine now. Thanks for prompt fixing. ;-)
