### ISSUE TITLE
Wizard cannot handle ":"

### ISSUE THREAD

**Issue by malenki** [tyrasd/overpass-turbo#208]
Telling the wizard to create a query for addr:housenumber results in a query for 
"addr"~"housenumber" which returns an empty dataset.
Replacing "addr"~"housenumber" with "addr:housenumber" by hand results in a working query.

**Comment by tyrasd** [comment]
The [`:` syntax](http://wiki.openstreetmap.org/wiki/Overpass_turbo/Wizard#Tag_Searches) is actually meant to mean a partial string search (as in JOSM's search tool) which is implemented via a regular expression in the resulting query.

If you want to search for tags with the key `addr:housenumber`, use `addr:housenumber=*` in the wizard.
