### ISSUE TITLE
Add URL parameter for source server

### ISSUE THREAD

**Issue by Abbe98** [tyrasd/overpass-turbo#211]

**Comment by tyrasd** [comment]
You can already do this by providing a `{{data:…}}` statement in the query text (see the documentation in the [wiki](http://wiki.openstreetmap.org/wiki/Overpass_turbo/Extended_Overpass_Queries#Other_Extensions) for the exact syntax).

**Comment by Abbe98** [comment]
Thanks! Was looking for it at the wrong page in the Wiki...
