### ISSUE TITLE
Overpass API endpoint provided in data extension ignored sometimes

### ISSUE THREAD

**Issue by mmd-osm** [tyrasd/overpass-turbo#212]
Testcase: http://overpass-turbo.eu/s/cnr

I'd like to load the results directly into JOSM via Export -> load data into JOSM.

Unfortunately, the server endpoint provided in the data extension is not considered, and as of one the statements is not yet supported on overpass-api.de, I get an error message.

At this time the only workaround is to manually enter the server endpoint underneath Settings -> Server

Brief tests showed that at least the following 3 export functions are affected by this:

* [ ] raw data directly from Overpass API
* [ ] load data into an OSM editor: JOSM
* [ ] load data into an OSM editor: Level0

**Comment by mmd-osm** [comment]
Thanks a lot for the quick fix!

I found a funny effect in Firefox 41 when I right click on "raw data directly from Overpass API" and then "Save Target as ...". Somehow this still triggers a download with the old URL, although the tooltip suggests that it's using the proper url. Left clicking on the link works ok though, i.e. data is downloaded from the correct server.

Level0 seems to have some own [URL checking](https://github.com/Zverik/Level0/blob/914578a38720c1ef3b387f43d01972b674f191ed/www/osmapi.php#L317) and refuses the test case. Maybe @Zverik could make that check a bit less restrictive and allow `*.overpass-api.de`.

**Comment by tyrasd** [comment]
:+1:

regarding Level0: yes, I've noticed that as well. Looks a bit like https://github.com/Zverik/Level0/issues/13.

**Comment by Zverik** [comment]
I've added `dev.overpass-api.de` to the list of regular expressions of Level0, and deployed the update.

**Comment by mmd-osm** [comment]
Re-test on Level0 also looks good, thanks to @Zverik!
