### ISSUE TITLE
Another request from your IP is still running

### ISSUE THREAD

**Issue by Bernard59118** [tyrasd/overpass-turbo#213]
Hello,
I no longer have the opportunity to question overpass, because I get the following message: "Another request from your IP is still running."
I received this message after several weeks without use. Having a fixed IP, I can change it.
Apparently other French users have this problem, see thread
https://lists.openstreetmap.org/pipermail/talk-fr/2015-November/078459.html
Thank you in advance for solving this problem.
Overpass is a useful tool
Best regards
Bernard

**Comment by tyrasd** [comment]
which API server are you using? the default overpass-api.de one?

//cc @drolbr

**Comment by Bernard59118** [comment]
http://overpass-turbo.eu/

**Comment by tyrasd** [comment]
so, you're using the default settings, right? That's strange as I didn't notice this behavior before.

Can you try to select one of the alternative API servers in *settings* -> *server* and see if that helps?

**Comment by tyrasd** [comment]
please take a look at https://github.com/drolbr/Overpass-API/issues/229, maybe that's the same problem.

**Comment by mmd-osm** [comment]
I guess a lot of people in France use "Free" as internet provider - that would be IPv6 range 2a01:e00::/26 - all of those users would be treated as one single user with the same prefix "2a01".

**Comment by Bernard59118** [comment]
Yes, I use the provider "free"
My IPv6 is like this :


    *2a01:e35:9aa99:9999::/64*

**Comment by Bernard59118** [comment]
Hello
my level of experise does not allow me to change the settings. I did not 
see where.
I use only by OverpassTurbo browser.
I useful as Firefox default browser.
I just tried "http://overpass-turbo.eu/" with Internet Explorer; and 
there it goes.
Nevertheless, the problem is not solved when I use Firefox.
I guess that's another problem.

**Comment by Bernard59118** [comment]
after a first successful trial with Explorer, the problem is the same !!!

**Comment by mmd-osm** [comment]
@Bernard59118 
did you try this suggestion already?
> **Can you try to select one of the alternative API servers in settings -> server and see if that helps?**

**Comment by mmd-osm** [comment]
@Bernard59118 : do you still face the issue today?

There's a fix available now, and I think it's already deployed.

**Comment by Bernard59118** [comment]
Hello,
Great, problem solved.
Thank you for intervention
Best regards
Bernard

**Comment by tyrasd** [comment]
perfect!
