### ISSUE TITLE
End user question: Return all users' edits except mine?

### ISSUE THREAD

**Issue by DaveF63** [tyrasd/overpass-turbo#214]
Hi
I'm currently using `<newer:5day and user:DaveF>` to find my edits in the previous specified time.

Is there a way to find edits by everybody else *except* mine? Tried a couple of combinations such as `<user:!DaveF>` but with no luck. To be able to do this would make a great validation checking tool.

**Comment by tyrasd** [comment]
yes, you can use the [difference](http://wiki.openstreetmap.org/wiki/Overpass_API/Overpass_QL#Difference)-operator: http://overpass-turbo.eu/s/cWE

PS: It would probably make sense to ask similar questions on http://help.osm.org instead of here, such that others can find and see the answer there.

**Comment by DaveF63** [comment]
Thanks for that, works well, although the unbalanced curved brackets look a bit strange.
  
>PS: It would probably make sense to ask similar questions on http://help.osm.org instead of here in the future, such that others can find and see the answer there.

OK, will do, but wherever I post these days it always appears to be in the wrong place and do all the expert Overpass experts peruse that forum?. I took advice from 'Help>About'. Maybe update it? :
