### ISSUE TITLE
regexp search with usernames

### ISSUE THREAD

**Issue by govvin** [tyrasd/overpass-turbo#218]
It used to be possible to search for objects by using a regular expression to search by user name like the query below:

    (
      node[user ~ "^(maning|ralleon|GOwin)$")({{bbox}});
    );
    out body;
    >;
    out skel qt;

However, I am unable to do this now and get the error message:
>parse error: ':' expected - '~' found.

Any advise?

**Comment by tyrasd** [comment]
As far as I know, it has never been possible to query for [users](http://wiki.openstreetmap.org/wiki/Overpass_API/Overpass_QL#By_user_.28user.2C_uid.29) by a regular expression. I only found the following open pull request https://github.com/drolbr/Overpass-API/pull/225 to add multi-user select functionality. Are you sure this used to work?

See also https://github.com/drolbr/Overpass-API/issues/112 for a related discussion.

**Comment by govvin** [comment]
Ooops. Now, I'm not sure if I actually got to use it. Maybe what I remember using were the script from https://github.com/pierzen/osm-contributor-stats to achieve the same purpose I had in mind.

:crying_cat_face:
