### ISSUE TITLE
Wizard - Is this expected behaviour?

### ISSUE THREAD

**Issue by DaveF63** [tyrasd/overpass-turbo#220]
Hi
Is this expected behaviour for the Wizard?:

![wizard](https://cloud.githubusercontent.com/assets/9528328/12453235/40d7e9ea-bf8a-11e5-8a69-462928bb035d.JPG)

Running crossing_ref=pelican & zara works as expected. Why is it failing on zebra?

Shouldn't there be a 'Yes, that is what I meant' override button?

**Comment by tyrasd** [comment]
The *or* operator may not work as you think it does… Basically it takes the condition to the left of it and the condition to the right of it and applies them both in a ql-query. Here, the second condition doesn't is missing the tag key, so the wizard doesn't know what to do with it. It then searches through a list of possible tag presets and finds *Zara* (which stands for `shop=clothes and name=Zara`) which looks reasonably similar to the input *zebra*.

If you want to search for multiple tag values, you have to repeat the tag key every time: `crossing_ref=pelican or crossing_ref=zebra` (or use a regexp which can be faster sometimes: `crossing_ref~/^(pelican|zebra)$/`).

**Comment by DaveF63** [comment]
Thanks. The repeat tag returns what I was expecting, but I'm struggling to understand the concept of the presets list. Couldn't it search everything & return whatever it finds? I realise this might give a lot of data, but that's what the abort/warning message is for.

PS Zara is a *very* niche preset
