### ISSUE TITLE
latlon in url?

### ISSUE THREAD

**Issue by dex2000** [tyrasd/overpass-turbo#222]
is it possible to load a latlon like http://overpass-turbo.eu/#51.574842|7.360047|18 or similar?

Background for that, i use a Linktool what generates Links to some qa-tools or maps etc. and in overpass-turbo i have to search every time the right image.

**Comment by tyrasd** [comment]
Yes, by setting the GET-parameter `C`: http://overpass-turbo.eu/?C=51.574842;7.360047;18
See http://wiki.openstreetmap.org/wiki/Overpass_turbo/Development#Map_Location_.26_Zoom

**Comment by dex2000** [comment]
Works fine, thx.
