### ISSUE TITLE
Support greater-than, less-than, etc

### ISSUE THREAD

**Issue by naoliv** [tyrasd/overpass-turbo#223]
Could overpass-turbo support greater-than, less-than, etc?
For example, if an user would like to have every highway with more than 3 lanes, he could use something like `[lanes > 3]`.

It should support `>`, `>=`, `<` and `<=`, if possible.

**Comment by tyrasd** [comment]
duplicate of https://github.com/drolbr/Overpass-API/issues/78. see also https://github.com/tyrasd/overpass-turbo/issues/143

**Comment by mmd-osm** [comment]
See http://gis.19327.n8.nabble.com/Date-ranges-with-Overpass-API-td5886864.html

**Comment by zwillikon** [comment]
@mmd-osm Hi, nabble has sadly gone offline.
