### ISSUE TITLE
Something is broken with areas

### ISSUE THREAD

**Issue by Vanuan** [tyrasd/overpass-turbo#226]
http://overpass-turbo.eu/s/eZu
Notice that there's more than one relation. What's wrong with it?

**Comment by tyrasd** [comment]
I'd guess that since the area database on overpass-api.de is quite outdated (~1 month old), the behavior you're seeing is just due to them being out-of-sync with the rest of the overpass db. When you switch over to the *openstreetmap.fr* server (which has more recent areas) in the settings, the query works just as expected.

**Comment by mmd-osm** [comment]
I reported this now on the status page: https://wiki.openstreetmap.org/wiki/Overpass_API/status

**Comment by Vanuan** [comment]
Ok, looks like server settings isn't included in the share link.

**Comment by Vanuan** [comment]
Does fr server has outdated areas too?

This http://www.openstreetmap.org/relation/1702215 shouldn't be part of http://www.openstreetmap.org/relation/72634

**Comment by Vanuan** [comment]
This one looks correct: http://overpass.osm.rambler.ru/cgi/
Either it's too old or too new. How do I verify that?

**Comment by Vanuan** [comment]
http://api.openstreetmap.fr/oapi/ (incorrect)
```
  "osm3s": {
    "timestamp_osm_base": "2016-03-14T22:29:02Z",
    "timestamp_areas_base": "2016-03-14T18:11:02Z",
  },

```

http://overpass.osm.rambler.ru/cgi/ (correct)
```
  "osm3s": {
    "timestamp_osm_base": "2016-03-10T21:02:02Z",
    "timestamp_areas_base": "2016-03-10T21:02:02Z",
    "copyright": "The data included in this document is from www.openstreetmap.org. The data is made available under ODbL."
  },

```

Still don't understand why http://www.openstreetmap.org/relation/1702215 is a part of http://www.openstreetmap.org/relation/72634

**Comment by tyrasd** [comment]
> http://overpass-turbo.eu/s/f1f

After the last area-update, this query doesn't include relation 1702215 anymore. Note that the geometry of a relation can change if nodes are moved or added/removed from it way members, which isn't reflected in the relation version number and date code.

**Comment by mmd-osm** [comment]
I wonder why we're discussing the exact same topic in 2 different tickets: https://github.com/drolbr/Overpass-API/issues/258#issuecomment-196555351

**Comment by tyrasd** [comment]
Right. Let's close this one.
