### ISSUE TITLE
Area generation

### ISSUE THREAD

**Issue by verdy-p** [tyrasd/overpass-turbo#228]
Area generation is stalled since 9 days:

>   "version": 0.6,
>   "generator": "Overpass API",
>   "osm3s": {
>     "timestamp_osm_base": "2016-04-07T14:04:02Z",
>     "timestamp_areas_base": "2016-03-30T00:26:01Z",

The timestamp for areas has not changed by a iota.

This causes selection problems for some reports (notably those using {{geocodeArea:country name}} for per-country reporting, which retrieve data from other bordering countries, if the internal border has been slighty moved by only a few meters).

How can we filter the requests, notably to eliminate the selection of very areas (such as country/region/cities) that are mostly located in fact in another country ? Can we specify a relation id instead and create our own "area" from its current geometry ?

This is less problematic for retrieving a list of nodes, but for retrieving long ways and large relations, the reports are simply false (a minor move of a single node by a few meters on a border causes a the selection of bordering polygon in OSM whose more than 99.9% of the surface is outside of the selection "area" used by Overpass, including positions that can be several hundreds kilomoters outside!).

**Comment by mmd-osm** [comment]
See https://github.com/drolbr/Overpass-API/issues/258 for a detailed discussion

**Comment by verdy-p** [comment]
The discussion is not about the fact that area generation is stalled since more than 9 days (the discussion says it should be updated every 6-12 hours, this is visibly not the case)

**Comment by verdy-p** [comment]
In other words this is not strictly a software issue (tracked by GitHub) but accurately reported here (it is an operational issue: some area-update daemon is not running on the server, or cannot start due to some issue such as incorrect connection parameters to the database, or missing update in firewall rules, or lack of working space in storage, or simply this daemon has been temporarily disabled for a maintenance, but not restarted)

**Comment by mmd-osm** [comment]
The ticket I mentioned describes a work around. Operational issues are best reported on the overpass api status page in osm wiki rather than github

**Comment by verdy-p** [comment]
Which link ??? The Help menu in Overpass drives us HERE !

There's NO link at all on the Overpass website to the API status page (which is also not made for tracking the state of external servers not hosted directly by the OSM Foundation). There's only a link to a generic talk page.

Please provide then an accurate page, and include it in the "Help" menu

**Comment by mmd-osm** [comment]
http://wiki.openstreetmap.org/wiki/Overpass_API/status

**Comment by verdy-p** [comment]
This status subpage is not linked from anywhere, not even from the parent page about Overpass API
It was hidden under the ambiguous term "details" in the general OSM status page (which currently displays a green "OK")...

**Comment by tyrasd** [comment]
I'll try to improve the help dialog by putting some more links there. see #229

**Comment by verdy-p** [comment]
Thanks for the modification of the message in the "feedback" section of the help menu
