### ISSUE TITLE
bring "interactive map" up to date

### ISSUE THREAD

**Issue by tyrasd** [tyrasd/overpass-turbo#23]
The *interactive map* (`map.html`) export has fallen behind the regular overpass turbo functionality quite a lot (e.g. mapcss, data statement, etc.). Bring it up to date.
* [x] MapCSS
* [x] Data Statement
* [ ] other [Parameters](http://wiki.openstreetmap.org/wiki/Overpass_turbo/Development)
* [x] small features rendering
* [ ] …?

**Comment by nounours77** [comment]
+2 - anything a newcomer could do to make this move? I'm ready to help ... but don't know this project yet.

**Comment by tyrasd** [comment]
Check out Arian's (@Secretmapper) awesome PR #173 on this, which adds MapCSS to the map.html "backend". Only thing missing is to adapt the export routine to make it not drop any present MapCSS statements. I'll update that one soon to get it ready for a release. :smiley:

**Comment by nounours77** [comment]
Looks great on the example!!! THANKS and really looking forward!!! :-)
I tryed to reproduce, but failed. Is this a bug, or did I not understand something basic.
Here my [example] (http://overpass-turbo.eu/master/map.html?Q=%3Cunion%3E%0A%20%20%3Cquery%20type%3D%22way%22%3E%0A%20%20%20%20%3Chas-kv%20k%3D%22mooring%22%20v%3D%22guest%22%2F%3E%0A%20%20%20%20%3Cbbox-query%20s%3D%2246.19599270020596%22%20w%3D%226.2017822265625%22%20n%3D%2246.55130547880643%22%20e%3D%226.6082763671875%22%2F%3E%0A%20%20%3C%2Fquery%3E%0A%20%20%3Cquery%20type%3D%22node%22%3E%0A%20%20%20%20%3Chas-kv%20k%3D%22mooring%22%20v%3D%22guest%22%2F%3E%0A%20%20%20%20%3Cbbox-query%20s%3D%2246.19599270020596%22%20w%3D%226.2017822265625%22%20n%3D%2246.55130547880643%22%20e%3D%226.6082763671875%22%2F%3E%0A%20%20%3C%2Fquery%3E%0A%20%3C%2Funion%3E%0A%3Cunion%3E%0A%20%20%20%20%3Citem%2F%3E%0A%20%20%20%20%3Crecurse%20type%3D%22down%22%2F%3E%0A%20%20%3C%2Funion%3E%0A%0A%0A%0A%0A%0A%0A%0A%0A%0A%0A%0A%0A%3Cprint%2F%3E), you should see boat icons, but you don't!

And here my skript I used: (I removed the lowerthan and biggerthan signs)
union
  query type="way"
    has-kv k="mooring" v="guest"/
    bbox-query {{bbox}}/
  /query
  query type="node"
    has-kv k="mooring" v="guest"/
    <bbox-query {{bbox}}/>
  /query
 /union
union
    item/
    recurse type="down"/
  /union
{{style:
  way[mooring=guest] {
    color: red;
    icon-image: url('http://www.sailcom.ch/images/grafik/Yacht.png');
  icon-width: 18; 
  }
    node[mooring=guest] {
    color: red;fill-color:red;width:3;
  icon-image: url('http://www.sailcom.ch/images/grafik/Yacht.png');
  icon-width: 18; 
  }
}}
print/

**Comment by tyrasd** [comment]
Thanks for the example, I'll check what's going wrong there.

**Comment by k1wiosm** [comment]
Any updates here?

**Comment by nounours77** [comment]
Unfortunately, the example is still not working. I do not know if tyrasd has made some changes or not, of if the problems I find are just on my side ...
Did you try something similar, and did it work? Maybe it would help to share your example with us?
nounours

**Comment by DaveF63** [comment]
Small features  & MapCSS would be great to fully incorporate, especially text labels.

**Comment by tyrasd** [comment]
this should finally work now

**Comment by nounours77** [comment]
Martin,

I works for me!!! thanks a lot, that's great!!

nounours

**Comment by DaveF63** [comment]
What's it can do at the moment is good. Thanks. However it doesn't recognise global setting 'Don't display small features as POIs', #173 which is a shame. .
