### ISSUE TITLE
query designed by overpass turbo is not outputing valid osm file in `[out:xml]` mode

### ISSUE THREAD

**Issue by matkoniecz** [tyrasd/overpass-turbo#230]
See https://github.com/drolbr/Overpass-API/issues/265

http://overpass-api.de/output_formats.html has 

> The XML data itself, i.e. the tags node, way and relation are returned exactly as from the main server.

linking to http://wiki.openstreetmap.org/wiki/OSM_XML which includes

> a block of nodes containing especially the location in the WGS84 reference system (...) a block of ways

and

> If you develop tools using this format, you can be certain that:

>    blocks come in this order

```
[out:xml][timeout:25];
(
  way["building"](37.95536,126.67604,37.95672,126.67774);
);
out body;
>;
out skel qt;
```

running on http://overpass-api.de/query_form.html returns https://gist.github.com/matkoniecz/f1f8d9b4d31cca7d383f8e36b8da0a65 that has block of ways before block of nodes. It breaks for example import to https://github.com/OpenOrienteering/mapper

It is possible to write this query to ensure valid .osm file https://github.com/drolbr/Overpass-API/issues/265#issuecomment-207817659 (though maybe also relation need a special handling).

I think that it is overpass bug, but workaround may be made also on Overpass-turbo side.

**Comment by tyrasd** [comment]
With *query designed by* you mean the query wizard, right? The wizard produces a json-output query by default, so I don't see why it needs to fulfill the specifications for the osm xml format. If you need the xml output in a specific element order, please use the mentioned workaround or use the query *"repair"* functionality provided by overpass turbo when using the *export to JOSM/Level0* tool.
