### ISSUE TITLE
Convert Overpass request to OsmFilter parameter file

### ISSUE THREAD

**Issue by homersimpsons** [tyrasd/overpass-turbo#233]
Hello, thank you for overpass :)
There is an option that I would love:
convert overpass request to OsmFilter request, to be apleb to copy/paste this in a parameter file and then use it on a specific map, or a huge map.
It could be, on overpass-turbo in menu export>request>OsmFilter parameter file

Thank you

(from https://github.com/drolbr/Overpass-API/issues/266)

**Comment by tyrasd** [comment]
After looking at the [documentation](http://wiki.openstreetmap.org/wiki/Osmfilter) of the filtering capabilities in OsmFilter (but without having much experience with it), I think that it's in general impossible to convert an overpass request to a set of OsmFilter parameters. Please correct me if I'm wrong.

If you have/know of some code that does the conversion, I can try to integrate it of course.

**Comment by homersimpsons** [comment]
This was an idea because overpass requests are easier than Osmfilter ones. And this would be better for the server.

**Comment by tyrasd** [comment]
yeah. But on the other hand, if someone knows how to install and use OsmFilter, it shouldn't be a huge problem to manually adapt/convert an overpass query for it.
