### ISSUE TITLE
way(r)[!=v] takes forever whereas way(r)[k!=v] is very quick

### ISSUE THREAD

**Issue by naomap** [tyrasd/overpass-turbo#237]
Hi. I'm preparing an Overpass workshop for SOTM FR. I came across a performance issue which I don't understand. The following request is pretty quick :

rel(165712);
way(r)["railway"!="platform"];
out; >; out;

However if you turn ["railway"!="platform"] into ["railway"="platform"]  (remove the negation) it takes forever ! 

Do you have any idea why that is the case ?

Regards,
Antoine.

**Comment by mmd-osm** [comment]
overpass turbo is only a web frontend. You should report Overpass API related questions here: https://github.com/drolbr/Overpass-API/issues

**Comment by naomap** [comment]
Of course ! Sorry about that. 
I've reported it on Overpass API.
Now closing the issue.
Thanks, Antoine.
