### ISSUE TITLE
Errors when using the "changed" filter - only on RU and FR servers

### ISSUE THREAD

**Issue by zstadler** [tyrasd/overpass-turbo#238]
The errors are produced when using the "changed" filter the servers:
1. http://overpass.osm.rambler.ru/cgi/
2. http://api.openstreetmap.fr/oapi/

Error message when running the http://overpass-turbo.eu/s/g2x query on the RU server:
`runtime error: open64: 2 No such file or directory /spool/roland/v0.7.52/db/relation_changelog.bin File_Blocks::File_Blocks::1`

Changing the query to look for ways produces a similar error message:
`runtime error: open64: 2 No such file or directory /spool/roland/v0.7.52/db/way_changelog.bin File_Blocks::File_Blocks::1`

Changing the query to look for nodes on the FR server produces a similar error message:
`runtime error: open64: 2 No such file or directory /ssd/api.openstreetmap.fr/db/node_changelog.bin File_Blocks::File_Blocks::1`

**Comment by mmd-osm** [comment]
* rambler.ru: that's a known issue: http://wiki.openstreetmap.org/wiki/Overpass_API/status
*  `(changed)` on French instance: the French instance does not support *attic* data, i.e. `(changed)` is not supported on that instance. You can find this documented in the wiki: http://wiki.openstreetmap.org/wiki/Overpass_API#Introduction

BTW; overpass turbo is not the right repository for server issues, as it is only a web frontend for Overpass API.

**Comment by zstadler** [comment]
Thanks for the info.

This specific issue was first seen 2016-05-04 and is unrelated to the 2016-05-17 issue with Rambler.
Added a report to http://wiki.openstreetmap.org/wiki/Overpass_API/status.
