### ISSUE TITLE
Custom shortcut definitions cannot be commented-out

### ISSUE THREAD

**Issue by zstadler** [tyrasd/overpass-turbo#240]
Apparently, the definition of custom shortcuts cannot be commented-out.

 For example, because the shortcut definition is commented-out, I would expect to see the same count twice:
```
[bbox:32.6, 35.1, 32.61, 35.11];

/*
//{{foo=(changed:"2020-05-01T00:00:00Z")}}
*/

rel
  {{foo}}
  ;
out count;

rel
  ;
out count;
```
But the first count is zero because the `changed` filter is active and it is set for 2020:
```
  <count total="0" nodes="0" ways="0" relations="0"/>
  <count total="6" nodes="0" ways="0" relations="6"/>
```

By the way, as a temporary workaround, a custom shortcut definition can be disabled by inserting the comment into its definition part:
```
{{foo=
  //(changed:"2020-05-01T00:00:00Z")
  }}
```

**Comment by tyrasd** [comment]
In principle this is intended behaviour, because the `{{}}` parsing intentionally doesn't know much about the Overpass QL syntax. (Note that the `{{}}` is expanded in the browser before sending it to the Overpass API and the query is really only parsed there.)

Another workaround solution would be to comment it out like this:

    {{//foo=(changed:"2020-05-01T00:00:00Z")}}

**Comment by zstadler** [comment]
Thank you for the clarification.

Perhaps the online help for Overpass Turbo, under the "Overpass Queries" section, and the [Extended Overpass Queries](http://wiki.openstreetmap.org/wiki/Overpass_turbo/Extended_Overpass_Queries) wiki page can explain that the handy shortcuts are, as you said, specific to the overpass turbo interface and take precedence over the Overpass QL syntax.

I find that the current wording does not make a clear distinctions , and me lead to some misunderstanding, as I have. 

You may also want to consider updating the  title of the wiki page to "Extended Overpass **_Turbo_** Queries" rather than "Extended Overpass Queries"

**Comment by tyrasd** [comment]
good ideas!
