### ISSUE TITLE
Ajax error when running queries on Mexico and USA

### ISSUE THREAD

**Issue by abautis** [tyrasd/overpass-turbo#246]
An error occured during the execution of the overpass query!

Request rejected. (e.g. server not found, request blocked by browser addon, request redirected, internal server errors, etc.)

Error while parsing the data (parsererror).

[out:json][timeout:250]{{data:overpass,server=http://dev.overpass-api.de/api_mmd/}};
// fetch area “Mexico” to search in
{{geocodeArea:Mexico}}->.searchArea;
// gather results
(
// query part for: “Highway”
way"highway";
);
// print results
out body;

;
out skel qt;

Can anyone help me with this? I am trying to get highway information for Mexico and USA in the Overpass Schema

**Comment by mmd-osm** [comment]
Duplicate post: https://github.com/drolbr/Overpass-API/issues/284
