### ISSUE TITLE
Search by exact coordinates

### ISSUE THREAD

**Issue by oilbob** [tyrasd/overpass-turbo#252]
I would like to search for nodes by their exact coordinates. I am sure, that these coordinates match a node. Tries with a bounding box using the same values for north and south as well as east and west did not return a result. Help is appreciated.

**Comment by mmd-osm** [comment]
See [`around` filter](http://wiki.openstreetmap.org/wiki/Overpass_API/Overpass_QL#Relative_to_other_elements_.28around.29).

**Comment by oilbob** [comment]
Thank you! I was looking for a way to keep the computational power low (which I guess is higher when searching in an area around a point). If that is the common way to do it, I can do it like this.

**Comment by mmd-osm** [comment]
If you have the exact coordinates, you can also provide a radius of `0` meters.

**Comment by oilbob** [comment]
Right, I'm using a radius of 1 m now. It does not work with 0 m, which would nice
