### ISSUE TITLE
Strange title and no info in way pop-up

### ISSUE THREAD

**Issue by zstadler** [tyrasd/overpass-turbo#256]
- The info pop-up has a strange title and no tag information for requested way 
  <img width="188" alt="2016-07-15 17_41_07-overpass turbo" src="https://cloud.githubusercontent.com/assets/1304610/16877994/66b71bd6-4ab3-11e6-9416-f4312dc65239.png">
  
  when running [the query](http://overpass-turbo.eu/s/hk6) :
  
  ```
  (
  way(64734796);
  relation(bw);
  );
  out geom;
  ```
- The standard title and tag information is shown
  <img width="122" alt="2016-07-15 17_53_30-overpass turbo" src="https://cloud.githubusercontent.com/assets/1304610/16878408/1528fa4e-4ab5-11e6-9272-368e93cd6ca4.png">
  when replacing `out geom;` with `( ._;>;); out;` :
  
  ```
  (
  way(64734796);
  relation(bw);
  );
  ( ._;>;);
  out;
  ```
- Things also look good
  <img width="122" alt="2016-07-15 17_43_49-overpass turbo" src="https://cloud.githubusercontent.com/assets/1304610/16878062/bc1e85b4-4ab3-11e6-83de-109b88f1b96d.png">
  when running without the `relation(bw);` term:
  
  ```
  (
  way(64734796);
  );
  out geom;
  ```

**Comment by mmd-osm** [comment]
I think this was introduced with a fix to handle ref-less and ref-full ways in https://github.com/tyrasd/osmtogeojson/commit/52fff233171e473e9ca70fd7bf8514aef9982e1c and probably belongs to the osmtogeojson library instead: https://github.com/tyrasd/osmtogeojson/issues

Concerning the first query example above, the response includes way 64734796 as part of relation 6410854 without any node ids, and again as a single way with node ids.

**Comment by zstadler** [comment]
I would appreciate if someone could further investigate and fix this issue.

I find that using `out geom` significantly reduces the complexity of Overpass queries. 
I hope it also reduces the server-side computation. However, bugs like this discourage the use of `out geom`.

**Comment by zstadler** [comment]
This issue seems to be resolved.
When using the [original query with the data of that time](https://overpass-turbo.eu/s/1I5z)

```
[date: "2016-07-15T00:00:00z"];
(
  way(64734796);
  relation(bw);
);
out geom;
```
the result is as expected:
![image](https://github.com/tyrasd/overpass-turbo/assets/1304610/21165cba-2021-405d-a725-3e4b48b90f18)
