### ISSUE TITLE
Use MapQuest instead of Mapnik tiles?

### ISSUE THREAD

**Issue by Shohreh** [tyrasd/overpass-turbo#26]
Hello

I'm an OSM newbie and someone mentionned http://overpass-turbo.eu as a simple way to query the OSM database and display some specific infos.

It works great, but I find the Mapnik layer hard to read: Is it possible to tell Overpass-Turbo to use MapQuest instead?

I saw the Settings > Map > Tile-Server setting, but don't know if this can be used to pass that parameter.

Thank you.

**Comment by govvin** [comment]
It it possible to set the tile layer using OverpassQL?

From this slide, it was mentioned that the following is a way of doing it, but couldn't get it to work:
`canvas {
  background-map: url('http://{s}.tile.openstreetmap.fr/hot/{z}/{x}/{y}.png');
}`
