### ISSUE TITLE
Some server side problems while executing queries

### ISSUE THREAD

**Issue by naoliv** [tyrasd/overpass-turbo#260]
Lately I am seeing some problems while trying to run some queries, and they all look like a problem at the server side.

- [ ] Using the default server `//overpass-api.de/api/`
```
An error occured during the execution of the overpass query! This is what overpass API returned:

runtime error: Query run out of memory using about 2048 MB of RAM.
```

- [ ] Using `http://overpass.osm.rambler.ru/cgi/` or `http://api.openstreetmap.fr/oapi/`

```
An error occured during the execution of the overpass query!

Request rejected. (e.g. server not found, request blocked by browser addon, request redirected, internal server errors, etc.)

Error-Code: [Exception... "" nsresult: "0x805e0006 ()" location: "JS frame :: https://overpass-turbo.eu/turbo.min.js?2016-06-06 :: .send :: line 4" data: no] (0)
```

One example query where I see this:

```
[out:json][timeout:900];
{{geocodeArea:são paulo}}->.searchArea;
(
  way["highway"](user:"Gabriel Vilela")(newer:"{{date:3 weeks}}")(area.searchArea);
);
out body;
>;
out skel qt;
```

**Comment by mmd-osm** [comment]
Query 1: Your issue belongs to a different repository, Overpass API server is [here](https://github.com/drolbr/Overpass-API).

Query 2: Looks like a NoScript issue in your browser. Did you allow those alterantive servers?

**Comment by naoliv** [comment]
Thanks for 1.
And for 2, I don't have NoScript installed. What else could be causing this, please?

**Comment by mmd-osm** [comment]
Sorry, I can't reproduce your issue on the French instance. Here's the result I got:

![12-08-2016 15-02-40](https://cloud.githubusercontent.com/assets/5842757/17622969/e78b682a-609d-11e6-8dd5-69eff37deeb0.png)

**Comment by petaire92** [comment]
I do have the same issue for 2 days now, and I tried everything : I've tested it on 2 different computers, multiple browsers, including tests with privacy mode, even on another connection, but I get stuck with this : 
![image](https://cloud.githubusercontent.com/assets/17812507/17836372/3db31f38-6790-11e6-905c-b854d54a008d.png)
And this morning, I tried with isup.me and I got this : 
![image](https://cloud.githubusercontent.com/assets/17812507/17836377/5de3cf78-6790-11e6-8602-013fc1f810db.png)

**Comment by mmd-osm** [comment]
@petaire92 : you could use http://tyrasd.github.io/overpass-turbo/ for the time being and then switch to the French server underneath Settings.

@tyrasd : do you happen to know, which overpass-turbo.eu is also down today?

**Comment by tyrasd** [comment]
> do you happen to know, why overpass-turbo.eu is also down today?

Yes, there's a ongoing DOS-type attack on the data center of my web hoster:
https://twitter.com/ubernauten/status/767267625181339649.

**Comment by tyrasd** [comment]
More details about the recent Overpass API outage can be found in the osm wiki: http://wiki.openstreetmap.org/wiki/Overpass_API/status

It's quite a coincidence that overpass-turbo has also had issues around the same time as the Overpass API did. :confused: 

Anyway, both services should by now be more or less back to normal operation.
