### ISSUE TITLE
'large amounts of data' query warning

### ISSUE THREAD

**Issue by DaveF63** [tyrasd/overpass-turbo#263]
Hi
Feature request
This could well have been discussed before but once again unsure what to search for.

Could the value (currently 2mb I think) that triggers the warning about the amount of data being download be increased, preferably including it as a user defined setting.
With many now having fast internet connections & server speeds increasing the current limit appears antiquatedly low. 
Obviously there will need to be an upper limit so as to not clog the server.

**Comment by tyrasd** [comment]
see #248
