### ISSUE TITLE
Oversimplification in exporter

### ISSUE THREAD

**Issue by hillwithsmallfields** [tyrasd/overpass-turbo#266]
In http://overpass-turbo.eu/s/izA, which has the query text as follows:
 `   [out:json];
    way(37143281);
    (node [~".+"~".+"](around:25); 
     <;
    ); 
    out body qt;
`
the code produced by "export > query > as QL" produces an error when used, as it has simplified `node [~".+"~".+"]`  to `node [~".+"]` which is not accepted.

**Comment by tyrasd** [comment]
That export option actually hits the overpass api "convert query" feature, which apparently doesn't know about key-regex filters yet. Can you please [open a ticket](https://github.com/drolbr/Overpass-API/issues/new) on the Overpass API repository for this?

**Comment by tyrasd** [comment]
btw: why do you want to export a query to QL if it is already in QL format? Does *export as text* not work for you?
