### ISSUE TITLE
Impossible to use on an iPad

### ISSUE THREAD

**Issue by k1wiosm** [tyrasd/overpass-turbo#267]
Overpass turbo website does not work on an iPad using Safari. The keyboard never shows up which makes it impossible to write anything.

Executing the default drinking water in Rome example works perfectly.

iPad mini 2 iOS 9.3.5

**Comment by tyrasd** [comment]
Did you try to deactivate the `rich code editor` in the settings?

**Comment by k1wiosm** [comment]
I did not try that. Thank you for your help. That fixed it.

**Comment by bjohas** [comment]
I can also confirm that disabling the rich text editor fixes it. Many thanks!
