### ISSUE TITLE
"Your browser is not supported"

### ISSUE THREAD

**Issue by DaveF63** [tyrasd/overpass-turbo#270]
I'm running Firefox 49.0.1, cookies enabled, no settings knowingly changed. In the last week I've started getting this message displayed on startup:

![overpass turbo browser not supported](https://cloud.githubusercontent.com/assets/9528328/19475902/55a13c12-952e-11e6-9169-764e7c96fded.JPG)

If I dismiss it, it works as expected.
Any ideas? Is it just me?

**Comment by tyrasd** [comment]
That's strange. I'm on firefox 49.0 and don't get the message.

The code that checks browser compatibility is [here](https://github.com/tyrasd/overpass-turbo/blob/master/js/ide.js#L96-L99) and basically only checks for [CORS](https://de.wikipedia.org/wiki/Cross-Origin_Resource_Sharing) and whether it can store something into the browser's local storage. Can you try if modifications in your overpass-turbo settings are preserved after a page reload? Also, do you see any error messages in the javascript console when the message appears?

**Comment by DaveF63** [comment]
My settings are preserved & I don't see any errors in my  javascript console. 
It occurs much less frequently but still pops up every once in a while.

**Comment by tyrasd** [comment]
OK, that's going to be hard to debug, unfortunately. But I still don't see anything that could possibly be causing this on overpass turbo's side. I would guess that it has more likely something to do with a bug/misconfiguration/etc. on your browser setup (idk, maybe you're hitting some local storage usage limit, or some browser plugin is interfering with jQuery's browser feature detection).

Let's close the ticket until we have more info on when/why/how this can occur.

**Comment by DaveF63** [comment]
It's returned with a vengeance this morning. Does this help?:
![capture](https://cloud.githubusercontent.com/assets/9528328/20270373/b3837204-aa7e-11e6-8c84-1861c3942b93.JPG)

**Comment by tyrasd** [comment]
ooh, yeah. That means your browser's local storage database is corrupted. Though, it's quite strange that the issue was kind of intermittent for you. There's not much you can do, except deleting the corrupt file (see http://askubuntu.com/questions/110649/how-can-i-stop-firefox-throwing-a-ns-error-file-corrupted-error), but you'll lose any saved data by doing that (affecting all websites using the local storage, not only overpass turbo).
