### ISSUE TITLE
Fun with overpass ql statement "make"

### ISSUE THREAD

**Issue by mmd-osm** [tyrasd/overpass-turbo#285]
`make` turns out to be a nice gift for pranksters, as it allows to produce almost arbitrary XML elements. This has some unintended side effects: http://overpass-turbo.eu/s/nEq 
Maybe the check for `<remark>` could be made a bit stricter in the code.

btw: I somehow feel a bit stupid to report this, oh well. :sheep:

**Comment by tyrasd** [comment]
oohhh :open_mouth: 

My first relation is that the Overpass API should not allow to override the `remark` tag (and other reserved *keywords*, e.g. `meta`). //cc @drolbr

PS: The issue is not present in the *json* output format.
