### ISSUE TITLE
Integrate street-level pictures

### ISSUE THREAD

**Issue by PanierAvide** [tyrasd/overpass-turbo#287]
I would like to know if overpass-turbo might support showing street-level pictures (for example using [Pic4Carto.js](https://framagit.org/PanierAvide/Pic4Carto.js)) available around OSM features. Let me explain with an use case:
- Querying all bicycle parking in a city without `bicycle_parking=*` tag defined
- Click on one of them, popup appears, and a button "Pictures around"
- Click on this link, a dialog containing a picture gallery shows all pictures (or recent ones) around this feature (for example in a 15 meters radius)

It would be useful to know fast if a picture of the feature is available. If so, we can use the picture to add details about the feature (for bicycle parking, it would be its type, capacity, if covered...).
If it seems interesting to you, I can work on a pull request to make this feature available.

**Comment by tyrasd** [comment]
Currently, I'd consider this out of scope of overpass turbo. This use case is quite specific and one could surely build a whole dedicated osm-quality-improvement tool around this idea.

Maybe once overpass turbo has some kind of plugin infrastructure, this could be implemented as such.
