### ISSUE TITLE
Export for Wiki

### ISSUE THREAD

**Issue by mmd-osm** [tyrasd/overpass-turbo#288]
The other day, I added a wiki template to the OSM wiki to automatically render Overpass QL source code in a `<div>` section along with the well known steering wheel icon pointing to overpass turbo. Once you click on the icon, the exact same source code is opened up in overpass turbo ([Example](https://wiki.openstreetmap.org/wiki/Overpass_API/Overpass_API_by_Example#Highway_around_schools_with_inappropriate_maxspeed_.28since_0.7.54.29)).  So, there's no more fiddling with shortlinks in the wiki and trying to keep everything in sync - the Overpass query in the wiki is the single source of truth now. :sunglasses: 

To motivate people to add more examples to the wiki, I thought about some new "Export to Wiki" feature in overpass turbo. Manually adding examples is of course also possible. However, it involves some insane escaping, which easily gets into the way of adding something useful to the wiki:

Conversion wise, I could identify at least the following two issues, which would have to be covered by an Overpass QL -> Wiki text conversion:

* overpass turbo extensions need escaping: `{{bbox}}` turns into `{{((}}bbox{{))}}`
* `|` needs to be escaped as `{{!}}`, basically everywhere, in particular in regular expressions.

Example output for "Export for Wiki":

```
{{OverpassTurboExample|query=
[out:json][timeout:800];
// Get all schools in current bounding box
( way[amenity=school]({{((}}bbox{{))}});
  node[amenity=school]({{((}}bbox{{))}});
  rel[amenity=school]({{((}}bbox{{))}});
)->.schools;
// find highway=* around schools with radius 50m, ignoring
// footway and paths. In addition, highways are relevant if they 
way(around.schools:50)[highway][highway!~"^(footway{{!}}path)$"]
   (if: (is_number(t[maxspeed]) && t[maxspeed] > 30) {{!}}{{!}} 
        !is_tag(maxspeed) )->.streets;
}}
```

**Comment by bjohas** [comment]
Hi @mmd-osm, this is a really great idea! I've played around with this a bit here https://wiki.openstreetmap.org/wiki/User:Bjohas/OTE - I think it would be better to resolve this within the wiki, so that users on the wiki can just enter the overpass query directly. A simple solution without syntax highlighting is possible using <pre> (see wikipage), but the syntax highlighting seems to throw a known issue. Do you want to discuss it on the wiki for a bit?

**Comment by mmd-osm** [comment]
I tried this with <pre> and <nowiki> but unfortunately, this didn't quite work out. We need both syntax highlighting, as well as being able to pass the query 1:1 to overpass turbo. If you try some alternatives, I would suggest to create your own template to play with and post the results here.

**Comment by bjohas** [comment]
Yeah, I've tried a few things. I agree it's currently impossible, but perhaps that's due to the issue mentioned on the page https://phabricator.wikimedia.org/T28213. Have you tried emailing somebody on a wikipedia mailing list? If not I can do that.

**Comment by bjohas** [comment]
I've posted something here https://www.mediawiki.org/wiki/Topic:Tpz21dqvqgkokhfl and here https://www.mediawiki.org/wiki/Help_talk:Magic_words#urlencode:.3Csyntaxhighlight.3E....3C.2Fsyntaxhighlight.3E

**Comment by mmd-osm** [comment]
> Have you tried emailing somebody on a wikipedia mailing list? If not I can do that.

No, I'm not really into wiki stuff and was just happy to get this working somehow. If you like you can take it up to a wikipedia mailing list as a follow up.

**Comment by bjohas** [comment]
OK, I'll see what I can work out. However, I've looked into it some more, and the escaping approach may well be the only one.

The list of "escape templates" is here https://wiki.openstreetmap.org/wiki/Category:Templates_for_Escaping. I think {{ could be best escaped to {{((}}, and }} to {{))}}. Clearly {{!}}  is needed for | and I'd recommend {{!!}}  for ||.  Also ; and = can be escaped with {{;}} and {{=}}, though it seems to work ok without it, so in the interest of keeping the text vaguely legible, it may be best to leave those.

**Comment by bjohas** [comment]
I wrote a perl script here to do the escaping https://github.com/bjohas/mediawikiencode

**Comment by mmd-osm** [comment]
Thanks. For the sake using this inside overpass turbo, I'd be more inclined towards a Javascript solution.
Multiple replacements is really easy to do, solution should have ~ 10 lines, like shown here: http://stackoverflow.com/a/15604206/3501889

**Comment by tyrasd** [comment]
> I wrote a perl script here to do the escaping https://github.com/bjohas/mediawikiencode, which I'll use in the meantime. Would be great to have this feature in overpass turbo!

Thanks guys for investigating the implementation details here. I'll implement this directly in turbo.

**Comment by bjohas** [comment]
@mmd-osm Ah yes, this was an ordering issue in the hashes. Fixed now. I've also added a optional printing of the medawiki template - after all, the code is for pasting into the wiki, so most likely you want the template code as well.

@tyrasd Great!

**Comment by tyrasd** [comment]
This is now available as *export -> query -> as text (osm wiki)*. You can already try it here: http://overpass-turbo.eu/master/

**Comment by bjohas** [comment]
This is great, many thanks! 

Two comments:

1. Would it be possible to add a "copy to clipboard" (in addition to the file download)? Given that most people will want to copy and paste to the OSM wiki, this would be helpful.

2. Could the export also include the location/zoom? The template can take a loc parameter:

 {{OverpassTurboExample|loc=47.0618984;15.4370248;17|query=
 }}

which maps to overpass/?C=47.0618984;15.4370248;17. If that's not wanted by the user, they can just remove it - which is easier than looking it up.

Many thanks!

**Comment by tyrasd** [comment]
Those are both very good suggestions. Can you please open two new tickets here, so they don't get lost?

**Comment by bjohas** [comment]
Following some queries that didn't work, I would recommend that = also be escaped as {{=}}. That fixed the issue for me.

**Comment by mmd-osm** [comment]
Hmm. never came across any issues with `=` so far. Do you have some example queries to demonstrate this?

**Comment by bjohas** [comment]
I just had another look, but can't find it, sorry. I'll send it if I come across the issue again.
