### ISSUE TITLE
"Export > Query > as text" should also offer original query

### ISSUE THREAD

**Issue by bjohas** [tyrasd/overpass-turbo#292]
I suggest that "Export > Query > as text" should also offer to export the original (unchanged) query text (including MapCSS), i.e. to add a 4th option to the "Export > Query" menu, as follows:

Export > Query
- as text (stand-alone, no CSS)
- as text (unchanged, for use in IDE)
- convert to ...
- convert to ...

**Comment by tyrasd** [comment]
Can't you just copy-paste the original unaltered query directly from the code editor?

**Comment by bjohas** [comment]
Yes, sure, that's possible. It's just that I sometimes keep a record of my queries while I'm experimenting. So it's then quite easy to keep downloading versions. (I can of course also copy-paste into a file locally, but it's easier to just hit a download button.)

Also, I hadn't actually realise that the Export>Query>text doesn't do the MapCSS. So the other day I adjusted the MapCSS on a bunch of queries, only to discover that all the saved query.txt files didn't have the MapCSS. So it would be good to have the two options (or at least indicate that the exported version will have substitutions and no CSS).

Thanks!

**Comment by tyrasd** [comment]
OK, I think it makes sense to have both options in the export menu for clarity. I'll consider it.

**Comment by bjohas** [comment]
Excellent, many thanks!
