### ISSUE TITLE
Consistently visualising relations

### ISSUE THREAD

**Issue by bjohas** [tyrasd/overpass-turbo#293]
I'm not sure this is a bug or whether it just needs documentation. The issue is that it's not clear to me when relation popups are available and when they are not. I suspect it may be to do with whether ways fully overlap with the relation? It would be good if there was a consistent way of creating clickable icons for the relationship.

Example here:
https://wiki.openstreetmap.org/wiki/Talk:Overpass_turbo#Visualise_tags_attached_to_relation

**Comment by bjohas** [comment]
Right, funny how you find the solutions moments after filing a request. I guess "out center" would be the solution to this?

However, the above example is still not clear to me, and a tip would be appreciated!

**Comment by mmd-osm** [comment]
>  I would be good to have more documentation on it here https://wiki.openstreetmap.org/wiki/Overpass_API/Language_Guide#Geometry_attributes.

Did you maybe not notice the big warning on the top of that page? "This wiki page doesn't cover some of the more recent Overpass API features. For a comprehensive list of features, please refer to the Overpass QL wiki page.". Feel free to enhance it. Thanks.

**Comment by bjohas** [comment]
Suite, thanks. I've not seen out geom described. What does it do?

The original comment was about visualising relations. Do you have a view on this? It seems that sometimes relations are hidden by other elements. Might be worth an enhancement of some kind?

**Comment by mmd-osm** [comment]
>  I've not seen out geom described. What does it do?

Quoting from: https://wiki.openstreetmap.org/wiki/Overpass_API/Overpass_QL#Print_.28out.29:

> geom: Add the full geometry to each object. This adds coordinates to each node, to each node member of a way or relation, and it adds a sequence of "nd" members with coordinates to all relations.

**Comment by bjohas** [comment]
Ah ok, thanks! I'd been searching the pages for "out geom" and so didn't see this. I've added notes to the wiki now.

Do you have a view on why the two examples provided here https://wiki.openstreetmap.org/wiki/Talk:Overpass_turbo#Visualise_tags_attached_to_relation   provide different results?

**Comment by mmd-osm** [comment]
> Do you have a view on why the two examples provided here https://wiki.openstreetmap.org/wiki/Talk:Overpass_turbo#Visualise_tags_attached_to_relation provide different results?

Sorry, really no idea what you mean by that. What is a "clickable relation" to start with? Screenshots would be good. I suspect that you see the relation in one case being rendered as polygon and in the other case as linestring?

**Comment by tyrasd** [comment]
> Do you have a view on why the two examples provided here https://wiki.openstreetmap.org/wiki/Talk:Overpass_turbo#Visualise_tags_attached_to_relation provide different results?

This is basically by design. [osmtogeojson](https://github.com/tyrasd/osmtogeojson/) handles the conversion of the data returned by overpass to GeoJSON, and it currently only supports multipolygon relations (and soon route relations, see https://github.com/tyrasd/osmtogeojson/issues/1), but not (yet) the site relations from your second example. If it doesn't know anything about a certain relation type, it falls back to render the relation's members individually and adds the relation membership as a property to the respective features. 

`out bb / center` is different, since then the relation members are not actually part of the result anymore and therefore osmtogeojson can only create a geometry for the whole relation.

**Comment by bjohas** [comment]
Thanks for the answer - that's really helpful! I'll copy the answer to the wiki.
