### ISSUE TITLE
GeoJSON features must have a type=feature member

### ISSUE THREAD

**Issue by RafalR** [tyrasd/overpass-turbo#295]
Overpass turbo return invalid GeoJSON. I suspect this is missing:

https://github.com/tyrasd/overpass-turbo/blob/master/js/ide.js#L1218
```javascript
return {
  type: "Feature",
  properties: feature.properties,
  geometry: feature.geometry
}
```

**Comment by tyrasd** [comment]
You're right. Thanks for noticing. Should be fixed now.
