### ISSUE TITLE
Export for Wiki: Copy to clipboard

### ISSUE THREAD

**Issue by bjohas** [tyrasd/overpass-turbo#297]
Enhancement of https://github.com/tyrasd/overpass-turbo/issues/288#issuecomment-299448523

I suggest to a "copy to clipboard" (in addition to the file download). Given that most people will want to copy and paste to the OSM wiki, this would be helpful.

**Comment by tyrasd** [comment]
this maybe also worth to add to a few other export options (e.g. raw/expanded query, bounding box, etc.)

**Comment by tyrasd** [comment]
this library might come in handy implementing this: https://github.com/sindresorhus/copy-text-to-clipboard
