### ISSUE TITLE
geocodeArea - "Nominatim Error close Could not find anything with the following name", when invoking with "?R&Q="

### ISSUE THREAD

**Issue by bjohas** [tyrasd/overpass-turbo#299]
When I click on one of he links o overpass here https://wiki.openstreetmap.org/wiki/London_public_transport_tagging_scheme/Map_Challenges which invokes overpass as

http://overpass-turbo.eu/?Q=%5Bout%3Ajson%5D%5Btimeout%3A25%5D%3B+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++%0A%7B%7Brse%3D%5B%22railway%22%3D%22subway_entrance%22%5D%7D%7D%0A%7B%7BgeocodeArea%3A%22London%22%7D%7D-%3E.a%3B%0A%7B%7Bmyarea%3D%28area.a%29%7D%7D%0A%28%0A++node%7B%7Brse%7D%7D%7B%7Bmyarea%7D%7D%3B%0A%29%3B%0A%28node._%28changed%3A%22%7B%7Bdate%3A7+days%7D%7D%22%29%29%3B%0Aout+meta+qt%3B&R

I got "Nominatim Error close Could not find anything with the following name" or similar error message. When I then ran the query, it ran fine. When I tried to repeat this, it worked ok, apart from the "missing translations" message (https://github.com/tyrasd/overpass-turbo/issues/296). Perhaps it's a similar issue, where it cannot find something related to the geocoder on startup with "?R&Q=" ?

**Comment by tyrasd** [comment]
This I cannot reproduce. Do you still see it? If not, it was probably just a temporary hiccup with Nominatim… Otherwise: Which browser are you using?

**Comment by bjohas** [comment]
Thanks for looking into it. No it hasn't appeared again!
