### ISSUE TITLE
Export as png doesn't work

### ISSUE THREAD

**Issue by bjohas** [tyrasd/overpass-turbo#300]
In the currently deployed http://overpass-turbo.eu/ and http://overpass-turbo.eu/turbo/build/master/ "Export > Map > png" doesn't work. "Exporting as image" appears, but the "Export - Image" window does not appear, and the file is not saved.

**Comment by bjohas** [comment]
I just tried this. "exporting as image" appears, but process stuck on "rendering map data".  "Export - Image" window does not appear, and the file is not saved. Maybe it's a regression?

**Comment by tyrasd** [comment]
I think you're right. The console shows the following error:

```
turbo.20f776b….js:29 Uncaught (in promise) TypeError: e.drawSvg is not a function
```

which should correspond to the following line in the code: https://github.com/tyrasd/overpass-turbo/blob/master/js/ide.js#L2172
