### ISSUE TITLE
Mapcss eval no longer working

### ISSUE THREAD

**Issue by mmd-osm** [tyrasd/overpass-turbo#301]
Please see https://github.com/tyrasd/overpass-turbo/pull/283#issuecomment-299927864 for details

**Comment by tyrasd** [comment]
Thanks for the report. I can confirm the issue, but here I see a slightly different error message:

> Error while evaluating mapcss evals TypeError: Cannot set property 'tag' of undefined

**Comment by mmd-osm** [comment]
Cool. Thanks a lot for the quick fix. Looking good so far!
