### ISSUE TITLE
Evaluate {{mybox=({{bbox}})}}

### ISSUE THREAD

**Issue by bjohas** [tyrasd/overpass-turbo#306]
It's helpful to be able to specify {{bbox}} inside a variable, e.g. to set

{{something=(area.a)}}

to look at larger area or to set

{{something=({{bbox}})}}

to inspect just a smaller area. This is currently not possible. The suggestion is to implement it, either specifically for {{bbox}} only, or generally to allow recursive evaluation.

A work around might be to assign {{bbox}} to something "area({{bbox}}) -> .a", but I've not found a good way to do that.

**Comment by mmd-osm** [comment]
I would suggest to do put all conditions in your query, and comment out the one you don't want. 

```C
{{something_a=(area.a)}}
{{something_b=({{bbox}})}}

node {{something_a}} {{something_b}} ...
```

**Comment by bjohas** [comment]
For me, {{something_b=({{bbox}})}} doesn't work, presumably because the {{bbox}} doesn't get evaluated. Do you have an example?

**Comment by bjohas** [comment]
E.g. this doesn't work: http://overpass-turbo.eu/s/oXO.

**Comment by mmd-osm** [comment]
Why don't you use a global bounding box which you can comment/uncomment as needed:

```C
[out:json][timeout:25]
// [bbox:{{bbox}}]            // uncomment if needed
;

(
  node{{sel}};
);
out meta;
```

**Comment by bjohas** [comment]
Ah yes! Good idea, thanks!

**Comment by tyrasd** [comment]
Thanks @mmd-osm for the good workaround.

I'd like to keep the parameter-substitution functionality as simple as possible (easy parsing, avoiding to possibly have to do recursive substitutions, etc.) for now. Sry

**Comment by bjohas** [comment]
That's fine - @mmd-osm's suggestion solves my problem. 

Though how would you get the area determined by a bounding box, if that's possible?

**Comment by bjohas** [comment]
Hmmm, so maybe I'm misunderstanding the global bounding box.

This query produces all stops irrespective of bounding box:
`
[bbox:{{bbox}}]
[out:json][timeout:25];
{{sel=["network"~"London Underground"]["type"~"route"]["name"="Central"]}}
(
  relation{{sel}};
)->.a;
node(r.a:"stop");
out meta qt;
`
while this one only produces stops in the bounding box:
`[bbox:{{bbox}}]
[out:json][timeout:25];
{{sel=["network"~"London Underground"]["type"~"route"]["name"="Central"]}}
(
  relation{{sel}};
)->.a;
node(r.a:"stop")({{bbox}});
out meta qt;
`

I was expecting them both to be the same.

**Comment by mmd-osm** [comment]
This looks like a bug, you should file an issue for this on overpass API repository.

**Comment by tyrasd** [comment]
@bjohas: You should create code blocks in github comments by wrapping them in tripple backticks: ` ``` `. See https://guides.github.com/features/mastering-markdown/

**Comment by bjohas** [comment]
Many thanks both! Filed here https://github.com/drolbr/Overpass-API/issues/402
