### ISSUE TITLE
Query with "around" doesn't complete (or time out)

### ISSUE THREAD

**Issue by bjohas** [tyrasd/overpass-turbo#311]
This query (http://overpass-turbo.eu/s/oYP) strangely never completes or times out, but is stuck on "calling API interpreter".

```
// nodes around relation
[bbox:{{bbox}}]
[out:json][timeout:25];
{{sel=["network"~"London Underground"]["type"~"route"]["name"="Central"]}}
(
  relation{{sel}};
)->.a;
(
node(around.a:10);
way(around.a:10);
);
out meta qt;
>;
out skel qt;
```

**Comment by mmd-osm** [comment]
That's a known issue, which is addressed in https://github.com/drolbr/Overpass-API/pull/167

Also, the global bbox is not applied to ```node(around.a:10);` at the moment. I would suggest:

```C
// nodes around relation
[bbox:{{bbox}}]
[out:json][timeout:250];
{{sel=["network"~"London Underground"]["type"~"route"]["name"="Central"]}}
(
  relation{{sel}};
)->.a;
(
  node(around.a:10)({{bbox}});
  way(around.a:10)({{bbox}});
);
out meta qt;
>;
out skel qt;
```

**Comment by bjohas** [comment]
Thanks! Yes, I do want to filter - see full query here http://bjohas.de/wiki/Maps/Transport_for_London/Lines#Checking_for_platforms. I'm using this to detect nearby platforms, that are not in the route relation (but should be). I just simplified the query for posting the issue!
