### ISSUE TITLE
Assignment to set leaves data in default set.

### ISSUE THREAD

**Issue by bjohas** [tyrasd/overpass-turbo#312]
I don't understand why this query produces output. 

```
[out:json][timeout:25];
{{sel=["network"~"London Underground"]["type"~"route"]["name"="Central"]}}
(
  relation{{sel}};
)->.a;
>;
out meta qt;
```

http://overpass-turbo.eu/s/oYT

**Comment by mmd-osm** [comment]
It's pretty easy to understand actually.

```C
(
relation({{sel}});
)->.a;
```

actually means:
```C
(
relation({{sel}})->._;
)->.a;
```

So, the relation query inside the union stores its result in the default set `._`. That's exactly what you see in the output.

**Comment by tyrasd** [comment]
> BTW: not really a question for the overpass turbo bug tracker, though.

+1, please address such issues/questions on https://github.com/drolbr/Overpass-API/issues (but please also check if there's already a ticket covering the respective topic).

**Comment by bjohas** [comment]
@mmd-osm, @tyrasd - many thanks! Added here https://wiki.openstreetmap.org/wiki/Overpass_API/Overpass_QL#Sets for clarification!
