### ISSUE TITLE
Overpass turbo editor on chrome/safari on iOS/iPad 

### ISSUE THREAD

**Issue by bjohas** [tyrasd/overpass-turbo#313]
While overpass turbo editor seems to work reasonably well on chrome/android, it does not work in safari or chrome on iOS/iPad. On tapping the editor, the keyboard doesn't pop up. May well be an upstream issue.

**Comment by HolgerJeromin** [comment]
There is only one (safari aka webview) rendering engine allowed on iOS. 
So even if your app is named Chrome the main work is done by the same code as Safari's browser.

**Comment by bjohas** [comment]
@HolgerJeromin Many thanks for that insight! So something between the code editor and web view isn't quite working.

**Comment by tyrasd** [comment]
did you try the workaround described here: https://github.com/tyrasd/overpass-turbo/issues/267#issuecomment-250413929 ?

**Comment by bjohas** [comment]
No - I didn't, and sorry I missed the existing bug!

Duplicate of https://github.com/tyrasd/overpass-turbo/issues/267.
