### ISSUE TITLE
TypeError: n.nodes is undefined

### ISSUE THREAD

**Issue by mmd-osm** [tyrasd/overpass-turbo#316]
Roland provided the following optimized version of a query, which now triggers a javascript error "TypeError: n.nodes is undefined" (Firefox), or "turbo.f7561f5….js:29 Uncaught TypeError: Cannot read property 'filter' of undefined" (Chrome)

```C
rel[wikidata](52.9047608002297,8.026885986328125,53.38988075156031,9.84375);

way(r)[wikidata]->.all;

foreach -> .rel(
    
  way.all(r.rel)(if: t[wikidata] == rel.u(t[wikidata]))->.ways;
  
  rel.rel(if:ways.count(ways) > 0);
  out center;
  .ways out tags;
);
```

**Comment by tyrasd** [comment]
It's an upstream bug in osmtogeojson. Closing here.

**Comment by tyrasd** [comment]
> following optimized version of a query

Nice and usefull query btw! Unfortunately not very well readable, though. :sweat_smile:

**Comment by mmd-osm** [comment]
Great, thanks a lot for the quick fix, the Javascript error is gone now!

> Unfortunately it's not very well readable, though.

Yeah, we definitely need a 'Wizard reloaded'  for all the new stuff. :sunglasses:
