### ISSUE TITLE
Style: text: name; breaks query

### ISSUE THREAD

**Issue by bjohas** [tyrasd/overpass-turbo#317]
This query runs fine without the 'style' but never completes when the style is added:
```
[out:json][timeout:25];
(
  way(135762301);
  way(165751428);
);
out meta;
>;
out skel qt;
{{style:
  node, way, relation {
    text: name;
  }
}}
```
If the style is replaced e.g. by color:red; the query runs fine also. Must be to do with text:name;

Thanks!

**Comment by tyrasd** [comment]
Thanks for the report. It was indeed a left over thing to re-implement during the latest code restructurings. :see_no_evil: It's fixed in master now. Will do a bugfix release later today.

**Comment by bjohas** [comment]
Excellent - glad it's useful!
