### ISSUE TITLE
unexpected results with diff

### ISSUE THREAD

**Issue by govvin** [tyrasd/overpass-turbo#319]
I'm in a UTC +8 time zone and I'm trying to gather changes that happened between 29th May, 12:00 to 23:59 with this:
```
[diff: "2017-05-29T12:00:00+8","2017-05-29T11:59:59+8"]
```
I know that I've used it like this before, but now I am unable to get the results I expected. Has anything changed?

**Comment by tyrasd** [comment]
Can you provide the full query (or optimally a minimal version of it), and explain what result you would have expected? Note that the *diff outputs are not actually supported by overpass turbo. You should probably use specialized tools such as achavi to visualize such data.

**Comment by govvin** [comment]
Hi there. Here's the query: http://overpass-turbo.eu/s/pnG

I'm trying to gather the edits made by the selected mappers for the (local)) date 29th May, between 12:00 to 00:00.

I know the edits are present, but I couldn't retrieve them using that query.

**Comment by tyrasd** [comment]
Try converting your timestamps to UTC. It seems Overpass doesn't handle the timezone suffix properly (or at all). //cc @drolbr

PS: Would you be so kind and report the timezone issue over at the Overpass API's issue tracker: https://github.com/drolbr/Overpass-API/issues/ ? Thanks!
