### ISSUE TITLE
Saving a query with a bad name is allowed and breaks things

### ISSUE THREAD

**Issue by tbertels** [tyrasd/overpass-turbo#325]
After #224 got fixed, I migrated my saved queries to osm.org.
However, while doing so, I pasted the content of a query in the name field and saved it.
Result: queries saved on osm.org cannot be loaded anymore.

Possible causes:
* multiline name
* too long name
* special characters in name

Note that saving a query locally with a bad name prevents us to remove it, but other queries are still usable.

http://www.openstreetmap.org/api/0.6/user/preferences is still accessible and shows the saved preferences, so this doesn't seems to be an API bug.

**Comment by tyrasd** [comment]
would you mind posting the relevant output from your http://www.openstreetmap.org/api/0.6/user/preferences (the line starting with `<preference k="overpass-turbo-` and having the "bad" name in it), so I can debug this a bit quicker?

**Comment by tyrasd** [comment]
> I migrated my saved queries to osm.org

PS: the queries saved from the "beta" instance will probably not be available on the "main" overpass-turbo.eu when the feature goes live there, because the two instances are using different namespaces for their settings.
