### ISSUE TITLE
adiff: querying action type

### ISSUE THREAD

**Issue by cascafico** [tyrasd/overpass-turbo#327]
Hello,
I wonder if it's possible to extract OSM elements based on action (create|modify|delete).

Issue raised because often casual mappers (particularly those using maps.me app) when deleting abandoned/disused POIs are not aware that they are deleting useful tags like addresses.

A query to detect easily such deletions could be useful.
Here's a  [draft](http://overpass-turbo.eu/s/q2T) of my query, which extracts without filtering action.

**Comment by tyrasd** [comment]
seems like a duplicate of https://github.com/drolbr/Overpass-API/issues/154
