### ISSUE TITLE
Geometry of relation members is no longer shown

### ISSUE THREAD

**Issue by zstadler** [tyrasd/overpass-turbo#328]
For [example](http://overpass-turbo.eu/s/3Ee),
```
(
  relation(3791784);
  >;
);
out;
```
used to show all relation members, but it currently shows just one dot for the relation.

The same disappearance happens with `out  geom`:
```
relation(3791784);
out geom;
```

**Comment by mmd-osm** [comment]
Cannot reproduce. Here's how this looks like here:

![grafik](https://user-images.githubusercontent.com/5842757/28246621-cb7e905e-6a1e-11e7-9ab0-87fb3c1f497a.png)

**Comment by zstadler** [comment]
Strangely, it happens only on Firefox.
Clearing the cache did not help. The "console" in the developer tools show no errors.
I'm using the latest version - 54.0.1 (32-bit)

**Comment by mmd-osm** [comment]
I also tested on Firefox 54.0 (64bit) Ubuntu 16.04.

**Comment by zstadler** [comment]
Un-setting
![image](https://user-images.githubusercontent.com/1304610/28247869-679656d4-6a42-11e7-992f-61bcda05cf8c.png)
seems to cause the problem.

**Comment by tyrasd** [comment]
Hi. I also cannot reproduce any problem with the query and the way overpass turbo displays the results. Can you maybe describe the issue you're seeing a bit better? Maybe also post screenshot(s) of how it looks like at your side (compared to what @mmd-osm posted above)?

**Comment by zstadler** [comment]
How to reproduce:
- Use Firefox 32-bit Windows 53.0 or higher
- Open http://overpass-turbo.de
- Settings -> Map -> Un-check the box next to "Don't display small features as POIs."
- Run the query `(relation(3791784);>;);out;`

Instead of the result provided by @mmd-osm above, I receive:
<img width="218" alt="2017-07-17 14_19_27-" src="https://user-images.githubusercontent.com/1304610/28266098-cb8b135a-6afb-11e7-90d9-de3402591890.png">

![image](https://user-images.githubusercontent.com/1304610/28266135-ef956b92-6afb-11e7-9163-fcf15d731d5f.png)

**Comment by mmd-osm** [comment]
I need to zoom out quite a bit to get the same result:

![grafik](https://user-images.githubusercontent.com/5842757/28266244-1a6a3918-6af4-11e7-9100-02c8e96894af.png)

Does this change if you zoom in further?  What's your screen resolution by the way?

**Comment by tyrasd** [comment]
Really odd.

I've looked into the [relevant code](https://github.com/tyrasd/overpass-turbo/blob/master/js/GeoJsonNoVanish.js#L47) for a bit, but can't see anything that could possibly be causing this.

@zstadler can you try a few more things, please:

* is the polygon not even shown when you zoom the map all the way in?
* do you have any browser plugins installed that are somehow related to and/or could potentially interfere with the *Leaflet* slippy map?
* do you see the same behavior also if you open overpass-turbo in a new "private" firefox window?

**Comment by zstadler** [comment]
* The screen resolution is 1920 x 1080 pixels. There is no change in this behavior when the screen resolution is changed to 800 x 600 pixels or when the window size is reduced dramatically.

* The single POI is there when zooming-in to "20 m". It seems to expand only at the "10 m" zoom level:
  <img width="81" src="https://user-images.githubusercontent.com/1304610/28276158-bc483f58-6b1e-11e7-9939-3d1970c8bdd6.png"> <img width="81" src="https://user-images.githubusercontent.com/1304610/28276251-fd00f35a-6b1e-11e7-85ad-031c235a6330.png">

* As far as I know, the "Tab Mix Plus", and "Saved Password Editor" have nothing to do with Leaflet. I've also disabled my add blocking plugin to be on the safe side.

* The same behavior is experienced in a new "Private" window.

**Comment by zstadler** [comment]
Is there a test site, with the original multi-line JavaScript code, which I can use to try and debug the execution of the `_onZoomEnd` function in my browser?

**Comment by tyrasd** [comment]
> Is there a test site […] which I can use to try and debug

At the moment not, but setting up a local development instance is [not hard](https://github.com/tyrasd/overpass-turbo#install--run): just git clone the repo, install nodejs if you don't have it already, then run `npm install` and `npm run` in the console.

Also, thanks for the additional information. Apparently, the check on [line 44](https://github.com/tyrasd/overpass-turbo/blob/master/js/GeoJsonNoVanish.js#L44) works fine, but for some reason a similar test in [line 50](https://github.com/tyrasd/overpass-turbo/blob/master/js/GeoJsonNoVanish.js#L50) (which compares the feature's bounding box size against a set threshold) doesn't trigger. If you could manage to debug this function, it would be really interesting to see what's in the variables `p1`, `p2`, `d`, `bounds` and `this.options.threshold` at that point.

One more question: does this happen only with multipolygon relations or also with other large osm objects (e.g. ways, route relations)? Does it happen only for this particular multipolygon relation or all osm multipolygons?

**Comment by mmd-osm** [comment]
In Firefox, you can also switch to Development Mode via F12, then go to Debug tab, and press "Format source code" (the `{ }` icon): 
![grafik](https://user-images.githubusercontent.com/5842757/28306662-7a2eba34-6ba0-11e7-8886-f09338232ea7.png)

That makes the source code readable and you can also set breakpoints more easily.

**Comment by zstadler** [comment]
> In Firefox, you can switch to Development Mode via F12, then go to Debug tab, and press "Format source code" (the `{ }` icon):
![grafik](https://user-images.githubusercontent.com/5842757/28306662-7a2eba34-6ba0-11e7-8886-f09338232ea7.png)
>  
> That reformats source code and makes readable, you can also set breakpoints more easily.

Unfortunately, reformatting does not insert line-breaks for me.

**Comment by zstadler** [comment]
Very strange indeed...

For some strange reason, the `Math.sqrt()` function in [line 36](https://github.com/tyrasd/overpass-turbo/blob/master/js/GeoJsonNoVanish.js#L36) and [line 49](https://github.com/tyrasd/overpass-turbo/blob/master/js/GeoJsonNoVanish.js#L49) always return `NaN`.

I know it's hard to believe, so here is a screenshot from the debugger showing the values of `p1`, `p2`, and `d`:

![image](https://user-images.githubusercontent.com/1304610/28317155-776c1e12-6bce-11e7-9230-6f545a0da92c.png)

My suggestion is to avoid the use of `Math.sqrt()`:
```
      var d2 = (p1.x - p2.x) ** 2 + (p1.y - p2.y) ** 2;
      if (d2 > this.options.threshold ** 2) return;
```
Exponentiation should also be a bit faster :-)

I tested the code with a few examples, and it seems to be working fine.

**Comment by tyrasd** [comment]
Wow. :astonished: Looks very much like a bug in Firefox's javascript engine / Math lib implementation.

Did you test what happens if you invoke `Math.sqrt` manually in the js console? Or maybe `Math.pow` is outputting some wrong results? What's on your machine the output of:
* `Math.pow(p1.x - p2.x, 2)`
* `typeof Math.pow(p1.x - p2.x, 2)`
* `Math.sqrt(16)`

**Comment by zstadler** [comment]
```
> Math.pow(p1.x - p2.x, 2)
54010.15530796014
> typeof Math.pow(p1.x - p2.x, 2)
"number"
> Math.sqrt(16)
4
> Math.sqrt(16.3)
NaN
> typeof 16.3
"number"
> Math.sqrt(16.3**2)
16.3
```
A new [Firefox bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1381880) was opened. However, I would not hold my breath for a Firefox fix...

**Comment by tyrasd** [comment]
Thanks for reporting this upstream, @zstadler !

**Comment by zstadler** [comment]
Thanks @tyrasd for the quick fix!

By the way, what's the reason for using `Math.pow()` rather than the exponentiation operator `**`?

**Comment by tyrasd** [comment]
For backwards compatibility reasons, I don't yet use ES6 and ES7 syntax features here.

**Comment by zstadler** [comment]
Is there a time estimate for releasing the fix?

**Comment by tyrasd** [comment]
> Is there a time estimate for releasing the fix?

it's live on http://overpass-turbo.eu now.

**Comment by mmd-osm** [comment]
BTW: culprit has been identified: https://developercommunity.visualstudio.com/content/problem/86702/c-runtime-math-scalar-version-of-sqrt-gives-incorr.html
