### ISSUE TITLE
download/copy for raw data?

### ISSUE THREAD

**Issue by DaveF63** [tyrasd/overpass-turbo#330]
Is there a reason for not having a download/copy for raw data option?

I'm aware of the raw data directly from Overpass API but that opens in a file with a predefined name. I'm finding I need to paste into an existing file.

**Comment by mmd-osm** [comment]
Overpass turbo cannot influence the file name, that's all defined by overpass api. I guess you're looking for something like https://github.com/drolbr/Overpass-API/issues/153

**Comment by DaveF63** [comment]
I received this email reply from @mmd-osm but is isn't showing here: 

"Overpass turbo cannot influence the file name, that's all defined by overpass api. I guess you're looking for something like drolbr/Overpass-API#153"

My Reply:
No. I was asking if "there's a reason for not having a download/copy for raw data option?"

**Comment by mmd-osm** [comment]
That's exactly why my comment is no longer there, I removed it because it didn't answer your question

**Comment by tyrasd** [comment]
There's no specific reason for not having the copy-to-clipboard option for the *raw data* export option,  other than that it wasn't included in #321 (it was probably just "overlooked" there, I guess //cc @simon04).
