### ISSUE TITLE
make uid: and id: numerically comparable

### ISSUE THREAD

**Issue by polarbearing** [tyrasd/overpass-turbo#331]
As I understand, I can write statements to match a particular ```uid:``` or a list of such.
I can also make numerical comparisons with tag values, such as maxspeed>30.
However it seems I cannot make numerical comparisons with meta data (except the changset date).

It would be quite helpful e.g. when checking for sock puppets created by blocked users, based on the assumption that new uids are created with increasing numbers, to have a statement like  ```number([uid:]) > 1000000```.

Probably also good for the object ```id:```

(So far my workaround is to create a CSV and throw it into sort -n )

**Comment by tyrasd** [comment]
That sounds like a ticket for the upstream Overpass-API repository. Please consider reporting there: https://github.com/drolbr/Overpass-API/issues – but it looks like as if (parts of) this feature request was already discussed in https://github.com/drolbr/Overpass-API/issues/367
