### ISSUE TITLE
Error: runtime error: open64: 2 No such file or directory /osm3s_v0.7.54_osm_base Dispatcher_Client::1

### ISSUE THREAD

**Issue by YachtingsBest** [tyrasd/overpass-turbo#332]
Recieved this when running an overpass query today, any thoughts? Thanks, love Overpass!

An error occured during the execution of the overpass query! This is what overpass API returned:

Error: runtime error: open64: 2 No such file or directory /osm3s_v0.7.54_osm_base Dispatcher_Client::1

![screenshot at jul 19 20-04-39](https://user-images.githubusercontent.com/10001854/28397244-a475a9b0-6cbd-11e7-8880-105108a6490a.png)

**Comment by MaartenDeen** [comment]
I get similar errors trying to download overpass data from JOSM. When I use query builder to build a query for railway=rail, I get this query:
`[out:xml][timeout:25][bbox:{{bbox}}];
(
   node["railway"="rail"];
   way["railway"="rail"];
   relation["railway"="rail"];
);
(._;>;);
out meta;`
which gives error "Failed to download data. Its format is either unsupported, ill-formed, and/or inconsistent/
Details (untranslated): runtime errror: open64: 763 Unknown error 763 /opt/osm-3s/v0.7.54/db/user_data.bin File_Blocks::read_block: Index
inconsistent."

Other queries give me Unknown error 1500. Queries I know worked yesterday.

**Comment by Supaplextw** [comment]
Here is the error I got:


[image: 內置圖片 2]

runtime error: open64: 1506 Unknown error 1506
/opt/osm-3s/v0.7.54/db/relations.bin File_Blocks::read_block: Index
inconsistent

Dennis

2017-07-20 14:48 GMT+08:00 MaartenDeen <notifications@github.com>:

**Comment by nrenner** [comment]
See https://wiki.openstreetmap.org/wiki/Overpass_API/status

To use another [server instance](https://wiki.openstreetmap.org/wiki/Overpass_API#Introduction) e.g. add 

    {{data:overpass,server=http://overpass.osm.rambler.ru/cgi/interpreter/}}

to your query in Overpass Turbo.
