### ISSUE TITLE
Remove French instance from server list?

### ISSUE THREAD

**Issue by mmd-osm** [tyrasd/overpass-turbo#333]
Unfortunately the French instance is no longer updating and also not maintained anymore.

**Comment by tyrasd** [comment]
ok, that's very unfortunate, but thanks for the heads up. I'll shortly remove it from the default list.

**Comment by mmd-osm** [comment]
Maybe this was a bit premature, new instance is being set up: https://github.com/osm-fr/ansible-scripts/pull/3

**Comment by tyrasd** [comment]
ok. can you let me know when their "new" instance is online?

**Comment by jocelynj** [comment]
Hi,

It is true that @RoPP is currently installing a new instance of Overpass on a VM on french infrastructure. Hopefully, it will be stable in a few days. For the moment, we have french data only on dev.api.openstreetmap.fr/overpass, for basic trials.

**Comment by RoPP** [comment]
The osmfr instance is available again. Please note that url has changed: http(s)://overpass.openstreetmap.fr/api.

**Comment by tyrasd** [comment]
nice. It's now updated in cf24e4d4a4d147064a03bacc3dba0a06cd090e01

Btw, @RoPP I noticed that your server doesn't return a proper error message when one tries to access attic data (I guess that's simply missing on your instance, right?). Instead one gets some invalid partial JSON or XML content: http://overpass-turbo.eu/s/rrK

**Comment by mmd-osm** [comment]
overpass.openstreetmap.fr resolves to 3 different hosts:

overpass.openstreetmap.fr	canonical name = cluster-ovh.openstreetmap.fr.
Name:	cluster-ovh.openstreetmap.fr
Address: 164.132.171.101
Name:	cluster-ovh.openstreetmap.fr
Address: 137.74.202.107
Name:	cluster-ovh.openstreetmap.fr
Address: 164.132.171.132


Seems as if not all of them have overpass installed? Right now I cannot get to any of them.
