### ISSUE TITLE
Wizard:  in 'Antarctica'  - not working

### ISSUE THREAD

**Issue by ImreSamu** [tyrasd/overpass-turbo#335]
I have found an interesting ` in <area>`  problem,  but I don't know,  how I can fix.

### Test example:
* Wizard:  `"amenity"="atm" in 'Antarctica'`   - no result 
* URL:  [https://overpass-turbo.eu/?w=%22amenity%22%3D%22atm%22+in+%27Antarctica%27&R](https://overpass-turbo.eu/?w=%22amenity%22%3D%22atm%22+in+%27Antarctica%27&R)

### Expected behavior :

1 result:

* https://www.openstreetmap.org/node/3611155242
* this is inside in the overpass database [http://overpass-turbo.eu/s/r2L](http://overpass-turbo.eu/s/r2L)

```xml
<node id="3611155242" visible="true" version="2" changeset="47272585" timestamp="2017-03-29T20:01:07Z" user="herried" uid="5580970" lat="-77.8461465" lon="166.6679804">
  <tag k="amenity" v="atm"/>
  <tag k="drive_through" v="no"/>
  <tag k="name" v="Wells Fargo ATM"/>
  <tag k="note" v="Only ATM on Antarctica"/>
  <tag k="operator" v="Wells Fargo"/>
  <tag k="source" v="Wikipedia"/>
</node>
```

### Actual behavior:

0 result

### Generated OVERPASS QL:

```
[out:json]
[timeout:25]
;
area(3602186646)->.searchArea;
(
  node
    ["amenity"="atm"]
    (area.searchArea);
  way
    ["amenity"="atm"]
    (area.searchArea);
  relation
    ["amenity"="atm"]
    (area.searchArea);
);
out;
>;
out skel qt;
```

Probably find this  area  [r2186646](http://www.openstreetmap.org/relation/2186646)  `name=Antarctica`
OSM Relation Analyzer: [r2186646](http://ra.osmsurround.org/analyzeRelation?relationId=2186646&_noCache=on)   =>  `Great! This relation seems ok.`

### CONTEXT:

I am customizing [Taginfo](https://github.com/taginfo/taginfo/blob/master/taginfo-config-example.json#L59)  for Antarctica ( [Geofabrik extract](http://download.geofabrik.de/antarctica.html)   ), 
and this basic setting is not working for Antarctica.

```
  "turbo": {
    "max_auto": 1000,
    "url_prefix": "https://overpass-turbo.eu/?",
    "wizard_area": "in 'Antarctica'"
  },
```

with the above config, Taginfo generates this query: 
`https://overpass-turbo.eu/?w=%22amenity%22%3D%22atm%22+in+%27Antarctica%27&R`
but in this case, it is not working.

### Other test cases
* [“"amenity"=* in 'Antarctica'”](https://overpass-turbo.eu/?w=%22amenity%22%3D*+in+%27Antarctica%27&R)
* [“"shop"=* in 'Antarctica'”](https://overpass-turbo.eu/?w=%22shop%22%3D*+in+%27Antarctica%27&R)

**Comment by mmd-osm** [comment]
That's an upstream issue with Overpass API. Please report it here: https://github.com/drolbr/Overpass-API/issues

**Comment by ImreSamu** [comment]
thank you,   I am reported here https://github.com/drolbr/Overpass-API/issues/421
