### ISSUE TITLE
Focus off world occasionally

### ISSUE THREAD

**Issue by andk** [tyrasd/overpass-turbo#339]
Today it has happened twice to me with two different targets. I visited the page http://overpass-turbo.eu/ . I entered the target into search field on the map, the pulldown recognized the target so I could pick directly from the pulldown, the map turned into the gray background. I then zoomed out until I reached "3000 km" in the legend and then the whole earth (on the Siberia end) entered the map from the left.

The two targets were 'Pico, Azores' and 'Mayaguana, The Bahamas'.

I have reproduced it in two different versions of Firefox and in Chrome.

**Comment by tyrasd** [comment]
Hm, strange. Seems to be a bug of the geocoder *OSMNames* I'm using: https://github.com/OSMNames/OSMNames/issues/141

**Comment by tyrasd** [comment]
this seem to be fixed upstream by now.
