### ISSUE TITLE
"runtime error" message unhelpful

### ISSUE THREAD

**Issue by SomeoneElseOSM** [tyrasd/overpass-turbo#340]
https://overpass-turbo.eu/ can return this as an error:

> An error occured during the execution of the overpass query! This is what overpass API returned:
> 
> Error: runtime error: […] Please check /api/status for the quota of your IP address.

Unfortunately, http://overpass-turbo.eu/api/status just gives a 404 error.
Presumably what it is trying to say is that the URL that it used internally (which I as a user don't know) should have /api/status added to it to understand the problem.

Unfortunately although it knows the URL, I don't :)

**Comment by mmd-osm** [comment]
This error message is coming from Overpass API (the database backend), hence you probably want to check overpass-api.de/api/status instead.

As the error message is way too technical I already filed a bug here for a more meaningful response: https://github.com/drolbr/Overpass-API/issues/351

**Comment by SomeoneElseOSM** [comment]
I know that the error's coming from Overpass, but I don't know which overpass instance I'm actually using - only Overpass turbo knows that.  If Overpass Turbo presents a message that says "Please check $url for the quota of your IP address." it seems only fair to include the whole URL to check and not have me have to guess part of it.

Also note that the issue has been logged at Overpass (https://github.com/drolbr/Overpass-API/issues/445#issuecomment-343091462) and they, correctly in my opinion, pointed back here.

**Comment by mmd-osm** [comment]
The whole /api/status concept doesn't make that much sense for a typical user. All a user wants to know is how many seconds you need to wait before trying again. Everything else shown in /api/status really is completely irrelevant, unless you want to chase some bugs.

That's why I'm suggesting to not spend any time on this issue, but rather wait for drolbr/Overpass-API#351

**Comment by SomeoneElseOSM** [comment]
OK - makes sense.

**Comment by SomeoneElseOSM** [comment]
Given that https://github.com/drolbr/Overpass-API/issues/351 has been open since 2016 now, perhaps it might be worth considering parsing what http://overpass-api.de/api/status returns?

Example below for those unfamiliar with it:

    Connected as: 1453004021
    Current time: 2021-03-18T14:45:23Z
    Rate limit: 2
    Slot available after: 2021-03-18T14:46:56Z, in 93 seconds.
    Slot available after: 2021-03-18T14:48:15Z, in 172 seconds.
    Currently running queries (pid, space limit, time limit, start time):
