### ISSUE TITLE
Abort only just rendering when receiving large datasets

### ISSUE THREAD

**Issue by RicoElectrico** [tyrasd/overpass-turbo#341]
Currently if you opt to not render a dataset that is >2 MB, you can't even view it in text or export it.

**Comment by mmd-osm** [comment]
Depending on the size of the result, _Export -> raw data directly from Overpass API_ may be the only sane option, as handling large amounts of XML or JSON typically comes with quite a heavy memory footprint in your browser.

**Comment by tyrasd** [comment]
as @mmd-osm already pointed out: the displaying of the raw data in the "data" tab is just as slow (if not slower) than the map display itself. Also transforming the data to geojson (which is necessary for most export options) can also become slow for very large data sets.

overpass turbo is not really made for handling larger data sets. If you hit these limits, it can make sense to switch from the browser environment to the command line (e.g. using https://github.com/tyrasd/osmtogeojson).
