### ISSUE TITLE
missing text if web address is part of a tag

### ISSUE THREAD

**Issue by RedEmile** [tyrasd/overpass-turbo#344]
Having a weblink within f.ex. note=*, overpass won't show the whole note's text, but only the webaddress.
Example:

> http://overpass-turbo.eu/s/sBj -> click on way ->  _**note=https://en.wikipedia.org/wiki/Grand_River_(Oklahoma)**_

> http://www.openstreetmap.org/way/458324356 -> full text is as follows  -> _**note="The Grand River is an alternate name for the lower section of the Neosho River...", see https://en.wikipedia.org/wiki/Grand_River_(Oklahoma)"**_

**Comment by tyrasd** [comment]
Thanks for the report. Strange that this apparently hasn't been noticed until now :see_no_evil:

It's fixed now on the master branch (test instance [here](http://overpass-turbo.eu/master/?Q=way(210562454)%3B%0Aout%20geom%3B&C=49.10813;8.85228;18)).

**Comment by RedEmile** [comment]
Thanks for quick debugging. When will it probably be part of the "normal" overpass-turbo?

**Comment by tyrasd** [comment]
not sure. since this isn't really a "bad" bug I wasn't thinking about doing a proper release just for it… Hm, I might just go ahead an just cherry-pick and deploy this small fix on overpass-turbo right now.
