### ISSUE TITLE
Store custom API link in cookies

### ISSUE THREAD

**Issue by mueschel** [tyrasd/overpass-turbo#345]
Settings allow to define an own Overpass API to get data from. It would be nice if custom URIs could be stored (e.g. in a cookie). Currently changing forth and back from the official API to an own one requires typing in the custom URI every time, because the drop-down only lists the official APIs.

**Comment by mmd-osm** [comment]
Duplicate of https://github.com/tyrasd/overpass-turbo/issues/243#issuecomment-223749618
