### ISSUE TITLE
Shortcut for closed ways (areas)

### ISSUE THREAD

**Issue by naoliv** [tyrasd/overpass-turbo#346]
I don't know if there is already a shortcut for this, sorry, but like we already have the [`area` clause](https://wiki.openstreetmap.org/wiki/Overpass_API/Language_Guide#Area_clauses_.28.22area_filters.22.29) to select closed ways and relations, could we have something to select only closed ways (excluding all relations, therefore), please?

**Comment by mmd-osm** [comment]
That feature of Overpass API hasn’t been released yet. Stay tuned.
