### ISSUE TITLE
Add kumi.systems Overpass Instance

### ISSUE THREAD

**Issue by kumitterer** [tyrasd/overpass-turbo#348]
You may want to add the instance at https://overpass.kumi.systems/api/ to the list of suggested servers. It runs on quite strong hardware (see [wiki](https://wiki.openstreetmap.org/wiki/Overpass_API)) and keeps attic data, so it should be able to take some load off the instance at overpass-api.de.

**Comment by tyrasd** [comment]
awesome. added in 786678074dbf39526fef273da7a29c71a4da4460

**Comment by mmd-osm** [comment]
Is your server still up and running? Tried several times in the last weeks and always getting errors.

**Comment by tyrasd** [comment]
@mmd-osm it works for me (now): https://overpass.kumi.systems/api/interpreter?data=node%28666%29%3B%20out%3B

**Comment by mmd-osm** [comment]
I'm getting connection rejected errors on my mobile phone only, desktop works ok. Will keep an eye on it. Thanks for testing!

**Comment by mmd-osm** [comment]
I'm getting http 502 Bad Gateway right now even on the desktop.

**Comment by kumitterer** [comment]
That's odd, I just executed a couple of queries successfully. I'll keep an eye on it.

**Comment by tyrasd** [comment]
at the moment requests take very long:

```
$ time curl "https://overpass.kumi.systems/api/interpreter?data=node%28666%29%3B%20out%3B"
<?xml version="1.0" encoding="UTF-8"?>
<osm version="0.6" generator="Overpass API 0.7.54.12 054bb0bb">
<note>The data included in this document is from www.openstreetmap.org. The data is made available under ODbL.</note>
<meta osm_base="2018-02-21T09:27:02Z"/>

  <node id="666" lat="68.3972288" lon="16.8342185"/>

</osm>

real	6m9.945s
```

(overpass-api.de returns the same result in 0.3 seconds)

**Comment by tyrasd** [comment]
now I'm seeing `502 Bad Gateway` errors again. Any ideas why your instance is so unstable @kumitterer ?

**Comment by kumitterer** [comment]
I don't have a clue, to be perfectly honest. Everything seems to be running just fine. I may have to set it up from scratch again. Sorry about that.

**Comment by kumitterer** [comment]
It appears to be an issue with fcgiwrap which somehow won't handle the connections properly, rather than Overpass itself. I'll do my very best to find a solution as soon as possible.

**Comment by kumitterer** [comment]
I changed from the former nginx + fcgiwrap configuration to using Apache behind an nginx reverse proxy. This seems to be much faster and more stable. I also took the opportunity to upgrade to the latest version of the Overpass API. Hopefully, this will solve the issues permanently. I also set up a monitoring tool to notify me about downtimes and unusually long response times.

**Comment by tyrasd** [comment]
The service is now quite stable, from what I can see. Thanks @kumitterer.

I just noticed a strange error message with some attic requests on your instance:

This simple [query](https://overpass.kumi.systems/api/interpreter?data=%5Bdate%3A%222014-01-01T00%3A00%3A00Z%22%5D%3B%0Away%2848655952%29%3B%20out%20geom%3B%0A%0A) contains the following as part of the returned result:

```xml
<remark>
runtime error: Way 48655952 cannot be expanded at timestamp 2017-12-09T10:42:07Z.
</remark>
```

(the rest of the returned data looks ok, apart from a missing `name` tag, which should be there).

The same request works fine when executed on the main Overpass-API [instance](http://overpass-api.de/api/interpreter?data=%5Bdate%3A%222014-01-01T00%3A00%3A00Z%22%5D%3B%0Away%2848655952%29%3B%20out%20geom%3B%0A%0A).

**Comment by mmd-osm** [comment]
> Way 48655952 cannot be expanded at timestamp 2017-12-09T10:42:07Z.

In most cases this turned out to be some data corruption in the attic database files, unfortunately...

**Comment by kumitterer** [comment]
It's odd that a database I only just cloned from overpass-api.de three or four days ago would already be corrupted. Anyway, I just started cloning it again. Hopefully that'll fix it.

**Comment by kumitterer** [comment]
@tyrasd Your query seems to work fine with the new database.
