### ISSUE TITLE
Exporting the request cuts off "geom" from "out geom;"

### ISSUE THREAD

**Issue by naomap** [tyrasd/overpass-turbo#349]
Given a request that uses the statement "out geom;", for instance 👍 

    rel[route=bus][network="Transpole"][ref=18];
    way(r);
    out geom;

Exporting that request cuts off 'geom' from the out statement, for no apparent reason. 
This makes it harder to reuse the result of the request in uMap for instance...

**Comment by tyrasd** [comment]
which export option do you use for this? export -> query -> raw query and export -> query -> standalone query seem to work fine to me. :confused:

**Comment by naomap** [comment]
This occurs when using Export -> Query -> Convert to Overpass QL (both normal and compact).

**Comment by tyrasd** [comment]
oh, that's a functionality provided by the Overpass-API itself, so it has need to be reported and fixed there: https://github.com/drolbr/Overpass-API/issues/ – would you mind opening a new ticket there?

it reminds me a bit of https://github.com/drolbr/Overpass-API/issues/183

**Comment by tyrasd** [comment]
thanks @naomap -> https://github.com/drolbr/Overpass-API/issues/450
