### ISSUE TITLE
Broken search for "objects that have a tag with key key" 

### ISSUE THREAD

**Issue by tordans** [tyrasd/overpass-turbo#350]
My goal is a map of all objects that use a given key (key is present) regardless of the key value.

According to https://wiki.openstreetmap.org/wiki/Overpass_turbo/Wizard#Tag_Searches it should be possible in a few ways:

**Try 1: All objects where key playground is present and value for this key is "anything"**
```
node
  [playground=*]({{bbox}});
out;
```
This does not work:
>Ein Fehler ist während der Ausführung der Abfrage aufgetreten. Folgendes hat die API als Fehlermeldung zurückgegeben:
Error: line 2: parse error: Value expected - '*' found.
Error: line 2: parse error: ']' expected - '*' found.

**Try 2**
```
node
  [playground==*]({{bbox}});
out;
```
This does not work:
>Ein Fehler ist während der Ausführung der Abfrage aufgetreten. Folgendes hat die API als Fehlermeldung zurückgegeben:
Error: line 2: parse error: '!', '~', '=', '!=', or ']' expected - '==' found.

**Try 3**
```
node
  [playground is not null]({{bbox}});
out;
```
This does not work:
>Ein Fehler ist während der Ausführung der Abfrage aufgetreten. Folgendes hat die API als Fehlermeldung zurückgegeben:
Error: line 2: parse error: '!', '~', '=', '!=', or ']' expected - 'is' found.

**Try 4**
```
node
  [playground!=""]({{bbox}});
out;
```
This should work, since the descriptions says "Matches objects that do not have a tag with key key and the value value.", so key is required an value should not be empty aka "anything".

However, this returns all kind of objects in the area, regardless of its key(-name).

**Try 5 / Success**
```
node
  [playground~".*"]({{bbox}});
out;
```
Only this returns the desired results.

# Questions
- Is https://wiki.openstreetmap.org/wiki/Overpass_turbo/Wizard#Tag_Searches wrong? Or am I missunderstanding things? Or it the overpass-UI wrong? Or the API behind overpass?
- And where should I address this issue, depending on the above answer.

Thanks!

**Comment by mmd-osm** [comment]
You're mixing Overpass Turbo Wizard and Overpass QL syntax! Try 1 - 3 are all using a syntax, which is a mixture of both Wizard and Overpass QL, and is in fact invalid either way.

Correct for your use case would be:

```C
node
  [playground]({{bbox}});
out;
```

**Comment by tyrasd** [comment]
thanks @mmd-osm for the comprehensive reply, I hope that answers all your questions @tordans.

btw: the wiki-page even has a nice picture for where exactly to enter these search queries:

![](https://wiki.openstreetmap.org/w/images/9/99/Overpass_turbo_query_wizard_steps_part_1.png)

**Comment by tyrasd** [comment]
PS: If you found this a bit confusing, and have a suggestion about how to improve the documentation on the osm-wiki, please let us know. :relaxed: (Or even better: go ahead and improve the pages by yourself if you feel confident.)

**Comment by tordans** [comment]
@mmd-osm thanks! I still need to look into it in detail, but I am pretty sure this will help.
@tyrasd will do! :)
