### ISSUE TITLE
Map PNG Export appears to hang

### ISSUE THREAD

**Issue by SK53** [tyrasd/overpass-turbo#351]
I appreciate this may purely be a factor on my desktop, but the Export Map (as PNG) just appears to hang. I have used this successfully in the past, but it no longer works (on various releases of FF).

**Comment by tyrasd** [comment]
confirming

**Comment by tyrasd** [comment]
fixed in master: https://overpass-turbo.eu/master/

**Comment by joostschouppe** [comment]
This bug seems to have re-appeared.
