### ISSUE TITLE
different users request (OSM quality)

### ISSUE THREAD

**Issue by JLZIMMERMANN** [tyrasd/overpass-turbo#352]
Something is missing : be able to display differents users with different colurs. I started with this http://overpass-turbo.eu/s/tGN   but I don't know how to give colours to each user.
This feature would be really helpfull for mapping parties and when we wish to see on the map how many objects were edited per user.

**Comment by tyrasd** [comment]
some context: https://twitter.com/JLZIMMERMANN/status/939957202965663745

**Comment by tyrasd** [comment]
This is now implemented in the master branch and available for testing on overpass-turbo's beta instance: Here's are [two](https://overpass-turbo.eu/master/?Q=%5Bout%3Ajson%5D%3B%0Anode%0A%20%20%5Bamenity%3Ddrinking_water%5D%0A%20%20(%7B%7Bbbox%7D%7D)%3B%0Aout%20meta%3B%0A%0A%7B%7Bstyle%3A%0A%0Anode%20%7B%0A%20%20fill-color%3A%20gray%3B%0A%20%20fill-opacity%3A%201%3B%0A%20%20opacity%3A%200%3B%0A%20%20symbol-size%3A%204%3B%0A%7D%0Anode%5B%40uid%3D26139%5D%20%7B%0A%20%20fill-color%3A%20blue%3B%0A%7D%0A%0A%7D%7D%0A&C=41.89953;12.50201;14) [examples](https://overpass-turbo.eu/master/?Q=%5Bout%3Ajson%5D%3B%0Away%0A%20%20%5Bbuilding%5D%0A%20%20(%7B%7Bbbox%7D%7D)%3B%0Aout%20center%20meta%3B%0A%0A%7B%7Bstyle%3A%0A%0Anode%20%7B%0A%20%20fill-color%3A%20gray%3B%0A%20%20fill-opacity%3A%200.4%3B%0A%20%20opacity%3A%200%3B%0A%20%20symbol-size%3A%204%3B%0A%7D%0Anode%5B%40user%3Dtyr_asd%5D%20%7B%0A%20%20fill-color%3A%20blue%3B%0A%7D%0A%0A%7D%7D%0A&C=46.45879;11.29395;13)
