### ISSUE TITLE
Textfeld not editable in mobile Safari and Firefox

### ISSUE THREAD

**Issue by bitnapper** [tyrasd/overpass-turbo#354]
In Safari and Firefox on iOS (iPhone or iPad) the textbox cant be edited. Text can be selected but not be changed, added or removed.

**Comment by HolgerJeromin** [comment]
Just a note: No other browser is allowed to have its own rendering engine on iOS. So Firefox/Chrome on iOS is quite the same than Safari.

**Comment by tyrasd** [comment]
duplicate of #267, see the workaround posted there.
