### ISSUE TITLE
Wrong translation

### ISSUE THREAD

**Issue by musuruan** [tyrasd/overpass-turbo#355]
Please change the following translation to "Lingua"

https://github.com/tyrasd/overpass-turbo/blob/f72573a8552911920c5c51bc95ed782a67776559/locales/it.json#L33

Thanks!

Andrea

**Comment by mmd-osm** [comment]
Translations are done on Transifex. You can even fix it yourself once you have signed up: see https://github.com/tyrasd/overpass-turbo#translating

**Comment by musuruan** [comment]
Thanks for pointing me to Transifex. I just updated the translation.
