### ISSUE TITLE
expose id of object in the map style

### ISSUE THREAD

**Issue by matkoniecz** [tyrasd/overpass-turbo#356]
I am making an overpass query where I want specific object to have a special styling.

Unfortunately, it seems that id of objects is not exposed to a map style (see http://overpass-turbo.eu/s/u4p with some of my attempts, none of examples or docs at https://wiki.openstreetmap.org/wiki/Overpass_turbo/MapCSS was useful ).

In my case I want to apply styling to group of objects and have one specific with a label (as repeating label for every single one would result in horrid rendering).

I thought about using make/convert to either add some marker tags or to create bunch of nodes, one of each type to create a legend - but according https://github.com/drolbr/Overpass-API/issues/335

> In OSM used names are on purpose possible, as explained. In particular, it will not be possible to manipulate tags and keep the meta information. This is to discourage mechanical edits, but to enable people modifying data on the fly.

(BTW, I am not entirely sure is it necessary as it seems that there are easier ways to make mechanical edits)

Currently it seems that the only way to achieve this is to find some rare tag combination and use it to assign label (see http://overpass-turbo.eu/s/u4q for an example).

So, it would be desirable to have some way to assign styling based on object id.

**Comment by tyrasd** [comment]
This sounds like a reasonable addition, in line with the feature request #352 about exposing user-names in mapcss styles.

As far as I can see, the MapCSS [specs](https://wiki.openstreetmap.org/wiki/MapCSS/0.2) don't talk about a possibility to query and use these meta-data fields, though. Do you know if this is possible in [JOSM](https://josm.openstreetmap.de/wiki/Help/Styles/MapCSSImplementation) (or any of the other tools working with MapCSS)? If yes, how does the syntax look like there?

**Comment by matkoniecz** [comment]
I found

> osm_id()
>    returns the OSM id of the current object [since 5699] 

on https://josm.openstreetmap.de/wiki/Help/Styles/MapCSSImplementation but I am not sure is it usable in selectors

**Comment by tyrasd** [comment]
OK, I see.

What about a syntax like the following?

```css
way[@id=171784106]{
fill-color: red;
}
```

Using `@` would be similar to how overpass turbo exposes the osm ids in exported geojson. And it would directly generalize to other metadata fields (`@uid`, `@username`, etc.).

**Comment by tyrasd** [comment]
Implemented in master. Here's an [example](https://overpass-turbo.eu/master/?q=W2RhdGU6IjIwMTctMTItMjkiXQpbb3V0Ompzb25dOwpub2RlCiAgW2FtZW5pdHk9ZHJpbmvEsmdfd8SCZXLEksSlKHt7YmJveH19KcSexJV0xJ4KxL9zxK1sxIQKxJ_EoWVbQGlkPcSJMDkyOMSIOTFdIHvEpCDEg3jElyBldmFsKCcidGhpcyDEm2UhIifFhwp9xZLEoMSixaTFpmZpbGwtY29sb3I6IHfFtMSDxJ7EpcaFxoctb3BhY8SsecaPMcaUxbfGmsacxK3GjzDGoXN5bcWCxohzaXrEhCA0xJ7Fv8aBxZXFl8WZfi8oMXw0fDcpJC_Fo8WlxpXGhsaIxorGjMaOIHJlZMa0xZPEosWWxZg9xrooMnw1fDjHgseExoPHh8aXx4rGjcaPZ8eOxKrHkca2x5TGuca7M3w2fDnHnseFxoTHiMaJxovHpCBibHVlx5HFvsW_&c=BOyJXeRFbO)

**Comment by matkoniecz** [comment]
Thanks!
