### ISSUE TITLE
empty output for more specific filter

### ISSUE THREAD

**Issue by jose1711** [tyrasd/overpass-turbo#357]
a query to get address POIs from slovakia works fine.
```
[out:csv(name, ::"lat", ::"lon", ::"type")]
[timeout:300];
area(3600014296);
  (
    ._;
    )->.boundaryarea;
  (
    node["addr:housenumber"](area.boundaryarea);
  );

out body;
```

the problem occurs when i try to narrow down the search by excluding nodes with amenity and/or shop tags:
```
[out:csv(name, ::"lat", ::"lon", ::"type")]
[timeout:300];
area(3600014296);
  (
    ._;
    )->.boundaryarea;
  (
    node["addr:housenumber"][!"amenity"][!"shop"](area.boundaryarea);
  );

out body;
```

now i get empty response (no error). if i run the same query for a smaller area (you can use 3601556717 for testing), then i get the expected output.

**Comment by tyrasd** [comment]
this looks like something that should be reported upstream at Overpass API's issue tracker: https://github.com/drolbr/Overpass-API/issues

**Comment by tyrasd** [comment]
btw: when I tried to run the second query without the `out:csv` at the start, one gets an out-of-memory exception. Probably, it's just the error output that's broken in csv mode… :thinking:

**Comment by jose1711** [comment]
yes, you're absolutely right. csv output is chopped off. thank you for sharing this observation.
