### ISSUE TITLE
Add a "edit here" button

### ISSUE THREAD

**Issue by pietervdvn** [tyrasd/overpass-turbo#358]
It would be useful to have an button which redirects to the editor on OSM.org. Then it would be quite easy to fix issues which are highlighted by a query with one click.

**Comment by mmd-osm** [comment]
Duplicate of https://github.com/tyrasd/overpass-turbo/issues/144?

**Comment by tyrasd** [comment]
yes, thanks for linking the other issue. let's close the duplicate

**Comment by pietervdvn** [comment]
This is indeed a duplicate
Thanks for closing it.
