### ISSUE TITLE
short_url_service not working (probably because it is cross-domain)

### ISSUE THREAD

**Issue by datendelphin** [tyrasd/overpass-turbo#359]
I noticed that there isn't even a request sent for osm.li, our link shortener for overpass-turbo.osm.ch and my guess is that it is blocked by the browser because it is a different domain.

**Comment by mmd-osm** [comment]
Your shortening service URL points to http: `http://osm.li/`, which cannot be called from https site.
Try using `https://osm.li/` instead.

**Comment by datendelphin** [comment]
Yes you are right. I changed the urls. I checked with chromium, and it works. Previously I only checked with Firefox, and it still doesn't work with Firefox (52). There is unfortunately no message in the javascript console.

**Comment by mmd-osm** [comment]
Firefox return HTTP 403 here. There's some issue with your shortening service.

```
<!DOCTYPE html PUBLIC
"-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"></meta>
    <title>403 Forbidden</title>
    <style type="text/css">
    #powered_by {
        margin-top: 20px;
        border-top: 2px solid black;
        font-style: italic;
    }

    #traceback {
        color: red;
    }
    </style>
</head>
    <body>
        <h2>403 Forbidden</h2>
        <p>Request forbidden -- authorization will not help</p>
        <pre id="traceback">Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/lib/python2.7/dist-packages/cherrypy/lib/encoding.py", line 217, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/cherrypy/_cpdispatch.py", line 61, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/srv/osm.li/short-url/shorturl.py", line 122, in get
    raise cherrypy.HTTPError(403)
HTTPError: (403, None)
</pre>
    <div id="powered_by">
      <span>
        Powered by <a href="http://www.cherrypy.org">CherryPy 3.5.0</a>
      </span>
    </div>
    </body>
</html>
```

**Comment by datendelphin** [comment]
Wait, what? It works in Firefox for you and not in Chrome? It's the other way around here. The unrelated https bug should be fixed now, thanks for the info.

**Comment by mmd-osm** [comment]
I think the issue is fixed, both Firefox and Chrome are ok now.

**Comment by datendelphin** [comment]
To sum it up: Most of the problem was probably caused by the short_url_service url not being https. Thank you @mmd-osm for helping.
