### ISSUE TITLE
allow date entries relative to a current date

### ISSUE THREAD

**Issue by matkoniecz** [tyrasd/overpass-turbo#360]
I made query that detects highway=construction that require resurveying ( http://overpass-turbo.eu/s/vT5 ).

Unfortunately currently dates used in query must be updated manually what reduces usefulness of this query.

So, I am unable to just link this query to mapper, I must link it and provide explanation how one should manually update dates.

**Comment by tyrasd** [comment]
The [`{{date:…}}` shortcut](https://wiki.openstreetmap.org/wiki/Overpass_turbo/Extended_Overpass_Turbo_Queries#Available_Shortcuts) is probably what you're looking for, right?

**Comment by matkoniecz** [comment]
ouch

Somehow I am extraordinarily terrible at using Overpass documentation. But unfortunately while it sounds fitting something somehow is not working:

```
[timeout:180];
(
way[highway=construction][construction]({{bbox}});
) -> .all_roads_under_construction;
(
way[highway=construction][opening_date](if:date(t[opening_date])>date({{date:1 day}}))({{bbox}});
) -> .known_opening_date_in_future;
(
.all_roads_under_construction - .known_opening_date_in_future;
);
out body geom qt;
```

goes down with

```
Error: line 6: parse error: Operator expected, but "T13"found. 
```

Replacing {{date:1 day}} with datestring fixes problem (I used '2013-11-24T22:55:36.201Z ' from documentation...).

I also tried without wrapping {{date}} in a date function but it is also not working, with the same error.

**Comment by tyrasd** [comment]
it works if you enclose the generated date in quotes like this:

```
[timeout:180];
(
way[highway=construction][construction]({{bbox}});
) -> .all_roads_under_construction;
(
way[highway=construction][opening_date](if:date(t[opening_date])>date("{{date:1 day}}"))({{bbox}});
) -> .known_opening_date_in_future;
(
.all_roads_under_construction - .known_opening_date_in_future;
);
out body geom qt;
```

(I know having to enclose this with quotation marks is a bit stupid, but I think it's too late to change how this shortcut works by now.)

**Comment by matkoniecz** [comment]
Thanks! I attempted to improve documentation in https://wiki.openstreetmap.org/w/index.php?title=Overpass_turbo/Extended_Overpass_Turbo_Queries&diff=1564635&oldid=1371434 and posted https://gis.stackexchange.com/questions/270491/use-current-date-in-overpass-turbo-querries/270492#270492 to make it easier to google.

**Comment by tyrasd** [comment]
Thanks a lot for that! :+1:
