### ISSUE TITLE
allow querying by object area/way length

### ISSUE THREAD

**Issue by matkoniecz** [tyrasd/overpass-turbo#364]
Usecase example: finding mistagging like https://www.openstreetmap.org/way/222795099#map=19/52.51666/13.41946&layers=N or excluding them in program processing OSM data (I wanted to add this functionality in StreetComplete).

**Comment by tyrasd** [comment]
seems like a feature request for overpass api, right? if yes, it would be better if you could directly create a issue [there](https://github.com/drolbr/overpass-api/issues) instead.

**Comment by mmd-osm** [comment]
Way length will be available in 0.7.55 and yes we already had an issue for this 😎
