### ISSUE TITLE
highway=bus_stop node not found in query

### ISSUE THREAD

**Issue by shankari** [tyrasd/overpass-turbo#365]
This is a highway bus stop
<img width="1188" alt="screen shot 2018-03-06 at 1 41 37 pm" src="https://user-images.githubusercontent.com/2423263/37060113-2f84b0b0-2144-11e8-92de-7c91437a6c30.png">

But is not found in a search that includes `node["highway=bus_stop"]({{bbox}});`

<img width="1434" alt="screen shot 2018-03-06 at 1 40 32 pm" src="https://user-images.githubusercontent.com/2423263/37060269-9875c5f0-2144-11e8-91d4-a8c9830e90e4.png">

**Comment by tyrasd** [comment]
you have a typo in your query. please use `node["highway"="bus_stop"]({{bbox}});` instead of `node["highway=bus_stop"]({{bbox}});` (note the missing quotes before and after the equal sign) in your query, then it works as expected. :wink:

**Comment by shankari** [comment]
oops! That was embarrassing.

I think I was confused because there were other entries that were tagged `"highway"="bus_stop"` that were showing up in similar queries, but on checking them again, they were also tagged `"public_transport"="platform"`, so they matched the `public_transport` query.

Thanks for the clarification!
