### ISSUE TITLE
Park not highlighted?

### ISSUE THREAD

**Issue by moriakaice** [tyrasd/overpass-turbo#375]
This is clearly a park: https://www.openstreetmap.org/relation/3118071 It was marked as such over 4 years ago (in 2013).

However, the following query, when done with said park in view, does not highlight it:
```
[bbox:{{bbox}}];
(
    way[leisure=park];
);
out body;
>;
out skel qt;

{{style:
    way[leisure=park],
{ color:blue; fill-color:blue; }
}}
```

Is there any reason for that?

**Comment by mmd-osm** [comment]
This is the overpass turbo bug tracker. I think your howto question would be better served on help.openstreetmap.org

**Comment by moriakaice** [comment]
Thanks for the suggestion, will move it there!

**Comment by HolgerJeromin** [comment]
@moriakaice If you want to highlight a relation you have to use relation instead of way :)
```
[bbox:{{bbox}}];
(
    relation[leisure=park];
);
out body;
>;
out skel qt;

{{style:
    relation[leisure=park],
{ color:blue; fill-color:blue; }
}}

```

**Comment by moriakaice** [comment]
Yeah, what I don't understand why this is a `rel`, not `way`, even though other parks are :)
