### ISSUE TITLE
List total number of tags in details popup

### ISSUE THREAD

**Issue by PanderMusubi** [tyrasd/overpass-turbo#376]
Please list the total number of tags in details popup as is done in OSM editor, see attachments.

Implementing this will make it quicker or easier to compare data. When the total number of tags is not equal, a user can directly derive that from the number listed.

![2018-04-25-110340_1920x1080_scrot](https://user-images.githubusercontent.com/198964/39236486-43d9b7ac-4879-11e8-963d-7f8e539c067b.png)

![2018-04-25-110624_1920x1080_scrot](https://user-images.githubusercontent.com/198964/39236498-49e67748-4879-11e8-9827-0226b0de7547.png)

**Comment by PanderMusubi** [comment]
Listing the number of tags is not only beneficial for nodes but also for lines, polygons, etc.

**Comment by tyrasd** [comment]
implemented in #378
