### ISSUE TITLE
possible bug? querying newer edits include unexpected older data

### ISSUE THREAD

**Issue by govvin** [tyrasd/overpass-turbo#380]
I have this [query](http://overpass-turbo.eu/s/yvD) for checking possible Pokémon Go features added in the last two days that we'd like to review.

Mostly, it works as expected except that the result includes `type=multipolygon` features that's been edited years back, without any changes in the 2 day time frame.

**Comment by tyrasd** [comment]
I believe you forgot to put a `(newer:"{{date: 2 days}}")` filter in line 78 of your query.
