### ISSUE TITLE
What happens on "Save as GeoJSON"?

### ISSUE THREAD

**Issue by eigenwillig** [tyrasd/overpass-turbo#384]
Where in the code does the conversion from raw JSON to GeoJSON happen?

> Note that Overpass-API doesn't output geojson, it outputs a json representation of the osm node/way/relation data model. Overpass Turbo has some code that converts the osm data model to geojson.
--[source](https://help.openstreetmap.org/questions/63099/overpass-api-difference-between-manual-overpass-geojson-export-only-linestring-and-overpass-api-result)

**Comment by simon04** [comment]
Overpass Turbo uses [tyrasd/osmtogeojson](https://github.com/tyrasd/osmtogeojson) for the conversion from OSM to GeoJSON.

**Comment by simon04** [comment]
See https://www.overpass-api.de/command_line.html

As far as I understand, the whole idea of python-overpy is to parse the JSON output into Python objects to work with.
