### ISSUE TITLE
Why are you abusing me @tyrasd ? What language ? What mailing list for your country ? I hope Github will be taking action against you soon !

### ISSUE THREAD

**Issue by bismoy2013** [tyrasd/overpass-turbo#386]
Refer last comment : https://github.com/tyrasd/overpass-turbo/issues/164 

as explained above, this is getting much too much off-topic here. @bismoy2013: please use a more appropriate discussion platform. If you'd like to use OpenStreetMap, you could ask your questions on https://help.openstreetmap.org/ for example (a tip: try to phrase your question as concrete as possible and have someone look over your English – no offence, but there appears to be a bit of a language barrier involved). Or maybe is there even a local forum or mailing list for your country?

**Comment by HolgerJeromin** [comment]
This is an issue tracker for one software. No discussion or help forum.

The mentioned issue is three years old!

**Comment by bismoy2013** [comment]
There are certain things we shouldn't just let go of so easily especially when a person is racist and perhaps **abused and bullied** you online at one point of time. There are cases where it takes years to get justice and this is just a small issue tracker. Anyways closing this down , talking to Github folks meanwhile. This was just a small way of me protesting against this guy !

- Thanks
