### ISSUE TITLE
Query relation metadata

### ISSUE THREAD

**Issue by srividyacb** [tyrasd/overpass-turbo#388]
Not able to find version of relation when queried with `out meta qt;` in the query. Only seeing `node` and `way` metadata.

Is relation version exposed as metadata? What is the query syntax to get all the metadata ?

Sample Query - https://overpass-turbo.eu/s/AAx

![image](https://user-images.githubusercontent.com/3423533/43308948-e3bc4de6-91a0-11e8-8978-05952847ec4b.png)

**Comment by srividyacb** [comment]
@mmd-osm Tried adding `out meta` instead of `out body` and did not get the metadata 
[Overpass-link](https://overpass-turbo.eu/s/Bjk)

**Comment by srividyacb** [comment]
@mmd-osm the `Data` tab shows the output in xml. Is there a way I can get the metadata as a geojson output? I am not seeing it when I export the data to geojson format.
Snippet of the `@relations` array - [geojson-output](https://gist.github.com/srividyacb/ec7134f1bf9010a3d9c6ef8754fa9575)
```
"@relations": [
          {
            "role": "via",
            "rel": "7650670",
            "reltags": {
              "restriction": "no_u_turn",
              "type": "restriction"
            }
          }
        ]
```

**Comment by mmd-osm** [comment]
No idea what issue you’re trying to solve or why you need geojson. In any case this seems to be the wrong place to report this issue, as the osm to geojson conversion is in a different repo: https://github.com/tyrasd/osmtogeojson
