### ISSUE TITLE
How to make a custom node

### ISSUE THREAD

**Issue by Robot8A** [tyrasd/overpass-turbo#389]
Hi, I wanted to do something like this:
```
[out:json][timeout:25];
(
  node[amenity=drinking_water](around:1000,41.6830209,-0.8876301);
);

out body;
>;
out skel qt;

make node ::lat = 41.6830209, ::long = -0.8876301; out;

{{style:
  node[amenity=drinking_water] {
    icon-image: url('icons/osmic/drinking-water-18@2x.png');
    icon-width: 36;
  }
}}
```

I want to query the water taps around a node, and also represent that node. The make statement only lets you edit tags and id, but I also want to edit lat and long. Is this possible?

**Comment by mmd-osm** [comment]
The point evaluator can do this: https://wiki.openstreetmap.org/wiki/Overpass_API/Overpass_QL#Point_evaluator

```
make node  ::geom = pt(41.6830209, -0.8876301);
out geom;
```

**Comment by mnalis** [comment]
> The point evaluator can do this: https://wiki.openstreetmap.org/wiki/Overpass_API/Overpass_QL#Point_evaluator

Is that still supposed to work nowadays @mmd-osm ?

because when I try something like:

```
[out:json][timeout:25];
(
  make node ::geom = pt(43.347030,16.734881), "fixme" = "test";
  node(1706131803);
);
out geom;
```

that point evaluator creates something that is almost, but not quite, entirely _unlike_ regular `node`:

```
{
  "type": "node",
  "id": 5048395419,
  "lat": 43.3469560,
  "lon": 16.7345281,
  "tags": {
    "name": "Sanja",
    "shop": "convenience"
  }
},
{
  "type": "node",
  "id": 1,
  "geometry": {
    "type": "Point",
    "coordinates": [ 16.7348810, 43.3470300 ]
  },
  "tags": {
    "fixme": "test"
  }
}
```

and as such of course, does not display that made-up node on map at https://overpass-turbo.eu/

Whelp?

**Comment by mmd-osm** [comment]
The way you describe it is exactly how it has been working since 10 years or so. Overpass turbo never supported derived objects. There was some feature request which got closed.
