### ISSUE TITLE
One click export a.k.a. user export tool preference

### ISSUE THREAD

**Issue by ProBackup-nl** [tyrasd/overpass-turbo#390]
[enhancement][useability]

Because JOSM Download from Overpass API doesn't show where there are elements on the Slippy map, I do want to use Overpass-turbo to make queries, visualise, make selections and export to JOSM. 

Note: This all to do a massive (500+ cases for manual review) of wrongly tagged (bicycle=no) ways. One wrong road can easily consist of 100+ way segments.

The wish/feature request is to reduce 2 clicks to just 1 (times > 500):

 1. "Export"
 2. "JOSM"

When clicking "Export" I want to immediately export to my favourite tool.

I want to select my favourite tool in "Settings" > "Export".

**Comment by tyrasd** [comment]
Sorry for the late reply, but IMHO it would be the best if you were to use/build a specialized tool for this kind of quality-assurance tasks and/or think about a different workflow (e.g. using the [todo-list](https://wiki.openstreetmap.org/wiki/JOSM/Plugins/TODO_list) plugin could work?).
