### ISSUE TITLE
french server does not support time based queries

### ISSUE THREAD

**Issue by riccardoklinger** [tyrasd/overpass-turbo#395]
when using the french server https://overpass.openstreetmap.fr/api/ the time based queries return in an error:
![grafik](https://user-images.githubusercontent.com/7377897/45206841-61bdf180-b286-11e8-8ef1-fec7774b41db.png)
Same query 
`[out:json][timeout:25][date:"2018-08-01T07:53:24Z"];(node["shop"](52.37,13.63,52.38,13.65););(._;>;);out;>; `
 runs great on the //overpass-api.de/api/ server entry
![grafik](https://user-images.githubusercontent.com/7377897/45206857-6e424a00-b286-11e8-8a24-04a1cf472257.png)

**Comment by tilmanb** [comment]
Yes. They run a version of the overpass API that does not have attic data, as far as i know.

What should overpass-turbo do, in your opinion? Display an explicit popup when trying to run a time-based query against a known-non-attic-server?

**Comment by riccardoklinger** [comment]
if date provided, the gui should answer with a short warning and offer running the query with a recent time.

**Comment by mmd-osm** [comment]
There's currently no API call to find out if a server supports attic calls. However, I don't think it's a good idea to store this information outside of the actual server. So better open up a message for Overpass API to request a better error message (which is the root cause of the issue).

**Comment by tyrasd** [comment]
yeah, having a better error message returned from overpass-api would be the most important improvement for this issue.

> here's currently no API call to find out if a server supports attic calls.

theoretically, one could do a basic "preflight" request (on startup and when switching to a different server) like `[out:json];area(1);` to determine if the server supports areas (by looking at whether the overpass-api server returns an error or not). I believe that that wouldn't be a very elegant solution, though.

**Comment by tilmanb** [comment]
As of now, overpass api will return explicit error messages, see the linked issue in Overpass-API.
