### ISSUE TITLE
Map_to_area : only id with name

### ISSUE THREAD

**Issue by operon** [tyrasd/overpass-turbo#398]
I am trying to use the "map_to_area" function 
https://wiki.openstreetmap.org/wiki/Overpass_API/Overpass_QL#Map_way.2Frelation_to_area_.28map_to_area.29

I find that this function can only use items with a name. Is it a mistake ? will it be corrected soon?

**Comment by mmd-osm** [comment]
This behavior is intentional and documented on the page you linked:

> The Overpass API internal area creation job does not create an area for each and every way/relation in OSM. If an area does not exist for a given way/relation, map_to_area will simply skip this object without adding an area. Otherwise the area will be returned but with its geometry as it was when it was last created or updated by an internal background process on the Overpass server, and it may be different from the most recent geometry loaded from the way/relation element in the OSM database.

**Comment by operon** [comment]
Ok, that's not a mistake.

However, I do not understand why this difference of the zone with or without name.
I want use all area landuse=residential not only those with name.

you can close if it's just that I do not understand well overpass

Thanks for your reponse

**Comment by mmd-osm** [comment]
There are some rules which define how objects are transformed into areas. This is really all just by convention, nothing else.
