### ISSUE TITLE
Customized Styling of Map Features

### ISSUE THREAD

**Issue by Vanuan** [tyrasd/overpass-turbo#4]
Currently, nodes are shown as a blue circle. It would be great to be able to set a custom image for a marker. Probably, it's out of scope of overpass api, but still good to have for embed map service.

**Comment by pyrog** [comment]
> That said, I still think that the above mentioned features would provide great benefit even for "analyzing data".

Yes.

The example of changing the color of amenities is exactly what I need. 😀
See drolbr/Overpass-API/issues/517
