### ISSUE TITLE
Case insensitive query not possible via the wizard

### ISSUE THREAD

**Issue by pangoSE** [tyrasd/overpass-turbo#401]
Keyword seems to be missing.
Maybe a checkbox could be ticked to add ,i to all fields?

**Comment by pangoSE** [comment]
I found https://wiki.openstreetmap.org/wiki/Overpass_turbo/Wizard#Tag_Searches
There is a way to specify insensitive!
Maybe you could link to this page from the wizard or improve the hands-on documentation to match the one in the JOSM overpass dialog?

**Comment by tyrasd** [comment]
yes, case-insentitive regular expressions are possible

> Maybe you could link to this page from the wizard

It should already be linked from the wizard dialog. :)
