### ISSUE TITLE
Around misses certain POI?

### ISSUE THREAD

**Issue by VValore** [tyrasd/overpass-turbo#411]
I have a set of queries build with the "around" statement and in general they work very well!

I have three substations found by the following OT query:
```
[out:json][timeout:90];
(
  way["power"="substation"][operator="Radius Elnet"][ref=2474];
  way["power"="substation"][name="Damhus Boulevard"][ref=486];
  way["power"="substation"][operator="Radius Elnet"][ref=677];
);
out body; >; out skel qt;
```
First and second is 276 meters apart, second and thrid are 667 meters apart and third and first are 434 meters apart.

My problem is that i cannot get the around statement to find each other like in:
```
[out:json][timeout:90];
(
  way["power"="substation"][operator="Radius Elnet"][ref=2474];
);
complete
{ (
    node(around:800)["power"="substation"];
    way(around:800)["power"="substation"];
); }
out body; >; out skel qt;
```
If I change the distance in the around statements to 1200 meters, I will find an extensive net of more than 600 POI's, but it will not find the the two other nodes ref=486 and ref=677?

I find this spooky, can anyone offer an explanation or have I stumbled over a bug?

Thanks! /Victor

**Comment by mmd-osm** [comment]
First of all, this is really the wrong repo, your question has nothing to do with overpass turbo.

You need to use an explicit input set in your case, otherwise the first "node" statement will overwrite any temporary results.

```
[out:json][timeout:90];
(
  way["power"="substation"][operator="Radius Elnet"][ref=2474];
);
complete -> .a
{ (
    node(around.a:800)["power"="substation"];
    way(around.a:800)["power"="substation"];
  ); 
}

out center;
```
