### ISSUE TITLE
No Translation of Simplified Chinese

### ISSUE THREAD

**Issue by dorbodwolf** [tyrasd/overpass-turbo#414]
Simplified Chinese isn't currently in the translation list, can you add it to list?

best wishes

**Comment by IVAN-RSM** [comment]
I also requested to translate to Galician. Is there someone there who admits us?

**Comment by simon04** [comment]
Added via https://github.com/tyrasd/overpass-turbo/commit/9b003f0578660107cccef4142f958731cbf8871d.
