### ISSUE TITLE
Entity's pop-up not displaying meta data

### ISSUE THREAD

**Issue by DaveF63** [tyrasd/overpass-turbo#418]
Hi
Entity's pop-up not displaying meta data:
![image](https://user-images.githubusercontent.com/9528328/54851418-c819d700-4ce1-11e9-8177-d752d46169eb.png)

I thought the plan was to add info, not remove it: #278

(is this related to yesterday's outage? I'm using //overpass-api.de/api/)

**Comment by DaveF63** [comment]
Hi
Even if I'm completely misunderstanding the point, I'd appreciate a reply to explain why.

**Comment by simon04** [comment]
You might miss `out meta`. The following query displays the meta section:

```
node(3755670274);
out meta;
```
