### ISSUE TITLE
locate me button doesn't work.

### ISSUE THREAD

**Issue by sabamosleh** [tyrasd/overpass-turbo#419]
when i click locate me button,it shows no marker,and doesn't zoom on my location.

**Comment by HolgerJeromin** [comment]
Which browser and website did you tested?

**Comment by sabamosleh** [comment]
> Which browser and website did you tested?

http://overpass-turbo.eu
chrom

**Comment by HolgerJeromin** [comment]
The console has the explaining message:

> [Deprecation] getCurrentPosition() and watchPosition() no longer work on insecure origins. To use this feature, you should consider switching your application to a secure origin, such as HTTPS. See https://goo.gl/rStTGz for more details.

perhaps it is possible to add an user feedback at the `catch` line of code:
https://github.com/tyrasd/overpass-turbo/blob/c7ea2474b3120fa6f7e702f7014c632e45fbba01/js/ide.js#L564-L571

related #336

**Comment by HolgerJeromin** [comment]
I am pretty sure the current code does not work. See my PR #438 for a fix.
