### ISSUE TITLE
link to wikipedia

### ISSUE THREAD

**Issue by mrtngrsbch** [tyrasd/overpass-turbo#421]
Hi,
Sorry for a stupid question, but would it be possible to have a link to wikipedia [architect:wikipedia] (and others) in tagbox ?
see screenshot : ![00000362](https://user-images.githubusercontent.com/782446/65635745-3452fb80-dfe1-11e9-89d0-483779cdfb8d.png)

thanks a lot !

**Comment by simon04** [comment]
![Screenshot_2019-09-25 overpass turbo](https://user-images.githubusercontent.com/782446/65635860-73814c80-dfe1-11e9-8199-6d10ad544879.png)

**Comment by mrtngrsbch** [comment]
hi simon004,
this issue is deployed?
because...

![ScreenShot 2019-09-25 a la(s) 22 29 37](https://user-images.githubusercontent.com/693328/65651173-0622eb00-dfe4-11e9-9aaf-2dec31c1321e.jpg)

**Comment by mrtngrsbch** [comment]
![ScreenShot 2019-09-25 a la(s) 22 33 36](https://user-images.githubusercontent.com/693328/65651419-b7c21c00-dfe4-11e9-9958-66780c91aec6.jpg)

**Comment by simon04** [comment]
@tyrasd has deployed it at `Thu, 26 Sep 2019 16:08:47 GMT`
