### ISSUE TITLE
Saved Queries: delete button deleting wrong item

### ISSUE THREAD

**Issue by erickdeoliveiraleal** [tyrasd/overpass-turbo#426]
IF you have many item in the list, when you click on the button it points to the wrong item.
Steps to reproduce:
Save ~12 items
Scroll items and try to delete some item. The list scroll, but the the delete buttons not.

**Comment by camelCaseSucks** [comment]
I can confirm this issue. I can't delete anything that I have to scroll down to see.

**Comment by govvin** [comment]
I confirm this issue on Firefox 68.0.2

If yo have long list of queries, and resize the modal box, you get a long list of "x" buttons that don't pair up properly with the query.

![image](https://user-images.githubusercontent.com/5821688/63855851-ed1e1e80-c9d2-11e9-9403-321188173db5.png)
![image](https://user-images.githubusercontent.com/5821688/63855911-15a61880-c9d3-11e9-9d25-e0f5fc517211.png)

**Comment by andrewblack512** [comment]
I have seen this on a number of browsers.

**Comment by simon04** [comment]
![2020-01-07_22-38](https://user-images.githubusercontent.com/782446/71931668-87227e80-319e-11ea-9248-c9b727e9b69e.png)

**Comment by iriman** [comment]
Comparing with [this advice](https://stackoverflow.com/a/4605809) delete buttons are positioned `absolute`. By making `<li>`s' position `relative`, delete buttons also scroll simultaneously.

![image](https://user-images.githubusercontent.com/8467903/72454623-75f8f380-37d6-11ea-9f79-902ea3615483.png)

**Comment by erickdeoliveiraleal** [comment]
it is still a bug, please reopen

**Comment by camelCaseSucks** [comment]
The issue still exists but #452 appears to fix it. Just waiting for it to be merged.

**Comment by axd1967** [comment]
(Still an issue on https://overpass-turbo.eu/!)
