### ISSUE TITLE
 Attic Query template should include range

### ISSUE THREAD

**Issue by jidanni** [tyrasd/overpass-turbo#427]
I have an idea. For Attic Queries, please have the template the user sees instead of saying

```
/* This query loads all objects as of 2016-01-01 */
[date:"2016-01-01T00:00:00Z"];
```
just say
```
[start-date:"2016-01-01T00:00:00Z"];
[end-date:"2019-06-11T00:00:00Z"];
```
or even
```
[start-date:"2016-01-01T00:00:00Z"];
[end-date:"now"];
```

1. No more need for the comment to explain unfortunate syntax.
2. Enables a range.

**Comment by jidanni** [comment]
Furthermore,
```
/* This query loads all objects as of 2016-01-01 */
[date:"2016-01-01T00:00:00Z"];
```
means
'''all objects created after 2016-01-01" to some people,
and
 ''all objects created before 2016-01-01" to other people,

**Comment by mmd-osm** [comment]
It makes absolutely no sense to create a template with [start-date] or [end-date], because that's simply invalid Overpass QL syntax.

As of 2016-01-01 means: this is how the database looked like when running the query at said point in time.

**Comment by jidanni** [comment]
OK, then please change the comment to

/* This query loads all objects **that existed on 2016-01-01 or before** */
[date:"2016-01-01T00:00:00Z"];

to make it clearer. Thanks.

Also wouldn't it be great to extend the syntax of the underlying system to enable time range [X..Y] queries instead of just [0..Y]?

**Comment by mmd-osm** [comment]
What should be the result of such a time range query?

**Comment by mmd-osm** [comment]
`[date:"2016-01-01T00:00:00Z"];` is a point in time query (not a [0..Y] style of query), hence the query will only return object versions which existed and were visible at the given point in time! Notice that object and object version are fundamentally different things.

Time ranges are already supported via `[diff:timestamp1, timestamp2];` and `[adiff:timestamp1, timestamp2];`, but I don't know if this is what you want. What should be the result of such a time range query?
