### ISSUE TITLE
Add 'view on OSM' link

### ISSUE THREAD

**Issue by jidanni** [tyrasd/overpass-turbo#428]
1. Go to http://overpass-turbo.eu/ .
2. Zoom and pan to your favorite breakfast spot.
3. Now suddenly have the urge to see the same spot on https://www.openstreetmap.org/

There should be a link somewhere on the screen to click.

**Comment by mmd-osm** [comment]
That's already available under:

export --> map --> current map view (bbox, center, etc.) --> to osm.org

**Comment by axd1967** [comment]
confirmed
