### ISSUE TITLE
A polygon is counted as a line in the "Displayed" summary

### ISSUE THREAD

**Issue by zstadler** [tyrasd/overpass-turbo#431]
[Way 661707153](https://www.openstreetmap.org/way/661707153#map=19/43.53524/16.44440) is a closed rectangle.

However, in the "Displayed" summary of the [Overpass-Turbo query](http://overpass-turbo.eu/s/L1i), it shows as a line, rather than a polygon:

![image](https://user-images.githubusercontent.com/1304610/61785545-9726eb80-ae14-11e9-9100-88bf6eb3eb8f.png)

**Comment by mmd-osm** [comment]
This way does not have any tags which would qualify it as a polygon, hence it's a way.

Rules are described here: https://wiki.openstreetmap.org/wiki/Overpass_turbo/Polygon_Features

**Comment by zstadler** [comment]
Thanks for reminding me!
