### ISSUE TITLE
New wizard for newbies

### ISSUE THREAD

**Issue by yopaseopor** [tyrasd/overpass-turbo#432]
Using all kinds of geoengines searchers I have realized the only one who works "always" is Overpass-turbo. 
For this reason I wish the improvement of the wizard section with:
1-possibility of searching three fields to search nodes, ways and relations
2-possibility of searching keys via iD predictives presets translations or something like that
3- possibility of searching by well-defined zones in OSM data-base, like OSMCha does.

**Comment by simon04** [comment]
1. Use `type:node`, `type:way`, `type:relation` in the wizard
2. This is already supported, see the "Drinking Water" example
3. This is already supported, see the "tourism=museum in Vienna" example

https://wiki.openstreetmap.org/wiki/Overpass_turbo/Wizard shows all supported queries/keywords.
