### ISSUE TITLE
Unsuported regex

### ISSUE THREAD

**Issue by pyrog** [tyrasd/overpass-turbo#437]
I want to use positive or negative lookahead.
HI,

I seem that it not yet supported.

For example, I want to find wrong values of wikimedia pictures (not started with `File:` or `Category:`)
```regex
wikimedia_commons~/^(?!(Category|File):).*/i
```

result: `static error: Invalid regular expression: "^(?!(Category|File):).*"`

I could use `wikimedia_commons~/http/` but I loose values like `1524488623511.jpg`

BR,

—
Yves

PS: JOSM accept `wikimedia_commons="^(?!(Category|File):).*"` with regex selected

**Comment by mmd-osm** [comment]
That's correct, positive and negative lookahead are not supported by Overpass API at this time (by the way, this is unrelated to overpass turbo).

**Comment by pyrog** [comment]
Thanks @mmd-osm and @simon04 😄

**Comment by mmd-osm** [comment]
@pyrog : can you close this issue, then? There's nothing to be done from overpass turbo side.

**Comment by pyrog** [comment]
@tyrasd You're welcome 😄 

Note: There is an open issue in the API: https://github.com/drolbr/Overpass-API/issues/146
