### ISSUE TITLE
Saved Queries: resizing 'load' window does not resize contents

### ISSUE THREAD

**Issue by camelCaseSucks** [tyrasd/overpass-turbo#439]
Clicking the load button opens a window containing lists of queries. The window can be resized, but the list of queries within remains the same size. This makes users unable to view more queries at once than can fit in the default window size.

**Comment by voschix** [comment]
Confirm this. And would like to underline that this also impedes saving more than 5 searches, and if you saved more than five, it makes it impossible to delete any but the first fives.

**Comment by simon04** [comment]
Would you please share a screenshot and specify which browser you are using.

On Firefox 72, I can scroll as well as resize the dialog:
![Screenshot_2020-01-07 overpass turbo](https://user-images.githubusercontent.com/782446/71930300-aa97fa00-319b-11ea-841a-120c2d976ed7.png)![Screenshot_2020-01-07 overpass turbo(1)](https://user-images.githubusercontent.com/782446/71930315-b2579e80-319b-11ea-87b9-6b3f7a769c56.png)

**Comment by simon04** [comment]
Relates to and/or duplicates #426

**Comment by voschix** [comment]
Yes, sure, it's the same thing. I apparently had not spotted #426 .
I actually had discovered it by loosing queries.

**Comment by tguen** [comment]
Firefox 71

![overpass-turbo-2](https://user-images.githubusercontent.com/57420975/71935831-abf60200-315c-11ea-9dba-644b64d94d54.png)

I expanded the window, which made a big empty space at the bottom (red), but didn't expand the list inside of the window, so I still have to scroll to see all of my queries (blue).

Here's what I'd expect it to look like:

![overpass-turbo-4](https://user-images.githubusercontent.com/57420975/71936518-8a961580-315e-11ea-992b-71fd76e617c2.png)

**Comment by erickdeoliveiraleal** [comment]
this pull request solves this: https://github.com/tyrasd/overpass-turbo/pull/452

**Comment by camelCaseSucks** [comment]
The issue still exists.

#452 appears to fix #426 which is a separate issue as I explained in my last post.

**Comment by camelCaseSucks** [comment]
The issue still exists.

#452 appears to fix #426 which is a separate issue.

**Comment by simon04** [comment]
The UI has received a modernisation since the PR has been opened (#458). Please test the latest version at https://tyrasd.github.io/overpass-turbo/

**Comment by erickdeoliveiraleal** [comment]
> The UI has received a modernisation since the PR has been opened (#458). Please test the latest version at https://tyrasd.github.io/overpass-turbo/

The saved queries before the modernisation was lost? My saved queries are not appearing :/

**Comment by simon04** [comment]
Different installation, different hostname, different settings. This is how browsers work. Nothing is lost, but only accessible from the URL where they have been saved.

**Comment by erickdeoliveiraleal** [comment]
> Different installation, different hostname, different settings. This is how browsers work. Nothing is lost, but only accessible from the URL where they have been saved.

sorry, I checked it it now :D

**Comment by camelCaseSucks** [comment]
The new version looks excellent. Any idea when it will be at overpass-turbo.eu?

**Comment by simon04** [comment]
Unfortunately no, see my attempts https://github.com/tyrasd/overpass-turbo/pull/458#issuecomment-626325583, https://github.com/tyrasd/overpass-turbo/pull/458#issuecomment-636163703, https://github.com/tyrasd/overpass-turbo/pull/458#issuecomment-683964127.

**Comment by tyrasd** [comment]
the deployed version has received the fixes by now.
