### ISSUE TITLE
Invalid MapCSS makes page unusable.

### ISSUE THREAD

**Issue by doublah** [tyrasd/overpass-turbo#445]
Page currently gets stuck unusable like this loading forever.

![firefox_iC8TbDRZBd](https://user-images.githubusercontent.com/11699874/68081734-a1408900-fe0a-11e9-87a3-20ad672f3b04.png)

**Comment by simon04** [comment]
Please share your query / MapCSS code. I cannot reproduce with manually crafted MapCSS errors.
