### ISSUE TITLE
Add link to multi values wikidata

### ISSUE THREAD

**Issue by pyrog** [tyrasd/overpass-turbo#447]
Hi Martin,

Links are not added for tags with separated values:
* [subject:wikidata=Q5353941;Q4785593;Q5069788](https://overpass-turbo.eu/s/OSd)
* [wikidata=Q65936653;Q65936655;Q65936658](https://overpass-turbo.eu/s/OSf)

OpenStreetMap render them for `subject:wikidata` (see [n6388256631](https://www.openstreetmap.org/node/6388256631))…
… but not (yet) for `wikidata` (see [w715606073](https://www.openstreetmap.org/way/715606073)).

Best regards,

—
Yves

**Comment by pyrog** [comment]
Thank you Simon for your fixe 😄 
Is it already online ? The 2 examples above don't work.

**Comment by simon04** [comment]
Not yet. @tyrasd, would you deploy the new version. Thanks!

**Comment by pyrog** [comment]
Thank you ❤️
