### ISSUE TITLE
Why tag with number cannot be loaded

### ISSUE THREAD

**Issue by MASangys** [tyrasd/overpass-turbo#448]
I try to input this query:

/*
This query looks for nodes, ways and relations 
with the given key.
Choose your region and hit the Run button above!
*/
[out:json][timeout:25];
// gather results
(
  // query part for: “brand=*”
  node[brand=99 Speedmart]({{bbox}});
  way[brand=99 Speedmart]({{bbox}});
  relation[brand=99 Speedmart]({{bbox}});
);
// print results
out body;
>;
out skel qt;

but it cannot be complete and show this message:
Error: line 10: parse error: ']' expected - 'Speedmart' found.

Error: line 11: parse error: ']' expected - 'Speedmart' found.

Error: line 12: parse error: ']' expected - 'Speedmart' found.

Can somebody fix it?

**Comment by stephan75** [comment]
Try "99 Speedmart" ... That means with these "" characters

**Comment by MASangys** [comment]
still cannot, can somebody figure out what is the problem. I thibk is because of number “99”, because when I use Shell as brand it works nicely..

**Comment by stephan75** [comment]
Please quote your query code here again, and use the text styling from github for code quoting.

**Comment by MASangys** [comment]
> /*
This query looks for nodes, ways and relations 
with the given key.
Choose your region and hit the Run button above!
*/
[out:json][timeout:25];
// gather results
(
  // query part for: “brand=*”
  node[brand=“99 Speedmart”]({{bbox}});
  way[brand=“99 Speedmart”]({{bbox}});
  relation[brand=“99 Speedmart”]({{bbox}});
);
// print results
out body;
>;
out skel qt;

>

**Comment by stephan75** [comment]
works for me:
```

/*
This has been generated by the overpass-turbo wizard.
The original search was:
“brand="99 Speedmart"”
*/
[out:json][timeout:25];
// gather results
(
  // query part for: “brand="99 Speedmart"”
  node["brand"="99 Speedmart"]({{bbox}});
  way["brand"="99 Speedmart"]({{bbox}});
  relation["brand"="99 Speedmart"]({{bbox}});
);
// print results
out body;
>;
out skel qt;
```

... with real results in Malaysia.

**Comment by MASangys** [comment]
Thank you so much
