### ISSUE TITLE
Cities being shown in Wrong Countries

### ISSUE THREAD

**Issue by GIS243** [tyrasd/overpass-turbo#454]
HI 

I am trying to download the cites with population greater than 50,000 from the following link https://overpass-turbo.eu/
but I  am getting the issue that some of the issues are shown in the wrong countries.

Please why I am getting this issue and how to correct this. 
![f339ca55-8d9c-4f0c-8ace-4d5b1ff74f65](https://user-images.githubusercontent.com/54910955/76029910-58592800-5f03-11ea-8c84-bf1357f66443.jpg)

**Comment by mmd-osm** [comment]
Actual query is missing, issue cannot be reproduced.

**Comment by GIS243** [comment]
Hi Thanks, this is the query Please 

**[out:json];
node
[place=city](if:t["population"]>50000);
out geom;**

**Comment by simon04** [comment]
This data originates from the OpenStreetMap object, e.g., https://www.openstreetmap.org/node/71556493
You have to fix the data on OpenStreetMap. This issue is not related to Overpass API nor overpass-turbo.

**Comment by mmd-osm** [comment]
You should also read this blog post how to do numerous comparisons the correct way: https://dev.overpass-api.de/blog/numbers.html
