### ISSUE TITLE
Can't search for an area within an area

### ISSUE THREAD

**Issue by camelCaseSucks** [tyrasd/overpass-turbo#466]
```
area[name=Oregon]->.state;
area(area.state)[name="Washington County"]->.county;

(
  node(area.county)[amenity=library];
  way(area.county)[amenity=library];
  rel(area.county)[amenity=library];
);

out;
>;
out skel qt;
```

I'm trying to search for all libraries in Washington County, Oregon. The first line searches for Oregon and the second is intended to find Washington County within Oregon. Instead it finds *all* areas named "Washington County". Is this a bug or am I doing something wrong?

**Comment by simon04** [comment]
I don't think nested searches are supported.

The simplest solution would be to combine the name query to "Washington County, Oregon", e.g. run the wizard on `amenity=library in "Washington County, Oregon"`

**Comment by camelCaseSucks** [comment]
I see now that [area(area) is not supported.](https://wiki.openstreetmap.org/wiki/Overpass_API/Overpass_QL#By_area_.28area.29)

 > combine the name query to "Washington County, Oregon"

How do I do that? With `area[name="Washington County, Oregon"]->.county;` I get no results, and `is_in` is no longer used.

**Comment by simon04** [comment]
Use the [Overpass turbo/Wizard](https://wiki.openstreetmap.org/wiki/Overpass_turbo/Wizard) with `amenity=library in "Washington County, Oregon"`
