### ISSUE TITLE
Wrong parsing of block comments in script

### ISSUE THREAD

**Issue by mikkolukas** [tyrasd/overpass-turbo#469]
In [Overpass_QL#Comments](https://wiki.openstreetmap.org/wiki/Overpass_API/Overpass_QL#Comments) it is documented that I can use block "comments in the same style of C, C++, Javascript, or CSS source code"

It works if I use:
```
/*
*/
```

However, contrary to other languages, if I do:
```
/**
**/
```
The rest of the script is ignored and I get no output.

If it is intended behavior, the wiki should be amended with that information so other users don't waste several hours.

Also posted at: [Talk:Overpass_turbo#Wrong_parsing_of_comments](https://wiki.openstreetmap.org/wiki/Talk:Overpass_turbo#Wrong_parsing_of_comments)

**Comment by mmd-osm** [comment]
overpass turbo is the wrong repo, this needs to go to [Overpass API](https://github.com/drolbr/Overpass-API).

**Comment by mikkolukas** [comment]
Thanks again for heads up 👍 :)
Have reposted it at https://github.com/drolbr/Overpass-API/issues/586
