### ISSUE TITLE
Unexpected behavior on recurse up relations (<<)

### ISSUE THREAD

**Issue by mikkolukas** [tyrasd/overpass-turbo#470]
I have added a "Be aware" with testing examples at [Overpass_QL#Recurse_up_relations_(<<)](https://wiki.openstreetmap.org/wiki/Overpass_API/Overpass_QL#Recurse_up_relations_.28.3C.3C.29), as I believe we going to live with this behavior:

> Done on a node or a way, it will return the parents of that node or way (as expected).
> Done on a relation, it will return both the relation itself and it's parents.
> If you want the parents only, you can do: `(<<; - rel._;);` instead.

This bug cannot be fixed without breaking the now expected functionality of thousands of scripts, but I believe it is important that the developer is made aware of the issue.

Also posted at: [Talk:Overpass_turbo#Unexpected_behavior_on_recurse_up_relations__(<<)](https://wiki.openstreetmap.org/wiki/Talk:Overpass_turbo#Unexpected_behavior_on_recurse_up_relations_.28.3C.3C.29)

**Comment by mikkolukas** [comment]
> This issue doesn't belong on the overpass turbo repo, really.

Why not?
And if so, where does it belong so I can report it correctly?

**Comment by mmd-osm** [comment]
overpass turbo is a web frontend, and has nothing to do with those recuse up relation operations.

Proper repository is the Overpass API repository (database backend): https://github.com/drolbr/Overpass-API/issues

**Comment by mikkolukas** [comment]
oh of course, I didn't notice the distinction that it was split into two projects.
I have reposted it at: https://github.com/drolbr/Overpass-API/issues/585

Thanks for the heads up! 👍 :)
