### ISSUE TITLE
'Copy this link to share the current code:' ?

### ISSUE THREAD

**Issue by DaveF63** [tyrasd/overpass-turbo#472]
Hi
What is the hyperlink in 'Copy this link to share the current code:' meant to achieve? All it does on my Win7/Firefox/Chrome latest set up is to reload the tab. 

Could it be upgraded to copy the shortcut to the clipboard? 

![image](https://user-images.githubusercontent.com/9528328/84391936-8e3c3580-abf1-11ea-8af4-0b6f30cbb43e.png)

**Comment by mmd-osm** [comment]
Just right click on the link and from the popup menu, copy it to your clipboard.
