### ISSUE TITLE
Overpass query  provinces of Costa Rica also returns Panama province

### ISSUE THREAD

**Issue by schweini** [tyrasd/overpass-turbo#474]
I ran the this query to obtain the provinces of Costa Rica, and it returns the province of "Chiriquí" of Panama,.
I don't think it's a OSM data bug, because nowhere in the nodes of Panama's province it says anything about Costa Rica.

If I use the (undefined) admin_levels 3,2 or 1, the whole of Panama is returned, which is even wronger.
Direct link to query 
http://overpass-turbo.eu/s/V9S
Query:
```
/*
This has been generated by the overpass-turbo wizard.
The original search was:
“admin_level=2 in "Costa Rica"”
*/
[out:json][timeout:25];
// fetch area “Costa Rica” to search in
{{geocodeArea:Costa Rica}}->.searchArea;
// gather results
(
  // query part for: “admin_level=4”
  node["admin_level"="4"](area.searchArea);
  way["admin_level"="4"](area.searchArea);
  relation["admin_level"="4"](area.searchArea);
);
// print results
out body;
>;
out skel qt;
```

**Comment by mmd-osm** [comment]
One of the two production server has some issues with areas at this time. This issue has already been reported.
Here's the result on the server with up-to-date areas:

![x4g](https://user-images.githubusercontent.com/5842757/88464979-50ece800-cebf-11ea-9dae-21c5c9bec6d1.png)

**Comment by schweini** [comment]
Thanks for the answer. Sorry if it was already reported - I couldn't find any previous mentions of this issue.

Is there an ETA on when the updates are deployed to the production servers?

**Comment by mmd-osm** [comment]
Unfortunately, I don't have an ETA.. I used the following server for this screenshot: `//lz4.overpass-api.de/api/`

**Comment by schweini** [comment]
That URL just gives me a "Forbidden" error message. :-(

**Comment by mmd-osm** [comment]
Did you copy that string into overpass turbo -> Settings -> General Settings -> Server?

**Comment by schweini** [comment]
Now that I did, it works! Thanks!

There's a another issue in CR, but i don't know if it is an OSM or OverPass thing:
In Costa Rica, there is a special case of "Parrita": it is one 'canton' (admin level 6) and ALSO an identical 'distrito' (admin level 8).
In Overpass, it shows up correctly at admin level 6, but at admin level 8 it is blank/not returned.
I already reported it as a map error in OSM, to no avail - but as I said: I am not sure if it is an OSM data issue, or an Overpass rendering issue.

The Overpass query that does not return the 'distrito' is here (look at the middle-central-western part):
http://overpass-turbo.eu/s/WsE

```/*
This has been generated by the overpass-turbo wizard.
The original search was:
“admin_level=2 in "Costa Rica"”
*/
[out:json][timeout:25];
// fetch area “Costa Rica” to search in
{{geocodeArea:Costa Rica}}->.searchArea;
// gather results
(
  // query part for: “admin_level=5”
  node["admin_level"="8"](area.searchArea);
  way["admin_level"="8"](area.searchArea);
  relation["admin_level"="8"](area.searchArea);
);
// print results
out body;
>;
out skel qt;```

The Overpass query that returns the correct 'canton' is here:
http://overpass-turbo.eu/s/WsF

```/*
This has been generated by the overpass-turbo wizard.
The original search was:
“admin_level=2 in "Costa Rica"”
*/
[out:json][timeout:25];
// fetch area “Costa Rica” to search in
{{geocodeArea:Costa Rica}}->.searchArea;
// gather results
(
  // query part for: “admin_level=5”
  node["admin_level"="6"](area.searchArea);
  way["admin_level"="6"](area.searchArea);
  relation["admin_level"="6"](area.searchArea);
);
// print results
out body;
>;
out skel qt;```

**Comment by mmd-osm** [comment]
https://www.openstreetmap.org/relation/11151141 only refers to existing an existing relation, rather than including some ways. Unfortunately this is not supported by Overpass as the relation does not have any geometry information on its own.

**Comment by mmd-osm** [comment]
Areas have been refreshed, you can close this issue now if there are no further topics.

**Comment by schweini** [comment]
Confirmed working as expected now.
Thanks!
