### ISSUE TITLE
Two missing traffic signals in Revere, MA, USA

### ISSUE THREAD

**Issue by JayJacksonNH** [tyrasd/overpass-turbo#488]
The Intersection query is missing a signalized intersection at the corner of Broadway/Yeamans Street, Revere, MA, USA
42.408207, -71.013546

See image from [google maps](https://www.google.com/maps/@42.4080596,-71.013593,3a,75y,29.65h,90t/data=!3m7!1e1!3m5!1sJk5gZYWAxwKf3YxghslDMA!2e0!6s%2F%2Fgeo0.ggpht.com%2Fcbk%3Fpanoid%3DJk5gZYWAxwKf3YxghslDMA%26output%3Dthumbnail%26cb_client%3Dmaps_sv.tactile.gps%26thumb%3D2%26w%3D203%26h%3D100%26yaw%3D22.797981%26pitch%3D0%26thumbfov%3D100!7i16384!8i8192):

2nd intersection: Broadway @ Cushman & School
42.414669, -71.009402

See image from [Google Maps](https://www.google.com/maps/@42.4145708,-71.009491,3a,75y,59.76h,96.22t/data=!3m7!1e1!3m5!1s-MAaZReOXHOrhisQBBxSGA!2e0!6s%2F%2Fgeo2.ggpht.com%2Fcbk%3Fpanoid%3D-MAaZReOXHOrhisQBBxSGA%26output%3Dthumbnail%26cb_client%3Dmaps_sv.tactile.gps%26thumb%3D2%26w%3D203%26h%3D100%26yaw%3D71.03061%26pitch%3D0%26thumbfov%3D100!7i16384!8i8192)

Thanks!

**Comment by mmd-osm** [comment]
We don't know what you mean by "The intersection query".
