### ISSUE TITLE
Add Clear / Reset button

### ISSUE THREAD

**Issue by jidanni** [tyrasd/overpass-turbo#489]
Add a clear or reset button.
It would do the same as
$BROWSER -incognito http://overpass-turbo.eu/
(I.e., just like we visited the site for the first time.)
(Except perhaps not moving the location to Roma.)

**Comment by mmd-osm** [comment]
What is the original problem you're trying to solve here?

**Comment by jidanni** [comment]
The problem is the user, after playing around for a while, has
```
/*
This has been generated by the overpass-turbo wizard.
The original search was:
“addr:city”
*/
[out:json][timeout:25];
// gather results
nwr["addr"~"city"]({{bbox}});
// print results
out geom;
```
on their screen and wants to start fresh.

OK. They close their browser window,
and then go browse
https://overpass-turbo.eu/
again.

But even that is not enough to get the window back to the pristine default starting state.


OK, now they use a incognito window, or delete all their cookies, and finally they are back to the beginning state:
```
/*
This is an example Overpass query.
Try it out by pressing the Run button above!
You can find more examples with the Load tool.
*/
node
  [amenity=drinking_water]
  ({{bbox}});
out;
```
I am sorry it took four years for me to respond. I suppose it was due to blocks causing me not to get notified.

**Comment by jidanni** [comment]
OK, perhaps a workaround is:
1. Click on the left panel (where we type our queries.)
2. CTRL+A (highlight all)
3. DEL

Now we can start fresh, typing or pasting our new query.
