### ISSUE TITLE
Warn that bbox will have no effect if relation numbers are given

### ISSUE THREAD

**Issue by jidanni** [tyrasd/overpass-turbo#490]
Maybe a warning should be issued upon being given
```
// gather results
(
  relation(389884)(-25.15274327485494,-59.32891845703125,-24.382124181118236,-58.02703857421875);
);
```
as the bbox will have no effect if relation numbers are given.

(The user needs to do [this](https://help.openstreetmap.org/questions/56810/overpass-turbo-bbox-reducing-amount-of-data-for-a-relation-with-many-ways?) instead if he wants "just a part of a relation.")

**Comment by mmd-osm** [comment]
Your query will return the whole relation 389884, some part of it lies within the boundary box you have given. This is exactly the way this is supposed to work. See https://wiki.openstreetmap.org/wiki/Overpass_API/Overpass_QL#Bounding_box
Note that the way this query is written, it is **not** suited to only return a small part of the relation. 
If you want that, use something like the following instead:

relation(389884);way(r);out geom(-25.15274327485494,-59.32891845703125,-24.382124181118236,-58.02703857421875);

No need to do anything on overpass turbo side.
