### ISSUE TITLE
Feature request: time ellapsed for last query

### ISSUE THREAD

**Issue by Binnette** [tyrasd/overpass-turbo#491]
Hi, when the query is completed, I would like to kwow the total time taken by my query.

I'm thinking about something like so:
![image](https://user-images.githubusercontent.com/6597721/96788752-45dd2180-13f4-11eb-9850-6ade79d04f5b.png)

Until now, i'm using my web browser debugger tool to have this info, but it is a bit annoying and not user friendly.

BTW, i always try to optimize the queries that I use often.

Have a nice day.

**Comment by simon04** [comment]
![2020-10-23-214823](https://user-images.githubusercontent.com/782446/97047893-ee68be00-1579-11eb-9a42-9f059e18d4c7.png)

**Comment by Binnette** [comment]
This is just perfect! Thanks a lot @simon04 :heart: :rocket:
