### ISSUE TITLE
Use https instead http for the link to OSM 

### ISSUE THREAD

**Issue by GeorgV** [tyrasd/overpass-turbo#492]
<img width="273" alt="Bildschirmfoto 2020-10-23 um 18 32 34" src="https://user-images.githubusercontent.com/1186956/97029825-3da0f580-155e-11eb-8aee-3784862c7945.png">
all links on this popup use the protocol http zu the osm pages. Please switch zu https.

**Comment by simon04** [comment]
Only when you're using http://overpass-turbo.eu/ (via HTTP), overpass-turbo does not specify HTTP/HTTPS for those links, see https://github.com/tyrasd/overpass-turbo/blob/c78c107622266ed14a4be97b5683302f8a42f7aa/js/overpass.js#L841-L854
