### ISSUE TITLE
Add 'Export to XLSX' Function

### ISSUE THREAD

**Issue by chnuessli** [tyrasd/overpass-turbo#493]
Hi there,
For Data Export in a format where everybody is used to , i think we should make a function to export an .xlsx
Maybe we can write a little converter in the background that converts .json data to .xslx

**Comment by chnuessli** [comment]
https://medium.com/better-programming/convert-json-to-xlsx-file-in-javascript-e7611a975916

Maybe something like this?

**Comment by mmd-osm** [comment]
Why don't you use CSV output in your query and import that in Excel? Works just fine here.

**Comment by chnuessli** [comment]
Yeah this is working fine. I thought we could make something for non experienced users with csv. Or do you think if you can handle overpass, you should be able to handle csv? If yes, feel free to close the issue, that's okay for me.

**Comment by mmd-osm** [comment]
I assume you need some kind of mapping to get from JSON to XSLX which probably isn't trivial to write.

With the built in csv output, you can control exactly the which fields are returned and leave out all the rest. Easy importing of OSM data into XSLX was exactly one of the reasons why we have this output mode in the first place.

There's some pretty extensive documentation on how to generate CSV output, including examples. That should be good enough to get started: https://wiki.openstreetmap.org/wiki/Overpass_API/Overpass_QL#CSV_output_mode

**Comment by chnuessli** [comment]
Thank you @mmd-osm 
I close this issue.
