### ISSUE TITLE
{{geocodeArea:*}} ISO_3166-2:GB

### ISSUE THREAD

**Issue by UKChris-osm** [tyrasd/overpass-turbo#502]
I just tried performing an OverpassTurbo query with the following `{{geocodeArea}}:` using [ISO_3166-2:GB](https://en.wikipedia.org/wiki/ISO_3166-2:GB) values:

`(
  {{geocodeArea:gb-eng}};
  {{geocodeArea:gb-wls}};
  {{geocodeArea:gb-sct}};
)->.searchArea;`

... and found that "_gb-eng_" (England) worked fine, but that "_gb-wls_" (Wales) returned an error, and that "_gb-sct_" (Scotland) didn't return an error, but also didn't match any results in Scotland.

Would this be because "_Nominatim_" doesn't fully support [ISO_3166-2:GB](https://en.wikipedia.org/wiki/ISO_3166-2:GB) or the Overpass API itself? Or maybe both?

**Comment by simon04** [comment]
Nominatim.

`geocodeArea` is specific to overpass-turbo. It executes the Nominatim query https://nominatim.openstreetmap.org/search?X-Requested-With=overpass-turbo&format=json&q=gb-eng and replaces `{{geocodeArea:gb-eng}}->.searchArea;` with `area(3600058447)->.searchArea;` (relation ID 58447 + 3.6e9 offset for relations)

For gb-wls, Nominatim does not return a result: https://nominatim.openstreetmap.org/search?X-Requested-With=overpass-turbo&format=json&q=gb-wls

**Comment by UKChris-osm** [comment]
Thank you @simon04 👍
