### ISSUE TITLE
How to colorize nodes differently?

### ISSUE THREAD

**Issue by cgringmuth** [tyrasd/overpass-turbo#504]
Hello, is it possible to colorize nodes differently? Following I posted a sample code. 

```
[out:json][timeout:25];

way(275873801);
node(w)->.a;
.a out body;

way(24364447);
node(w)->.b;
.b out body;

{{style:
node.a { color:blue; fill-color:blue; }
node.b { color:red; fill-color:red; }
}}

//out skel qt;
```

As following example I want a different color for set a then for set b. Is this possible?

**Comment by simon04** [comment]
The response from the Overpass API no longer contains references to `.a` or `.b`, thus, overpass-turbo cannot differentiate. See this comment for a more detailed explaination: https://github.com/tyrasd/overpass-turbo/issues/499#issuecomment-756927476

**Comment by DaveF63** [comment]
I don't see how #499 relates to this query as #499 still "contains references to" to the sets.
