### ISSUE TITLE
Copy query misses styles

### ISSUE THREAD

**Issue by jidanni** [tyrasd/overpass-turbo#509]
The style, clearly present, is not included when copying the query.
![20210509T044346](https://user-images.githubusercontent.com/1230959/117552972-4a5fe380-b081-11eb-8cd4-efe89a210f6e.jpg)
Or add a checkbox: include styles.

**Comment by simon04** [comment]
The style is only missing in the standalone query. Please read its tooltip "For direct use with the Overpass API, has expanded shortcuts and doesn't include additional overpass turbo features such as MapCSS."
