### ISSUE TITLE
Style text cannot be appended to

### ISSUE THREAD

**Issue by jidanni** [tyrasd/overpass-turbo#515]
Let's say the user desperately wants to append text elements together, 
```
{{style:
node {
    text: addr:housenumber;
    text: addr:unit;
  }
}}
```
or even glue a "Not " on front, and "!" on back.

Well there is no way. Despite [talk](https://wiki.openstreetmap.org/wiki/Talk:Overpass_turbo/MapCSS#Support_for_string_functions_.3F) about it.

**Comment by simon04** [comment]
I've added an example to the documentation: https://wiki.openstreetmap.org/w/index.php?title=Overpass_turbo/MapCSS&diff=2192733&oldid=2151049
