### ISSUE TITLE
"Teilen -  Aktuelle Kartenansicht mitgeben" does not work properly

### ISSUE THREAD

**Issue by rdorsch** [tyrasd/overpass-turbo#520]
Hello,

I just found overpass-turbo and I think it is very useful, many thanks.

I tested with Firefox 78.10.0.esr on Debian Linux and found a minor issue:
If I deselect "Teilen -  Aktuelle Kartenansicht mitgeben", I still do not get the search for my current view (bbox), but for the view I had when I created the bookmark.

When I use the link in chromium, it is even worse I get a bbox for the Piazza del Colosseo in Roma!

Not sure if I misunderstood the feature though.

What I was looking for:
Zoom to a map view (bbox) and then load the bookmarks to get different card features (e.g. bbq area, playground, drinking water, etc)

Thanks
Rainer

**Comment by simon04** [comment]
> I still do not get the search for my current view (bbox), but for the view I had when I created the bookmark.

This is the expected behaviour.

> What I was looking for

You might want to use permalinks without the "Aktuelle Kartenansicht mitgeben" or use the save/load capabilities of overpass-turbo.

**Comment by rdorsch** [comment]
What is "Aktuelle Kartenansicht mitgeben" actually doing? I do not see a difference between having this option selected or not selected. I also enabled "Geteilte Abfrage sofort beim Öffnen ausführen".

**Comment by simon04** [comment]
"Aktuelle Kartenansicht mitgeben" adds the current location to the generated URL. When opening this URL, the map is shown for this location.

Try opening the following URLs in a [private window](https://support.mozilla.org/en-US/kb/private-browsing-use-firefox-without-history): 

* https://tyrasd.github.io/overpass-turbo/?Q=node%0A%20%20%5Bamenity%3Ddrinking_water%5D%0A%20%20(%7B%7Bbbox%7D%7D)%3B%0Aout%3B (generated without "Aktuelle Kartenansicht mitgeben")
* https://tyrasd.github.io/overpass-turbo/?Q=node%0A%20%20%5Bamenity%3Ddrinking_water%5D%0A%20%20(%7B%7Bbbox%7D%7D)%3B%0Aout%3B&C=48.12542;16.37581;12 (generated with the "Aktuelle Kartenansicht mitgeben")
