### ISSUE TITLE
Sharing a permalink no longer produces a short link

### ISSUE THREAD

**Issue by naomap** [tyrasd/overpass-turbo#521]
Sharing a request with a permalink now (since a couple of days or so ?) produces a long URL containing the request, such as:
`http://overpass-turbo.eu/?Q=%2F%2F%5Bbbox%3A%7B%7Bbbox%7D%7D%5D%3B%0Aarea%0A%20%20%5Bboundary%3Dadministrative%5D%0A%20%20%5Badmin_level%3D6%5D%0A%20%20%5Bname%3D%22Gard%22%5D%3B%0A%0Arel%0A%20%20%5Bboundary%3Dlocal_authority%5D%0A%20%20%5B%22local_authority%3AFR%22~%22%5E(PETR)%24%22%5D%0A%20%20(area)%3B%0Aout%20geom%3B%0A&C=43.85483;4.28604;10`
instead of the usual short link so convenient to send via emails.

It might be intentional however I have not seen any announcement about this change on the Overpass mailing list.

**Comment by habi** [comment]
Only short links also return a `503 Service Unavailable`-error, e.g. http://overpass-turbo.eu/s/10NY

**Comment by mmd-osm** [comment]
The shortlink service seems to be done for some reason, I doubt this was in any way intentional.

**Comment by habi** [comment]
> I doubt this was in any way intentional.

Why?

**Comment by mmd-osm** [comment]
The service was up for some 7 years now, and there’s zero reason to believe that this is anything other than some technical glitch.

**Comment by kmpoppe** [comment]
I sure hope it's not intentional, there are tons of links out of the wiki to these short links ;-) Alas, there wasn't a commit to this project within the last 17 days so it's most likely not the source that's gone wrong somewhere, just the server interpreting the links.

**Comment by habi** [comment]
As I'm not a native English speaker I mis-interpreted, and thought you think it's a deliberate decision to turn short links off...

**Comment by DaveF63** [comment]
> anything other than some technical glitch.

> just the server interpreting the links.

A glitch on which server? OSM Turbo or 3rd party URL shortener?

**Comment by mmd-osm** [comment]
IIRC, overpass turbo was using a custom built url shorting service running on overpass-turbo.eu.

**Comment by simon04** [comment]
@tyrasd, can you take a look please? You're the only one capable of debugging/fixing this server issue. Thank you!

**Comment by tyrasd** [comment]
It's fixed for now by restarting the service on the server. I still have to look into why it failed in the first place.

> IIRC, overpass turbo was using a custom built url shorting service running on overpass-turbo.eu.

That's correct. I think I never actually shared the code of it. Anyway, in case you are interested to take a look, here it is: https://gist.github.com/tyrasd/cfa9bcf9cdbfdd27631aa03bb602d0c2

**Comment by simon04** [comment]
Awesome, thank you!
