### ISSUE TITLE
food pois

### ISSUE THREAD

**Issue by djmystica** [tyrasd/overpass-turbo#522]
Hi,
is it possible to look for bakeries, pastries, fish markets, farmers' markets, butchers etc?
basically im interested in all food related point of interests
i see there are only a few amenities related to food, as listed here
https://wiki.openstreetmap.org/wiki/Map_features
thanks!

**Comment by vinber** [comment]
hi, i'm not sure overpass-turbo is best place to discuss about food tags :) i thing is relevent for an osm's tags discussion
if you want bakeries, pastries, fish markets, farmers' markets, butchers you have tags like shop=bakery, shop=pastry, shop=seafood, shop=farm, .....

https://wiki.openstreetmap.org/wiki/Map_features -> this is a simple entry in wiki.openstreetmap.org

**Comment by djmystica** [comment]
thanks Vinber!
how can i select multiple shops?
like shop=bakery, shop=pastry, etc in overpass?
i can only add 1 category atm
thanks!

**Comment by djmystica** [comment]
ok found it!
