### ISSUE TITLE
Add KartaView image id support (as with Mapillary)

### ISSUE THREAD

**Issue by Talkless** [tyrasd/overpass-turbo#524]
It's very convenient to have `mapilarry=*` keys rendered as links in `overpass-turbo` popups. Maybe we could have this kind of functionality for [KartaView](https://kartaview.org/map) too?

There are just a few keys set in OSM: 
https://taginfo.openstreetmap.org/keys/kartaview#values

Though having it available conveniently via `overpass-turbo` would give more motivation to use keys, instead of linking directly with `image=` key which might not be the best solution.

For example, `kartaview=3689641:0` would mean https://kartaview.org/details/3689641/0/track-info, by using scheme someone already started applying.

I've started thread in https://lists.openstreetmap.org/pipermail/tagging/2021-June/061818.html but so far didn't get much from it, so I'm starting initiative on my own.

**Comment by simon04** [comment]
The key `kartaview` is only used on 249 objects (as of 2021-08-29) and lacks an OSM wiki page. Please reopen once the key is used more frequently.
