### ISSUE TITLE
Automatic switch to data view fails for queries returning no nodes

### ISSUE THREAD

**Issue by ltog** [tyrasd/overpass-turbo#528]
I compare the versions running at
- https://overpass-turbo.eu/ (version 7883359 , working fine)
- https://tyrasd.github.io/overpass-turbo/ (version 46aca53 , erroneous)
- https://overpass-turbo.osm.ch/ (version 3e784b0 , erroneous)

The version at overpass-turbo.eu seems to run fine, while the version at tyrasd.github.io (and at osm.ch) seems to be erroneous.

Reproduce like this:

- Open Overpass Turbo
- Adjust the default (or any) query by changing `out;` to `out count;`
- Run the query
- Notice an error message `This query returned no nodes. In OSM, only nodes contain coordinates. For example, a way cannot be displayed without its nodes. If this is not what you meant to get, overpass turbo can help you to repair (auto-complete) the query by choosing "repair query" below. Otherwise you can continue to the data.`
- Click `show data`
- overpass-turbo.eu changes to a data view (same behaviour as clicking the button `Data` on the top right), while with tyrasd.github.io (and osm.ch) nothing happens (except in the browser console, one gets an error message `Uncaught TypeError: r()(...)[0] is undefined` happening at `turbo.15bc95b5b4ed85f61bcd.js:50:69035` (or at `turbo.8186ba244f376fff0801.js:50:69090` for osm.ch ))

**Comment by ltog** [comment]
Ok, I did some bisecting. The behaviour seems to have changed since b2e50f8db3957435db6261fa9468e81c45d54d23.

**Comment by simon04** [comment]
Thank you for reporting. The suggested fix in #529 is incorrect (accessing `$(...).checked` does not make any sense). The actual problem is that the modal dialog is destroyed before invoking the button callback.
