### ISSUE TITLE
CONFUSING: include name of loaded query

### ISSUE THREAD

**Issue by axd1967** [tyrasd/overpass-turbo#531]
When loading a query from OSM.org, it is never clear which query is now active in the editor:

![image](https://user-images.githubusercontent.com/3529789/131225516-82097164-db97-4b2a-ae80-2f801f6151b8.png)
![image](https://user-images.githubusercontent.com/3529789/131225524-833eaa1d-8ce2-4c9a-ac03-b88d7865e19c.png)

**Comment by simon04** [comment]
Do you have an idea where to include the query name? How should this label behave once you modify the loaded query?

**Comment by axd1967** [comment]
I understand, but that's a technical issue... I'm only reporting a problem.

A dirty workaround could be to inject the query name as a top-level comment string in the query?

So this leads to this user workaround:

## workaround
Manually include the name of the query as a comment in the query.

**Comment by Lee-Carre** [comment]
> that's a technical issue

No, it's a *user-visible design* issue (what to implement), which will significantly affect actual technical issues (how to implement).

Not wanting to deal with inconvenient considerations won't make them go away.

Until they're resolved, nothing will be implemented.
Software development isn't a magic black-box.

> comment

My first thought was this *as a solution*, so I'm not sure that calling it a workaround is accurate.

Besides, unless OP-T is gonna store a whole lot of state (which persists across sessions), then some kind of string in the composed query itself seems necessary. By nature, it must be a comment.

**Comment by simon04** [comment]
Fixed via #608 – https://tyrasd.github.io/overpass-turbo/ – latest version

<img width="497" alt="Screenshot 2023-01-28 at 16 39 56" src="https://user-images.githubusercontent.com/782446/215275626-4cf18cad-5775-42da-9b9f-5bddf76b5885.png">
