### ISSUE TITLE
Dutch translation for "share.copy_this_link" is outdated

### ISSUE THREAD

**Issue by danieldegroot2** [tyrasd/overpass-turbo#533]
The display text for the Dutch translation of the string ["share.copy_this_link"](https://github.com/tyrasd/overpass-turbo/blob/ec7010ff6b491c06db9742be3b061201781b4856/locales/nl.json#L119) currently defaults to an older translation, while a newer translation already exists.
This is the case for other users as well.

("Copieer" -> "Kopieer"; translation of "copy")

![image](https://user-images.githubusercontent.com/67521919/132383187-e9e76c02-1b0f-4ed0-a65f-6673f6680a60.png)

**Comment by simon04** [comment]
The strings have been updated a few months ago, https://github.com/tyrasd/overpass-turbo/commit/46aca53522404d1d7026f2dbd5bf1426f760371e. Please see the latest version deployed to https://tyrasd.github.io/overpass-turbo/
