### ISSUE TITLE
No hits with query that used to work

### ISSUE THREAD

**Issue by Shohreh** [tyrasd/overpass-turbo#536]
Hello,

For some reason, the following query no longer works:

```
[out:json][timeout:25];

//Paris : 7444
rel(7444);
map_to_area -> .searchArea;

(
  node["amenity"="bicycle_rental"](area.searchArea);
  way["amenity"="bicycle_rental"](area.searchArea);
  /* OK
  node["amenity"="bicycle_rental"]({{bbox}});
  way["amenity"="bicycle_rental"]({{bbox}});
  */
);
// print results
out body;
>;
out skel qt;
```

→ "This map intentionally left blank."

Is there an issue server-side?

Thank you.

**Comment by mmd-osm** [comment]
Temporary issue on one of the two production servers, which has been fixed in the meantime.

You can close the issue again, there's nothing left to do.
