### ISSUE TITLE
Q: Apart from the new graphics...

### ISSUE THREAD

**Issue by DaveF63** [tyrasd/overpass-turbo#548]
Hi
Apart from the new graphics* ...

Are there any new features/fixes that users should be aware of?

* Not keen on the new font used in an entity's tag list & the search box is too big

**Comment by mmd-osm** [comment]
I'd recommend to take a look at the changelog: https://github.com/tyrasd/overpass-turbo/blob/master/CHANGELOG.md
In addition, you can see the query runtime when hovering over the bottom right box. I hope this answers your question.
