### ISSUE TITLE
Does not display node without tag and its parent way at the same time

### ISSUE THREAD

**Issue by ridalalven** [tyrasd/overpass-turbo#550]
Hi! Following up on what might be a bugg: I cannot succeed getting Overpass Turbo displaying both a node which is part of a way _and_ this way at the same time. Here, an Overpass example: http://overpass-turbo.eu/s/1b3P. If I delete the line printing the way (line 3), I can see the node on the map. Otherwise, the map will only show the way. Thanks for checking this unexpected behaviour! In case it is just something I am doing wrong, I am looking forward to a hint :)

**Comment by mmd-osm** [comment]
Seems to be a duplicate of #499

Related discussion: https://help.openstreetmap.org/questions/81712/overpass-turbo-plot-both-a-way-and-a-certain-node-of-that-way (uses the exact same example .../s/1b3P  as above)

**Comment by ridalalven** [comment]
Yes, it is the question on https://help.openstreetmap.org/questions/81712/overpass-turbo-plot-both-a-way-and-a-certain-node-of-that-way where DaveF suggests that it is likely to be a bug. It might be the same bug as mmd-osm mentions; then, it would mean that Overpass Turbo never shows nodes without tags along a way - even if asked to show both the way and a node on it - as long as the node does not have a tag.

Now, I checked that it works for nodes that have tags:. Here, **two examples** for illustration:
```
[out:json][timeout:10];
way(151615630); // river
out geom;
node(1230090972); // node of river with tag
out geom;
```
```
[out:json][timeout:10];
way(151615630); // same river
out geom;
node(1644398312); // node of river without tag
out geom;
```
The **first case** displays both way and node; the **second** only the way and not the node. Is this the correct behaviour or is it a bug? In case it is no bug, I am happy for all hints how to display both the way and the un-tagged node at the same time.

**By the way**, when querying to display both a relation and a node without tag that is part of that relation, both are displayed correctly: [https://overpass-turbo.eu/s/1f1S](https://overpass-turbo.eu/s/1f1S). Therefore, I assume the problem to be a bug.

**Comment by mmd-osm** [comment]
Can you please copy all of your comments in this issue to the existing issue #449 and close this one? 

There's not much benefit in having two issues discussing the exact same topic.

**Comment by ridalalven** [comment]
@mmd-osm: Sorry, I did not understand that they actually are the same when reporting the bugg because comments in #499 are discussing center versus geom and colourised nodes as well as #499 was labelled as question. Anyways, I will do as you said.

**Comment by ridalalven** [comment]
As mmd-osm suggested, please refer to #499 instead.
