### ISSUE TITLE
Map shows area even though `out center` is used

### ISSUE THREAD

**Issue by tordans** [tyrasd/overpass-turbo#551]
I have a query of relations but want to get the center (with all tag).
In general, that works, but the Maps shows one relation as an area as well (first screenshot).
However, the Data-Tab does not show anything lets me think this one area is different from the others.
And when I export-visualize the GeoJSON in https://geojson.io/#map=12/52.3608/13.6033, it looks fine as well (second screenshot).

# Steps

Run https://overpass-turbo.eu/s/1f1o
RESULT: 
![image](https://user-images.githubusercontent.com/111561/149306443-55a70fd7-e464-450b-93dd-43499de4a987.png)

EXPECTED RESULT:
![image](https://user-images.githubusercontent.com/111561/149306477-9c01b80c-2351-4dad-b797-cac67abd4cdf.png)

**Comment by mmd-osm** [comment]
Cannot reproduce here. All I see is a few center points for the relations and no areas whatsoever.

**Comment by tordans** [comment]
Thanks for checking mmd. I retried in a different browser and don't see the issue anymore either. Maybe there was some weird caching situations… – anyway, not worth keeping this ticket open.
