### ISSUE TITLE
Spelling issue in estonian translation

### ISSUE THREAD

**Issue by kallejre** [tyrasd/overpass-turbo#553]
Reporting a very small, but common and slightly annoying issue with estonian translation: "zoom to data" is currently translated as "suurenda andmete _järgi_", which in verbatim translation mean "zoom to follow the data". Instead of "järgi" should be "juurde" (to/by).

Yes, I am aware that translations are managed through Transifex (this phrase is on row 22), but since the translation has been reviewed it can't be edited as easily. I already submitted suggestion on Transifex, but looking at the history, it becomes apparent that estonian translation has been inactive for past 8 years and therefore any suggestions made there will probably be ignored.

Another small error i noticed there was row 214: "do not show this message again." -> "ära näita rohkem." is missing "_this message_" portion. Already submitted suggestion for that phrase as well.

**Comment by simon04** [comment]
Please see https://github.com/tyrasd/overpass-turbo#translating and fix the error on Transifex. Thanks!
