### ISSUE TITLE
Use Overpass-turbo on Local Server Running Overpass API?

### ISSUE THREAD

**Issue by convolutionbbs** [tyrasd/overpass-turbo#558]
Hello,
I have a local server that is running the overpass api with instructions here:
https://wiki.openstreetmap.org/wiki/Overpass_API/Installation

I also have installed the overpass-turbo on that server using the fairly simple # npm install, # npm start as found on the README.

Is it possible to configure overpass-turbo to query my local server directly instead of out to the internet?  It may be doing this already, but it's not obvious to me where the configuration parameters may be.

Thanks

**Comment by mmd-osm** [comment]
Overpass turbo runs exclusively in your browser and needs to talk to the overpass API endpoint via http. It doesn’t really matter where you deploy overpass turbo static files.

**Comment by simon04** [comment]
You may customize the suggested servers in the config (before building):

https://github.com/tyrasd/overpass-turbo/blob/b37de36eb81e84e5dde4fd65207d0d89e5bef7cb/js/configs.ts#L7-L13
