### ISSUE TITLE
How to get the direction of link of road network?

### ISSUE THREAD

**Issue by RuoyunChen** [tyrasd/overpass-turbo#564]
I'm looking at the city of Montreal in Canada and I have extracted the road network (motorway|trunk|primary|motorway_link|trunk_link|primary_link)

Now looking at the attribute table of the data with QGIS, I don't know how to get the direction of each segment of the way. Will the nodes contain information like that? How to see it from the data? Thanks!

**Comment by mmd-osm** [comment]
This is probably the wrong repo for this kind of question, as it's specifically for overpass-turbo.eu. You need to find another community site for your question.
