### ISSUE TITLE
Firefox 98 warning about `__storejs__test__` cookies

### ISSUE THREAD

**Issue by tomhughes** [tyrasd/overpass-turbo#568]
Firefox 98 is issuing warnings about the `__storejs__test__` cookie in the console:

> Cookie “__storejs__test__” will be soon rejected because it has the “SameSite” attribute set to “None” or an invalid value, without the “secure” attribute. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite

Although it says it will soon be rejected it seems it might actually be rejecting it because I get the unsupported browser notice :-(

Oddly if I use private browsing then the console message goes away, as does the unsupported browser notice.

I've tried disabling all the extensions (uMatrix, uBlock, etc) that might be interfering and it doesn't seem to make any difference.

**Comment by mmd-osm** [comment]
I cannot reproduce those messages. Are you sure you're not calling overpass turbo using some Google service (translate, or some mobile thing)? A few sites list  __storejs__test__ as one of Google's marketing cookies.

**Comment by tomhughes** [comment]
So this is all very odd...

Both my laptop and my desktop were displaying the same symptoms and in both cases devtools claimed there was no storage of any sort for the site but when I went to the main settings and used "Manage Data" it showed 64Kb of storage for overpass-turbo.eu and when I deleted that everything started working.

The alert has stopped appearing and the console messages have also vanished!

**Comment by SammysHP** [comment]
I can reproduce this issue.

Firefox 99, the website works only via https. Using http I can see the warning in the console and the "unsupported browser" popup.
