### ISSUE TITLE
Short URL is not generated when viewed with HTTP

### ISSUE THREAD

**Issue by danieldegroot2** [tyrasd/overpass-turbo#572]
Forwarding [user report](<https://twitter.com/BUnicycling/status/1513177726433349637>) (April 10, 5:30PM CEST) from [b-unicycling](https://www.openstreetmap.org/user/b-unicycling):
> Incidentally, has overpass-turbo stopped with the short links altogether? I've tried Firefox and Chrome and different PCs and it just doesn't generate them for me.

As it works for me and others, sent a DM. Reply;
> Sorry, [trying again] doesn't work. It's a pity, because I don't want to use the long link to share. It hasn't worked for a couple of weeks for me now.

Asked for a screenshot of the website and console.

(_May be related to #338._)

**Comment by mmd-osm** [comment]
Works fine here. User should try another browser, or turn off any browser plugins or similar and try again.

**Comment by danieldegroot2** [comment]
> I would recommend to close the issue as it's obviously working for other users.

Sure. I'll close the issue once it's been resolved, or when they don't reply in the near future.

**Comment by mmd-osm** [comment]
By the way, browser console may also have some hints why it didn't work.

**Comment by danieldegroot2** [comment]
> By the way, browser console may also have some hints why it didn't work.

Just fyi, I mentioned asking for this at the bottom of my first post.

**Comment by danieldegroot2** [comment]
@mmd-osm now we know [it returns a _403 Forbidden_](https://twitter.com/BUnicycling/status/1513608019715764230).

Should I ask them to expand the details for this and screenshot (or copy over) the full error? I've asked them to disable extensions in the meantime.

**Comment by mmd-osm** [comment]
Interesting, it seems the sharelink service only works once you start up overpass-turbo using https: https://overpass-turbo.eu/

**Comment by HolgerJeromin** [comment]
Ref
https://github.com/tyrasd/overpass-turbo/issues/336#issuecomment-346102142

**Comment by mmd-osm** [comment]
> They also have queries cached seperately, it seems.

I don't think so, both links end up with the same query: https://overpass-turbo.eu/s/1gtZ and http://overpass-turbo.eu/s/1gtZ

**Comment by danieldegroot2** [comment]
> > They also have queries cached seperately, it seems.
> 
> I don't think so, both links end up with the same query: https://overpass-turbo.eu/s/1gtZ and http://overpass-turbo.eu/s/1gtZ

I meant what tyrasd mentioned in above linked comment; they have seperate local storage.
> people might have queries (or other settings) saved in their browser's local storage which they would like to keep [when switching the website to only use the HTTPS version].

**Comment by SammysHP** [comment]
It's not only TLS, it also does not work when you access overpass-turbo via the www subdomain:

https://www.overpass-turbo.eu – fails
https://overpass-turbo.eu – OK

**Comment by tyrasd** [comment]
this bug should be fixed now
