### ISSUE TITLE
overpass-turbo.eu sometimes fails silently for larger bounding boxes / areas

### ISSUE THREAD

**Issue by cristianbogdan** [tyrasd/overpass-turbo#574]
Something very strange happens with overpass queries since today. Queries that used to work now fail. This issue looks similar to #453.  

Sometimes this query is successful, but returns an empty result set.
```
(area[boundary=administrative]["name:en"=Romania];)->.ro;
(
  way(area.ro)[highway~motorway]
); 
(._;>;);
out meta;
```

At the same time, this query works as expected:
```
(area[boundary=administrative]["name:en"=Romania];)->.ro;
(
  way(area.ro)[highway~proposed];  
); 
(._;>;);
out meta;
```
Same goes for `highway~construction`,  it works very well.

I have also noticed that when the first query fails, setting a small bounding box instead of `(area.ro)` may return the correct results: `way({{bbox}})[highway~motorway]; `. However, zooming out (enlarging the bounding box) will return an empty result set, with no error code or error message.

Also combining `highway~construction`  with `highway~motorway` in the same query will return a combination of the above, in other words there will be `construction` highways (or railways) in the result, but no motorways!

To complicate things further, this problem only happens sometimes. It happened an hour ago and 12 hours ago, but it does not happen right now.

**Comment by mmd-osm** [comment]
Overpass turbo is only a web fronted. The issues you describe need to be reported over at Overpass API. Likely the issue has been fixed in the meantime already.
