### ISSUE TITLE
Store query in url when running it

### ISSUE THREAD

**Issue by tguen** [tyrasd/overpass-turbo#585]
I often have multiple tabs with different queries open at once. If I close my browser and reopen it (it's configured to reopen all of my tabs), all of my overpass tabs show only the last query I ran. I often forget what queries I had open. Even if I remember, I usually don't have them saved and have to rewrite them. This is obviously very frustrating.

I'd like the site to update the url when running a query so it's not lost if the tab is reloaded, similar to how osm.org changes the url when panning the map, selecting features or changesets, etc.

Related: #563

**Comment by simon04** [comment]
Related: #563
