### ISSUE TITLE
Query results should have been filtered out?!

### ISSUE THREAD

**Issue by sjakobi** [tyrasd/overpass-turbo#586]
https://overpass-turbo.eu/s/1mdI returns several nodes that I meant to remove by specifying `[covered=yes]`, e.g. 

* https://www.openstreetmap.org/node/5860596145
* https://www.openstreetmap.org/node/5860596146

Is my query bad or might these results indicate a bug in the app?

**Comment by sjakobi** [comment]
Hmm, I'm failing to reproduce the issue in a different browser. I suspect the result set may have been cached from an earlier query. Does this seem plausible? What would be a good way to prevent this issue?

**Comment by mmd-osm** [comment]
Your query is bad, by adding [covered=yes] you’re including rather than excluding nodes with such tagging.

**Comment by sjakobi** [comment]
> Your query is bad, by adding [covered=yes] you’re including rather than excluding nodes with such tagging.

The unexpected nodes don't even have a `covered` field, so I think they ought to be filtered out?!

Anyway, I can't reproduce the issue any more, so I'll close this.

Thanks for this great tool, in any case! :)
