### ISSUE TITLE
GPX download is in UTF-8 BOM

### ISSUE THREAD

**Issue by boldtrn** [tyrasd/overpass-turbo#603]
Not a super serious issue, but I wanted to report it, as it cost me quite a bit to track down.

Exported gpx files are in UTF-8 BOM, which can require reading applications to exclude the BOM.

You can check this like:
```
# file export.gpx
export.gpx: XML 1.0 document text, UTF-8 Unicode (with BOM) text, with very long lines
```

Other GPX files are:
```
other.gpx: XML 1.0 document text, UTF-8 Unicode text
```

**Comment by simon04** [comment]
Fixed on https://tyrasd.github.io/overpass-turbo/ via 3ccdff385234b067ac60c69d74bcdc79fedf66fd.
