### ISSUE TITLE
Long Queries/URL parameters result in "414 Request-URI Too Long"

### ISSUE THREAD

**Issue by ManCaveMedia** [tyrasd/overpass-turbo#611]
Long GET requests (about 200 ways) in a URL parameter (?q="" or ?Q="") result in a "414 Request-URI Too Long" error.
I tried a POST request, but that's not working at all. Would this be something you can fix?

My children are going door-to-door delivering flyers.
We use a google spreadsheet to track the streets they've been to and the flyers we have put an address sticker on.
We were able to generate a live map based on this data, but now they have about 100 streets done, the request gets too long.
If I was able to POST the parameters, I believe this would be solved.

**Comment by simon04** [comment]
The following variants are supported now:

- https://tyrasd.github.io/overpass-turbo/?q=...
- https://tyrasd.github.io/overpass-turbo/#q=...

https://tyrasd.github.io/overpass-turbo/ – latest version
