### ISSUE TITLE
Also have direct link to editor

### ISSUE THREAD

**Issue by jidanni** [tyrasd/overpass-turbo#612]
![20230118T094951](https://user-images.githubusercontent.com/1230959/213061567-4765bfa2-0382-4d6f-bcc3-d459dbd043b6.jpg)
Here there is a hyperlink to https://www.openstreetmap.org/way/522890635 .
But often we want to got to https://www.openstreetmap.org/edit?way=522890635 
So to save us some clicking, maybe say
> [522890635](https://www.openstreetmap.org/way/522890635) ([✏](https://www.openstreetmap.org/edit?way=522890635)), or just
> [522890635](https://www.openstreetmap.org/way/522890635)  [✏](https://www.openstreetmap.org/edit?way=522890635).

P.S., maybe have the link be https://www.openstreetmap.org/edit?way=522890635#map=17/24.31009/120.73338 to save even more time, just like what happens when we go to the current link, and push Edit at the top.

**Comment by simon04** [comment]
Live on https://tyrasd.github.io/overpass-turbo/ – latest version

**Comment by jidanni** [comment]
Thanks, but I can't find it yet there.

**Comment by jidanni** [comment]
Cool!

**Comment by DaveF63** [comment]
I appear to have a problem with this. Can you replicate it?

Open this (Greenwich, London) or any other location in osm.org
https://www.openstreetmap.org/#map=19/51.47688/0.00000

Open JOSM (I'm using latest windows .exe version) 

Run @simon04's Overpass above. Select one & click on the pencil.

For me, it loads the Greenwich data, not Rome by using the wrong co-ordinates.
It also loads another tab (the node object is a Rome fountain.):
https://www.openstreetmap.org/edit?node=255454064#map=19/51.47688/0.00000

Close the Greenwich tab & the JOSM layer & select another drinking fountain & the same happens.

Do you get the same?

**Comment by jidanni** [comment]
I don't use JOSM, etc. so can't help testing. So you should probably open a new issue.

**Comment by DaveF63** [comment]
My post wasn't really aimed at just you.

JOSM isn't required as, as I stated, it also loads a new tab in OSM.org indicating the problem.

If I had posted a new thread I would have been criticized for not posting here.
