### ISSUE TITLE
Add touchscreen pan/zoom functionality to the slippy map

### ISSUE THREAD

**Issue by thibaultmol** [tyrasd/overpass-turbo#613]
openstreetmap.org and the iD editor both have the ability to zoom and pan using a touchscreen (like on a laptop), but overpass turbo doesn't do anything with this input

**Comment by simon04** [comment]
Very likely fixed via #615.

**Comment by thibaultmol** [comment]
Can confirm that it works on Chrome (chromeos) and chrome (android).
it's a small thing, but my god do I love interacting with maps via touch zoom and pan. Great!
