### ISSUE TITLE
is it possible to show ways in different colors depending on a parameter ?

### ISSUE THREAD

**Issue by EssBee59** [tyrasd/overpass-turbo#614]
Hello,
thank for the fantastic tool!
For quality assurance I liked to show a list of ways with a color depending on a parameter I previously calculated: 
(for our  bike-routing engine -the brouter- we are trying to consider new "tags", as example a noise-factor or river-factor..)

After calculation of the "noise" factors we have a list of ways, and each way is associated with a "class" (value between 1 and 6):

the following request is alreday a very good help, as it shows all the ways we have considerd for noise:
  [out:json];
way(id:
 177730583 ,
 984260059 ,
....   (list of 1000 till 5000 ways)
 744603079 ,
 41556898 
)
;
out geom;

My question:  is it possible to show the ways in a color depending on the "class" parameter,?
Example:
----------------
way_id,  class
 177730583 , 3      ==> yellow
 984260059 , 6      ==> red
....   
 744603079 , 1     ==> green
 41556898  2       ==>  blue
Regards

**Comment by simon04** [comment]
Hi, please take a look at https://wiki.openstreetmap.org/wiki/Overpass_turbo/MapCSS

**Comment by EssBee59** [comment]
Hello simon04,
thank for your help!

Yes, the documentation is very good, but I did not found a "simple" solution to my special request.
Now using a perl script I have a running solution (that looks a bit strange with big overhead)
No matter, thank to the overpass-team!

I attach an example of my solution where the ways are listed twice:
-once in the main "way list"
-then in 6 "style" classes each way appears again according to his class (meta-data)
regards
(I will close this request in the next days) 
[1-stock_river.txt](https://github.com/tyrasd/overpass-turbo/files/10526970/1-stock_river.txt)

**Comment by simon04** [comment]
It seems that you'd like to color the tracks based on `tracktype`, that's what you call "class"? Follow the [color coding](https://wiki.openstreetmap.org/wiki/Overpass_turbo/MapCSS#Color_Coding)...

**Comment by EssBee59** [comment]
> It seems that you'd like to color the tracks based on `tracktype`

Hello,
No, the "class" above is an own calculated parameter (with a value between 1 and 6), a kind of "new tag", but not known in the OSM!.
thank for your help, as I have a solution now I close the request
Regards

**Comment by EssBee59** [comment]
It seems, no simple solution exist to my special request... but I found a workarround with a perl script!
