### ISSUE TITLE
infinite "parse url parameters" - "Uncaught (in promise) TypeError: l is null"

### ISSUE THREAD

**Issue by matkoniecz** [tyrasd/overpass-turbo#623]
use link https://overpass-turbo.eu/?Q=%7B%0Anwr%5Bbuilding%5D%28%7B%7Bbbox%7D%7D%29-%3E.all%3B%0A%28.all%3B+-+nwr.all%28newer%3A%222020-04-01T00%3A00%3A00Z%22%29%3B%0A%29%3B%0Aout+body%3B%0A%3E%3B%0Aout+skel+qt%3B&C=50.0733/19.9285;19

overpass is stuck at

![screen01](https://user-images.githubusercontent.com/899988/222217322-cc1fa224-a5cb-4d67-82ec-4e10bebd2826.png)

browser console shows 

```
Uncaught (in promise) TypeError: l is null
    i https://overpass-turbo.eu/turbo.d81a7a4eb4fd922cae37.js:58
    t https://overpass-turbo.eu/turbo.d81a7a4eb4fd922cae37.js:50
    init https://overpass-turbo.eu/turbo.d81a7a4eb4fd922cae37.js:50
turbo.d81a7a4eb4fd922cae37.js:58:61410
```

link is used in https://wiki.openstreetmap.org/wiki/Overpass_API/Overpass_API_by_Example#Old_objects

**Comment by simon04** [comment]
The URL needs to be fixed

```diff
-&C=50.0733/19.9285;19
+&C=50.0733;19.9285;19
```

I'll make the parsing more robust...
