### ISSUE TITLE
Option to filter by today()-x days

### ISSUE THREAD

**Issue by tastrax** [tyrasd/overpass-turbo#625]
I regularly rerun queries and it would be good to limit the queries by X number of days somehow. without having to specify exact dates

**Comment by simon04** [comment]
Are you referring to the date-clauses like the following part of the "Attic date query" example?

```
[date:"2016-01-01T00:00:00Z"];

```

**Comment by tastrax** [comment]
I am using it in Overpass turbo and I think I have sussed out that the following works effectively?

["{{date:"1 month"}}"]
