### ISSUE TITLE
Searching 'in London' in the wizard doesn't include things in the City of London

### ISSUE THREAD

**Issue by RedAuburn** [tyrasd/overpass-turbo#631]
When typing 'x in London' the expected results would be anything within London, however it doesn't include things in the City of London:
![Screenshot from 2023-04-07 10-07-51](https://user-images.githubusercontent.com/26939824/230580677-5e154ea3-1a7e-43c2-b501-4a1ab96eb556.png)

**Comment by mmd-osm** [comment]
https://www.openstreetmap.org/relation/65606 is the first hit returned by Nominatim, which is used under the hood when you search for "London". So this result is expected.

**Comment by mmd-osm** [comment]
"Greater London" is the first hit returned when querying for "London", and that's exactly what you get here.

**Comment by RedAuburn** [comment]
> "Greater London" is the first hit returned when querying for "London", and that's exactly what you get here.

Ah, yup looks like this is a Nominatim issue 👍
