### ISSUE TITLE
node["tourism"="wilderness_hut"] does not find all the huts in the wilderness

### ISSUE THREAD

**Issue by User156785** [tyrasd/overpass-turbo#632]
Example: only 1 out of 8 huts is found:
https://overpass-turbo.eu/s/1uo3

![image](https://user-images.githubusercontent.com/132166729/235325356-b235a26f-9203-4091-adb4-1bbcce83b4ad.png)

**Comment by simolg** [comment]
they are not the same types of nodes, try a more generic one: amenity=shelter
nw[tourism=wilderness_hut]({{bbox}});
nw[amenity=shelter]({{bbox}});

. . . or filter by category
nw["shelter_type"~"basic_hut|rock_shelter|weather_shelter|lean_to"]({{bbox}});

**Comment by simolg** [comment]
they are not the same types of nodes, try a more generic one: "amenity"="shelter"
`nw[tourism=wilderness_hut]({{bbox}});`
`nw[amenity=shelter]({{bbox}});`

or filter by category
`nw["shelter_type"~"basic_hut|rock_shelter|weather_shelter|lean_to"]({{bbox}});`

check here:
https://wiki.openstreetmap.org/wiki/Tag:amenity=shelter
https://wiki.openstreetmap.org/wiki/Key:shelter_type

**Comment by simolg** [comment]
you must also include "way"

```
[out:json];
(
  node["tourism"="wilderness_hut"]({{bbox}});
  way["tourism"="wilderness_hut"]({{bbox}});
);
out center;
>;
```

**Comment by User156785** [comment]
Ja - na, klar! Dankeschön!
Wie sagt ein Kollege immer: Wer lesen kann ist klar im Vorteil.  ;-)
[https://dev.overpass-api.de/overpass-doc/de/preface/osm_data_model.html#nwr]
