### ISSUE TITLE
Regex not working for for addr:housenumber

### ISSUE THREAD

**Issue by gdprdatasubect** [tyrasd/overpass-turbo#648]
Hello,

i tried finding large housenumbers, but the following did not work:
```
  node["addr:housenumber"~"^\d{4}"]({{bbox}});
  way["addr:housenumber"~"^\d{4}"]({{bbox}});
```
Am i missing something or using it wrong?

**Comment by mmd-osm** [comment]
You're missing a second "\",  as documented here: https://wiki.openstreetmap.org/wiki/Overpass_API/Overpass_QL#Value_matches_regular_expression_(~,_!~)

_Please note that in QL you need to escape backslashes: ..._
