### ISSUE TITLE
Problem with map_to_area ?

### ISSUE THREAD

**Issue by Mahabarata** [tyrasd/overpass-turbo#650]
Hi,

I created this query : https://overpass-turbo.eu/s/1yFn

The problem is that, in the area of the relation Marshall Islands (see https://www.openstreetmap.org/relation/571771#map=6/9.579/167.003), the relation Naṃdik 3825989 (see https://www.openstreetmap.org/relation/3825989#map=6/9.579/167.003) is not listed in the result of the query and I don't understand why : this relation has the tag admin_level and is in the area so it should be selected, no ?

Same thing for the relation Enewetak 3825996 (see https://www.openstreetmap.org/relation/3825996#map=6/9.579/167.003).

Could you have a look ?

Best regards

**Comment by mmd-osm** [comment]
I haven't looked into your example in detail, most likely, the relations in question share the same ways as the area. However, according to https://wiki.openstreetmap.org/wiki/Overpass_API/Overpass_QL#By_area_(area) _The area filter selects all elements of the chosen type that are **inside** the given area or areas_ Note that the word "inside" is really important here. 

Also, I'd recommend to discuss such HOWTO issues on https://community.osm.org instead.

**Comment by Mahabarata** [comment]
Except that the result of the query shows the relation 571771 itself.

In another way of speaking, the query finds the relation 571771 and only this relation (first line), changes this relation into an "area" (second line) then tries to find all relations with a specific tag that are in this area (third line) : so it finds the relation 571771 itself but not the relation 3825989 when this relation is in the area (and is part of the relation 571771 itself as a member).

For me it is incoherent that the third line finds the relation 571771 and not the relation 3825989 : it looks like a bug so I think only you (I mean the developers of overpass and not the community) can find out what is happening.

I have another more complex result : the same query for another country (replace "Marshall Islands" with 'Oman" in the above query). This country has a main area and 2 exclaves, see https://www.openstreetmap.org/relation/305138#map=6/21.739/56.019. The final result shows all the relations inside this area (in particular the complex relation https://www.openstreetmap.org/relation/3781315 = good news) but also a relation which is clearly **outside** the area : https://www.openstreetmap.org/relation/12905765#map=6/21.739/56.019

Overpass-turbo is a great query software, I use it a lot to find problems in osm datas.

But I stopped to trust "map_to_area" because sometimes it gives not enough datas and sometimes too much datas : I hope you will find what is going on because this statement is (will be) very useful.

Best regards.

**Comment by mmd-osm** [comment]
Thank you for your comment. In case you want to report some issue with is_in, you need to head to the Overpass API backend repo instead. This repo covers the web frontend only.

**Comment by Mahabarata** [comment]
Done, thanks
