### ISSUE TITLE
Move from OAuth 1.0a to OAuth 2.0 for OSM logins

### ISSUE THREAD

**Issue by mmd-osm** [tyrasd/overpass-turbo#653]
OSM's OAuth 1.0a is in the process of being deprecated, as discussed at https://github.com/openstreetmap/operations/issues/867. No timeline has been set, but we do not expect to shut off OAuth 1.0a this year. It would be good to move to OAuth 2.0 well before this time.

**Comment by mmd-osm** [comment]
@tyrasd : thanks for switching to OAuth 2.0, we can close this issue now... 

![image](https://github.com/tyrasd/overpass-turbo/assets/5842757/90078eaa-2429-4384-9554-b278b6311e87)

**Comment by tyrasd** [comment]
ah, yes, I forgot to close this ticket. thanks for keeping track of it!
