### ISSUE TITLE
What happened to custom online queries?

### ISSUE THREAD

**Issue by CapitaineMoustache** [tyrasd/overpass-turbo#665]
Since the last update, I can no longer access custom queries saved online and accessible by logging into one's OpenStreetMap account.
Will they come back? Are they lost?

Long live Overpass Turbo! Thanks for your fantastic work!

![Screenshot 2023-10-17 at 12-00-14 overpass turbo](https://github.com/tyrasd/overpass-turbo/assets/72600146/4ab0f619-3508-4f96-a80b-0fe28ef2c28e)

**Comment by mnalis** [comment]
I'm missing that too, and have several complex / important queries saved there which I can no longer access :sob: 

Can we have that feature back please?

**Comment by mnalis** [comment]
> Try to logout, then hit "Load" again, then again "Load" on the popup

I would, but the `Logout` button is missing too (Even after force-refreshing with ctrl+f5):

![Screenshot 2023-10-26 at 22-25-59 overpass turbo](https://github.com/tyrasd/overpass-turbo/assets/156656/da480d33-3dc4-47fd-ab87-41d8f7c1e821)
![Screenshot 2023-10-26 at 22-26-12 overpass turbo](https://github.com/tyrasd/overpass-turbo/assets/156656/8a14611b-f37d-4119-8869-9b2245a86b05)

I've tried clearing cookies and local storage for overpass-turbo.eu domain, as well as revoking Overpass turbo OAuth1 authorizations; but it still doesn't help. Firefox 115.4.0esr. Any hint what else to try? I really don't want to erase all cache / site data in Firefox for all sites :scream_cat:

**Comment by mnalis** [comment]
found it!

Just typing `overpass-turbo.eu` in web browsers opens plain http connection to http://overpass-turbo.eu/ which does not offer OSM Save/Load functionality (but works otherwise) !

Manually opening `https` site with https://overpass-turbo.eu/ does offer `Saved Queries (osm.org)` :smiley: 


Perhaps http site should force-redirect to https, or at least use [HSTS](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Strict-Transport-Security) to avoid such behaviour? 

Or at least such behaviour should be visibly documented (e.g. show 'Load from OSM` but have text `Must use https://overpass-turbo.eu to use this functionality` below it instead of `Load` button)

**Comment by mmd-osm** [comment]
Force redirect has been discussed in some other issue. I think it's super annoying for people who run their own Overpass instances on http.

**Comment by CapitaineMoustache** [comment]
Thanks a lot @mnalis! 
That was a HTTPS issue!
#

> found it!
> 
> Just typing `overpass-turbo.eu` in web browsers opens plain http connection to http://overpass-turbo.eu/ which does not offer OSM Save/Load functionality (but works otherwise) !
> 
> Manually opening `https` site with https://overpass-turbo.eu/ does offer `Saved Queries (osm.org)` 😃
> 
> Perhaps http site should force-redirect to https, or at least use [HSTS](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Strict-Transport-Security) to avoid such behaviour?
> 
> Or at least such behaviour should be visibly documented (e.g. show `Load from OSM` but have text `Must use https://overpass-turbo.eu to use this functionality` below it instead of `Load` button)

**Comment by mnalis** [comment]
Just to note that my solution ended up being turning on **_"Enable HTTPS-Only Mode in all windows"_** setting in my Firefox, which fixed the issue permanently, and I'd like to thank overpass-turbo to giving me a final nudge to do that :smile_cat: 

I'd still recommend it would be nice for all unsuspecting users if there was a message that the functionality is disabled. I guess somewhere around here:

https://github.com/tyrasd/overpass-turbo/blob/9cc1d4738a2a82a0a1bd1278a40680d12c7da4d7/js/ide.ts#L1318-L1334


For `overpass-turbo.eu` instance in particular, perhaps adding HTTP/2 support on  would fix issue automagically (by clients spontaneously upgrading to [TLS-enabled HTTP/2](https://en.wikipedia.org/wiki/HTTP/2#Encryption) when available) ?
