### ISSUE TITLE
The 'no entities found' message is failing to display.

### ISSUE THREAD

**Issue by DaveF63** [tyrasd/overpass-turbo#668]
The 'no entities found' message is failing to display, even though the option to disable is is unchecked.
Even after I've performed a reset. Win 10, Firefox latest.

![image](https://github.com/tyrasd/overpass-turbo/assets/9528328/7af645c6-8a74-48c6-92cc-fdf349d96084)

**Comment by tastrax** [comment]
Agreed that its failing to display correctly, but I think its actually in the background

![image](https://github.com/tyrasd/overpass-turbo/assets/8775395/5bfde969-6410-4254-8aca-c56f160fba72)
