### ISSUE TITLE
`"Drinking Water" in London` in Wizard query does not work

### ISSUE THREAD

**Issue by habi** [tyrasd/overpass-turbo#685]
Entering `"Drinking Water" in London` into the Query Wizard window at https://overpass-turbo.eu/ fails to complete the search.
Entering `"Drinking Water" in Zürich` also fails to complete the search.

Entering `"Drinking Water" in Zürich` at http://overpass-turbo.osm.ch works just fine.

Safari Version 17.2.1 (19617.1.17.11.12) on macOS 14.2.1 (23C71)

**Comment by habi** [comment]
Mentioned on https://redd.it/19dr8yh, tested just now by me

**Comment by hfs** [comment]
Duplicate of #667

**Comment by simon04** [comment]
Duplicate of #667.
