### ISSUE TITLE
Tiny-url creation fails

### ISSUE THREAD

**Issue by jari-rajasalo** [tyrasd/overpass-turbo#692]
Getting error 503 Service Unavailable when clicking Share-button. Also old shortened links are not working.

**Comment by tordans** [comment]
It's even worse, decoding URLs linke https://overpass-turbo.eu/s/1JEr does not work either. Same 503.

Ping @tyrasd

**Comment by pyrog** [comment]
Can't paste this [url](https://overpass-turbo.eu/?q=LyoKCiovCltvdXQ6eG1sXcSAZml4ZWQgYnkgYcSJbyByZXBhaXLEhFt0aW1lxIjEijI1MDBdOwovLyBnYXRoZXLEnWVzdWx0c8SyL253clsid2Vic2l0ZSJ-ImNhbXB0b8WUxZYixLDFg8WFxYcidXJsxZHFk8WVxZfFmcWnxZzEscSzxZ_FiMSnYWfFkMWSxZrFqMW1xavFnsWGxYhkxL1jcmnFl2lvbsWlxbXFmMW3xZ3FrcW6InPEiHJjZTpuxZXFs8WmxZbGh8WqxZ3FucWgxJHEjMaVxobFqcWbxprGisWgxYrFjMWOxpFhY8aQc3PGhcWnxpjGosWsxYTGi8aNxaLGkDplbMafxrDGoXDFuMWuxozGjsaQxq_Gl8a-xbgKKC5fOz47KTsgxKogxKh0YTvEkMSSxJTElsSYxJrFmMS8xKDEosSE&c=BL5Rn5akPG) in JOSM (probably longer than 255 characters)

**Comment by tyrasd** [comment]
the service is now up again. it looks like some bot or automated script was spamming the service with invalid `/create` requests which caused it to crash. sorry for the inconvenience. it should now also more robustly handle such invalid requests.

**Comment by DaveF63** [comment]
This problem appears to have resurfaced.

**Comment by tyrasd** [comment]
> Allow users easy copying of the real link.

That's easy: just paste the short link into a new browser tab, press <kbd>Enter</kbd> and copy the un-shortened generated URL.

**Comment by jidanni** [comment]
> That's easy: just paste the short link into a new browser tab, press <kbd>Enter</kbd> and copy the un-shortened generated URL.

Yes, but the average user is not sure that is the officially recommended way. They would have to figure that out by trial and error.

They might even think that the short url is the one that is always guaranteed to work, and the long url might be the one that could fail sometimes.

So I'm just saying please offer the users choice, right up front in the interface.

**Comment by jidanni** [comment]
Also, when I'm making my web page and including such links, I want my readers to see exactly what each link will take them to. 

If the only choice,  apparently, is the short urls, readers get worried "What am I about to click on?" 

I'm saying that both short and long should be promoted equally and not need special workarounds.

**Comment by DaveF63** [comment]
Ping @tyrasd
This problem appears to have resurfaced again.

Apache/2.4.58 (Ubuntu) Server at overpass-turbo.eu Port 443

**Comment by thofrey** [comment]
I confirm. Tiny-url creation fails. Also calling saved links with tiny-url fails with *Service unavailable*. Already (estimated) 5 days now.

---

**Edit** works again. Many thanks.
