### ISSUE TITLE
Correct instantiation of attribution control

### ISSUE THREAD

**Issue by erictheise** [tyrasd/overpass-turbo#702]
Working on attribution strings downstream at OHM it appears that [these two lines](https://github.com/tyrasd/overpass-turbo/blob/4ca2e6641e8d3fd174cffe3054d14fe338528064/js/ide.ts#L492-L493) have no effect. An attribution control needs to be instantiated, then added to the map like this

```
const attribControl = new L.Control.Attribution({position: "bottomright"});
attribControl.addAttribution(tilesAttrib);
attribControl.addTo(ide.map);
```

Note that the attribution control that appears on the live site is the one created when the Leaflet map is [initialized](https://github.com/tyrasd/overpass-turbo/blob/4ca2e6641e8d3fd174cffe3054d14fe338528064/js/ide.ts#L478-L483), as [`{prefix: false}`](https://github.com/tyrasd/overpass-turbo/blob/4ca2e6641e8d3fd174cffe3054d14fe338528064/js/ide.ts#L492) is not honored.

**Comment by tyrasd** [comment]
should be fixed with #703, right?
