### ISSUE TITLE
Auto repair: Add round brackets if there are multiple lines

### ISSUE THREAD

**Issue by danieldegroot2** [tyrasd/overpass-turbo#720]
Ask the user if they want to add round brackets around their query if they are making multiple queries.
```
...
nwr[1]({{bbox}});
nwr[2]({{bbox}});
...
```
Without round brackets, semi-colon (and indentation) only the second line will be run/rendered.

Modify existing query to include them
```
...
(
  nwr[1]({{bbox}});
  nwr[2]({{bbox}});
);
...
```
The user can then succesfully run the query.

It is of course only a minor issue, which can happen any time you accidentally remove the brackets (when switching to a single-line query for example).

**Comment by mmd-osm** [comment]
By the way, Overpass QL has no concept of indentation, it's not relevant in any way.
