### ISSUE TITLE
saving query in user store

### ISSUE THREAD

**Issue by ghost** [tyrasd/overpass-turbo#89]
I often type the same queries over and over again. My session-data get destroyed at browser shutdown: The current **save** button doesnt work for me.

Nice additional possibility for overpass-turbo would be, to save your queries in a closed overpass-turbo store, for a signed in (osm) user.
Tags, descriptions and date informations will bring back the overview to important and common user related queries.

Best regards Johannes

**Comment by tyrasd** [comment]
FYI: Queries can soon be synced with an osm.org account (testing on http://overpass-turbo.eu/master/ is already possible).
